### ISSUE TITLE
Python error: Internal error setting the array gltf2_blender_export.save()

### ISSUE THREAD

**Issue by jitspoe** [KhronosGroup/glTF-Blender-IO#1866] opened 2023-02-10 02:34 UTC
**Describe the bug**
Python error when exporting:
![image](https://user-images.githubusercontent.com/7751182/217985584-4606509e-e29e-4f48-b900-90a058da4659.png)

**To Reproduce**
Export attached file as "gltf".

**Expected behavior**
It works.

**Screenshots**
![image](https://user-images.githubusercontent.com/7751182/217985584-4606509e-e29e-4f48-b900-90a058da4659.png)

**.blend file/ .gltf**
[chest.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/10703156/chest.zip)

**Version**
 - OS: Windows 10
 - Blender Version 3.4.1

**Comment by julienduroure** [comment] 2023-02-10 06:24
Hello,
I can not reproduce it, on 3.4 neither current 3.5 alpha (linux)
Do you use some option at export?
Can you please try to reset to factory settings before exporting?

**Comment by jitspoe** [comment] 2023-02-20 00:08
Hmm, I didn't change any settings, but it no longer seems to reproduce the error.  The worst kind of bug!  😐

**Comment by ara-martirossyan** [comment] 2023-02-22 21:14
Hello,
I have the same error when i try to export as gltf with the following blend file
[climb.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/10808356/climb.zip)

**Comment by julienduroure** [comment] 2023-02-23 06:47
@ara-martirossyan 
Hello,
No, your error is not the same than the traceback from this ticket.
Your issue is a duplicate of #1803 
This will be fixed in Blender 3.6, and before release, you will find a workaround in #1803 
Thanks !

**Comment by ara-martirossyan** [comment] 2023-02-23 09:05
@julienduroure 
Hello, thanks for feedback and the reference to actual  issue
Then, I don't mean to spam in here, but I somehow realized that if i unselect "Always Sample Animations"
I manage to export successfully. Thanks again!

**Comment by julienduroure** [comment] 2023-02-25 10:25
About the original bug:
Let's this ticket open 1 month. If nobody success to reproduce during this time, I will close the ticket.

**Comment by julienduroure** [comment] 2023-03-27 14:13
Hello,
Seems nobody reproduced it :(
Let's close this ticket.
Feel free to open a new one if you encounter it again!

**Closed by julienduroure** 2023-03-27 14:13 UTC
Labels: question
