### ISSUE TITLE
Sheen Intensity & Sheen roughness gets exported as black values.

### ISSUE THREAD

**Issue by AsuraSloth** [KhronosGroup/glTF-Blender-IO#1728] opened 2022-09-16 12:53 UTC
**Describe the bug**

Sheen intensity and Sheen roughness get exported as black values.

**To Reproduce**

1. Follow the documentation to add a Sheen Colour & Sheen Roughness texture to the shader setup (using a velvet BSDF & Add Shader).
2. Export the GLB output. (blender 3.3.0)
3. Use a GLTF viewer like Khronos Sample Viewer and check the Sheen & Sheen roughness channels.

**Expected behavior**
The Sheen & Sheen Roughness channels will show black.

**Screenshots**

The Sheen value shows black.
![sheen output](https://user-images.githubusercontent.com/85283488/190639387-02b590ec-ef95-48f6-9259-f5c881de94d6.jpg)

The Sheen Roughness values also show black
![sheen roughness](https://user-images.githubusercontent.com/85283488/190639473-c83e5806-bff6-431d-ad78-5149042a0408.jpg)

The Sheen Colour shows up correctly.
![Sheen Colour](https://user-images.githubusercontent.com/85283488/190639514-2b098744-7ec8-4dc7-91b9-73f68eb2c28c.jpg)

Shader Setup
![Node Settings](https://user-images.githubusercontent.com/85283488/190639700-dceb5821-0402-4fa7-99f8-ecd10c4131eb.jpg)

Shader Setup after reimporting GLB file.
![Shader After export](https://user-images.githubusercontent.com/85283488/190639788-b0f37e84-5345-4a48-b98f-8f900465c825.jpg)

**.blend file/ .gltf**
My zip file is higher than 25 mb, so heres a wetransfer link https://we.tl/t-JsshTFtFxB

**Version**
 - OS: [Windows 11 Home]
 - Blender Version [3.3.0]

**Comment by julienduroure** [comment] 2022-09-16 13:53
Confirmed. Bad default factor is used.
Will be fixed in 3.3.1
As a workaround waiting the release, you can add Math node and MixRGB node, as you can see when you re-import the file, bug using 1.0 for Math node, and white (1.0/1.0/1.0) for MixRGB

**Comment by AsuraSloth** [comment] 2022-09-16 14:02
Thank you very much Julien, this will help.

P.S: I'm new to github and I am not a programmer, so Im not sure if 'close to comment' is the right process here.

**Comment by julienduroure** [comment] 2022-09-16 14:04
Don't worry, let it open, I will close it when I will merge the code.
Thanks :)

**Comment by AsuraSloth** [comment] 2022-09-17 09:14
I have tried the fix and there still seems to be an issue with the Sheen Roughness Channel. It gives a plain white value even if a texture is plugged in.

Sheen Roughness Error
![sh rg combined](https://user-images.githubusercontent.com/85283488/190849380-cce3dbac-d7d2-41de-9646-502f63615e5e.jpg)

Heres my shader setup before export
![Before export _02](https://user-images.githubusercontent.com/85283488/190849400-cd1e9c4d-629d-47c4-a272-8f5291c0fc06.jpg)

Heres the shader setup on reimport
![After export _02](https://user-images.githubusercontent.com/85283488/190849435-9bd79f36-736f-49e0-9aba-d41d9daa64bf.jpg)

Not sure if im doing something wrong though. I can't seem to find the solution for this.

Heres the download link to the blender and GLB file. https://we.tl/t-Kc8Km4PQ3J

**Comment by julienduroure** [comment] 2022-09-17 09:35
The Roughness must be map on alpha channel of texture

**Comment by AsuraSloth** [comment] 2022-09-17 11:38
Sorry Julien, having the sheen roughness texture in the alpha channel doesn't help either.

![sheen viewer combine](https://user-images.githubusercontent.com/85283488/190854603-f364e755-6f22-4192-a1cf-34436b470b43.jpg)

Shader before export
![before export_02](https://user-images.githubusercontent.com/85283488/190854625-334e0a89-2914-4910-816c-8d0253dc7c40.jpg)

Shader on reimport
![after export_02](https://user-images.githubusercontent.com/85283488/190854629-8b10c1a7-7964-40b1-a658-558132de6ba7.jpg)

Heres the files https://we.tl/t-AyznNe9HTs

**Comment by julienduroure** [comment] 2022-09-17 11:58
At first look, this setup looks OK, and export seems to be OK. If you export gltf + separate textures, you can see the roughness sheen texture with alpha ok.
Maybe there is a bug in Sample Viewer, because if you choose the sample of Khronos (for example SheenCloth), the same white is displayed, even if there is some roughness.

**Comment by AsuraSloth** [comment] 2022-09-17 12:49
Yes you are right, its a problem with the viewer. Both the Khronos Viewer and Don McCurdy's viewer doesn't display Sheen Roughness properly. But the Babylon js viewer does.

Heres the incorrect view on Khronos (the sheen is applied everywhere).
![Screenshot 2022-09-17 at 17-49-49 glTF Sample Viewer](https://user-images.githubusercontent.com/85283488/190857603-dc521c20-d3f2-4679-9e2b-c0d00253589e.png)

Heres the correct view on Babylon js (sheen is applied based on grunge texture)
![Screenshot 2022-09-17 at 17-48-59 Babylon js - Sheen_Test_03 glb](https://user-images.githubusercontent.com/85283488/190857624-45aae8ec-5880-4df8-aaab-021b9de030a9.png)

Thank you for your help Julien & sorry for the time it took to clarify the doubts.

**Closed** 2022-09-19 06:47 UTC
Labels: bug, exporter, Material
