### ISSUE TITLE
JPEG Quality slider value is not affecting the final texture output

### ISSUE THREAD

**Issue by jacv2593** [KhronosGroup/glTF-Blender-IO#2056] opened 2023-11-16 14:47 UTC
When manually adjusting the value of the quality slider downwards or upwards, the final output is not being affected by the new value.

1. Export a 3D object with textures using the .glb exporter
2. Navigate through the export settings, Data, Material, Images (change to JPEG), adjust the quality slider down or upward
3. Export the result and compare it to a different value of the quality slider
4. Both files, even though have different texture quality values, have the sime file size output (which wasn't the case in previous versions of blender)

Texture quality should've been drastically reduced in file size and quality.

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/20290045/d8565025-c285-4db4-9fe4-df961f026eff)
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/20290045/05433a54-deeb-4fd4-bc94-43d468b314bb)

[glb-exporter-issue.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/13379001/glb-exporter-issue.zip)

OS: Windows
Blender: Release 4.0.0

**Comment by julienduroure** [comment] 2023-11-16 14:54
Hello,
This is a duplicate of #2055 
Already fix. This will be available in 4.0.1 (planned for tomorrow)

**Closed by julienduroure** 2023-11-16 14:54 UTC
