### ISSUE TITLE
Radically high export times with new Blender 3.3 / 3.4 version glTF-2 exporter

### ISSUE THREAD

**Issue by lyonheart001** [KhronosGroup/glTF-Blender-IO#1822] opened 2023-01-06 16:53 UTC
**Describe the bug**
Very high export times when exporting a model to glTF separated version files for MSFS flight simulator.  The previous version exported a sophisticated file project in several seconds.  It now takes minutes to export the same file with the new Blender 3.3 / 3.4 Khronos version exporter.

**To Reproduce**
1. Export an aircraft complete with PBR materials and animations
2. Export as glTF-2 MSFS version Export
3. Note export times.

**Expected behavior**
Export on Blender 3.2 and earlier versions, same file, 5 to 6 seconds.
Export with new Khronos version glTF-2 exporter for Blender 3.3 / 3.4 / 3.5, several minutes.  3 to 5+ minutes.

**Screenshots**

**.blend file/ .gltf**
If applicable, a zipped folder containing a .blend file for exporter issues and a .gltf file for importer issues. Please take care to include all resources, such as textures in the .zip file.

**Version**
 - OS: [e.g. macOS, linux]
I am using Windows 10, 32 Gigs of RAM, 6 Gigs of VRAM.
 - Blender Version [e.g. 2.82, 2.83, or build date]
Blender 3.2 and Blender 3.4.  For projects that are taking too long to export, I am reverting them back to Blender 3.2 format to export them.  The time to export is far to long and costly.  There are 7 model exports per export process, each being either an interior or exterior model, and also models of LOD detail levels, so with Blender 3.2, it takes a couple of minutes for all of those to be exported.  For Blender 3.3 and 3.4, it takes a radically high amount of time to export all of those.  Not good for production.  

**Additional context**
I wonder what has caused the massive, dramatic jump in export times?  Sad, as it was lightning fast before.

**Comment by julienduroure** [comment] 2023-01-06 17:20
Hello,
Please provide a .blend file you are trying to export
Note that if you don't provide a test file, I will not be able to investigate.
I will test it with official glTF export, not with MSFS, as I am not the maintainer of the MSFS extenstion

**Comment by lyonheart001** [comment] 2023-01-06 18:56
Just sent.

**Comment by julienduroure** [comment] 2023-01-11 17:42
Tested with file Test_Package/model/LearFan 2100 Blendr 3.3 573.blend

This file was created with 3.4, so I can't open it in 3.2 without any warning
![image](https://user-images.githubusercontent.com/1696020/211876240-7b7d3582-a87a-4694-8ed1-193440a46a51.png)

The file has some "Remember settings", so exporting it without changing anything....

- Exporter time in 3.2 (even if I can't take it into account because file is from 3.4) : 1.3s
- Exporter time in 0.5s

Trying with Test_Package_01/model/Pacer Blender 3.4 033.blend

Same issue with test cases:
- Created with 3.4, so can't guarantee exporting in 3.2
- They are some Remember settings, so exporting without changing anything 
- Export times : 4.85s in 3.2 / 4.76s in main branch

Trying with Test_Package_01/model/Piper Pacer 003.blend

Same issue with test cases:
- Created with 3.4, so can't guarantee exporting in 3.2
- They are some Remember settings, so exporting without changing anything 
- Export times : 13.17s in 3.2 / 4.75s in main branch

If you want me to analyze your issue, please send me a file (and only 1 blend file):
- Created in 3.2 or previous version
- If you use "Remember Settings", be sure that your export settings and selection are ok
- I will compare time of the same file in 3.2 and main branch

Without any new information within a week, I will close this ticket.

Thanks !

**Comment by tonypez** [comment] 2023-01-25 22:11
> Without any new information within a week, I will close this ticket.
> 
> Thanks !


Hello Julien,

I have the same Issue as the guys above, the export times with Blender 3.3 and Msfs2020 1.1.7 exporter (glTF2 Khronos) got much longer.

If we export the main assembly of our aircraft with blender 3.1, this takes 1 min;
If we export the same file with blender 3.3, this takes 55min.

I have converted my aircraft into a big dummy file, renaming all confidential names and converting all meshes into spheres.
If you please give me your email, I can send you this data so you can test the export time problem yourselves.

Thank you

**Comment by ronh991** [comment] 2023-01-25 22:24
I am also having long export times.  Even without the MSFS plugin enables - just to make sure it was not the ASOBO plugin.

This issue seems to stem from making a model in 3.1.x and then trying to continue it in 3.3+ . 

Here is a blend file that also will error out if you try to export glttf in 3.3.3 but will export without error in 3.1.2

3.1.2 export
22:22:09 | INFO: Starting glTF 2.0 export
22:22:09 | INFO: Extracting primitive: Plane.083
22:22:09 | INFO: Primitives created: 1
22:22:09 | INFO: Finished glTF 2.0 export in 0.012270689010620117 s

3.3.3
22:23:15 | INFO: Draco mesh compression is available, use library at F:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\site-packages\extern_draco.dll
22:23:39 | INFO: Starting glTF 2.0 export
22:23:39 | INFO: Extracting primitive: Plane.083
22:23:39 | INFO: Primitives created: 1
Traceback (most recent call last):
  File "F:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\__init__.py", line 648, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "F:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 35, in save
    json, buffer = __export(export_settings)
  File "F:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 52, in __export
    __gather_gltf(exporter, export_settings)
  File "F:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 66, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "F:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 34, in gather_gltf2
    animations += __gather_animations(blender_scene, export_settings)
  File "F:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 93, in __gather_animations
    animations_, merged_tracks = gltf2_blender_gather_animations.gather_animations(obj_uuid, merged_tracks, len(animations), export_settings)
  File "F:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animations.py", line 131, in gather_animations
    animation = __gather_animation(obj_uuid, blender_action, export_settings)
  File "F:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animations.py", line 174, in __gather_animation
    channels=__gather_channels(obj_uuid, blender_action, export_settings),
  File "F:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animations.py", line 211, in __gather_channels
    return gltf2_blender_gather_animation_channels.gather_animation_channels(
  File "F:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "F:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_channels.py", line 128, in gather_animation_channels
    channel = gather_animation_channel(
  File "F:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_channels.py", line 268, in gather_animation_channel
    sampler = __gather_sampler(channels, obj_uuid, export_settings, bake_bone, bake_channel, bake_range_start, bake_range_end, force_range, action_name, driver_obj_uuid, node_channel_is_animated)
  File "F:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_channels.py", line 336, in __gather_sampler
    return gltf2_blender_gather_animation_samplers.gather_animation_sampler(
  File "F:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "F:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_samplers.py", line 59, in gather_animation_sampler
    input = __gather_input(channels, obj_uuid, is_armature, non_keyed_values,
  File "F:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "F:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_samplers.py", line 243, in __gather_input
    keyframes, is_baked = gltf2_blender_gather_animation_sampler_keyframes.gather_keyframes(blender_obj_uuid,
  File "F:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 38, in wrapper_cached
    result = func(*args, **kwargs)
  File "F:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animation_sampler_keyframes.py", line 356, in gather_keyframes
    mat = get_object_matrix(blender_obj_uuid,
  File "F:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 92, in wrapper_objectcache
    return result[cache_key_args[0]][cache_key_args[1]][cache_key_args[4]]
KeyError: 1.0

same file


[EXPORT_FAIL_ACTION_Isolated_blender3.1.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/10504236/EXPORT_FAIL_ACTION_Isolated_blender3.1.zip)

**Comment by tonypez** [comment] 2023-01-25 22:38
I have just created a dummy file from my production assembly that proves the export times are screwed with blender 3.3 (and 3.2):
Here the download link from Wetransfer
https://wetransfer.com/downloads/dda907f4638cdf43018645b43d8243e920230125223234/26d614?utm_campaign=TRN_TDL_05&utm_source=sendgrid&utm_medium=email&trk=TRN_TDL_05

If you export this data with Blender 3.1.2 as glTF2 this takes 1min
if you export this data with Blender 3.3 as glTF2 this takes 50min circa.

Hopefully you guys can drop a fix asap since it is impossible to use newer versions of blender currently given this issue.

Thank you

**Comment by julienduroure** [comment] 2023-01-26 08:48
Hello,

- you can send me an email to contact ATT julienduroure DT com for the file
- I cannot reproduce the traceback on 3.3.3 nor main with your settings. When you save export settings with "Export Selection only", please keep to not change your selection when you save the file.
- When not using "export selection only", I can reproduce on 3.3.3, and main too (but not on animation refactor project). I will check
- About animation:
  - When using "Export selection only", all exported animation are baked, in case some parent are animated
  - You can remove these animation (when object is really not animated) using the "Optimize animation size" option
  - This will be changed on Blender 3.6, where "export selection only" and "bake animation" will be split into 2 options

**Comment by tonypez** [comment] 2023-01-26 11:00
> Hello,
> 
> * you can send me an email to contact ATT julienduroure DT com for the file
> * I cannot reproduce the traceback on 3.3.3 nor main with your settings. When you save export settings with "Export Selection only", please keep to not change your selection when you save the file.
> * When not using "export selection only", I can reproduce on 3.3.3, and main too (but not on animation refactor project). I will check
> * About animation:
>   
>   * When using "Export selection only", all exported animation are baked, in case some parent are animated
>   * You can remove these animation (when object is really not animated) using the "Optimize animation size" option
>   * This will be changed on Blender 3.6, where "export selection only" and "bake animation" will be split into 2 options
> 
> Edit: I created #1842 to manage the traceback. Let's this ticket about performance

Hello Julien,
Thank you for the email, I just sent you the file

**Comment by lyonheart001** [comment] 2023-01-28 17:09
Thank you Julien for researching this.

**Comment by lyonheart001** [comment] 2023-01-28 17:35
Julien, 
In my case, I brought in a glTF to Blender 3.2 or higher (possibly 3.3 or 3.4) and the frame rates were radically high, normally 50, 100, and 200 KF's for imported animations.  They were suddenly 2400, 4800, etc.  I reduced them in Blender in 'Animation Track; Scale' to proper lengths.  But...  With those models I imported up to 3.3/3.4, they had the huge export times.  A plane fully made and animated in Blender 3.4, for instance, had 'no' long exports.  But animations that were imported (from glTF to Blender), those had gigantic export times.  Both used 'export selected'.  I wonder if somehow Blender is messing up this with the handling of animation tracks using a 'scale' now?  Just a thought.

Bill

**Comment by julienduroure** [comment] 2023-01-28 17:53
Hello,
For importing, please refer to #1823 
Please try reset your settings to factory settings. You are probably not using the same frame rate in all your Blender version. As far as I understand, => no bug here.

For exporting time, investigation is still in progress, but in 3.2 comes a better way to export animation, because before 3.2, most of animation exports can be wrong. Now (3.2+), animations are baked to be sure they are correctly exported.
Because you have not any active action on most of your objects, baking can not be cached in 1 pass, and baking take place for any of your objects.

In 3.6, Blender will come with more option to export animation, as a "Scene" option, when you don't want to manage action library (like for game engine for example). Seems to be the case in your file. Animations will be exported as they are seen in Viewport.
Trying to file with this option, can export it in 88s.

**Comment by 3blake7** [comment] 2023-03-19 14:39
I am importing and exporting a bunch of .glb's. i noticed my file sizes getting gradually larger with each export. the NLA tracks are the problem, the 10th animation has all the NLA Tracks from the proceeding 9. its like there is an NLA Track database and it's exporting all of them instead of the just the ones associated with that armature and it's not deleting them when i delete the armature.

**Comment by julienduroure** [comment] 2023-03-19 17:05
@3blake7 Can you please create a new ticket (with your test cases files), as the issue is not the same than current ticket.

About current ticket: Let's close it, as 3.6 alpha can now export animation in "Scene" mode, with separated animation for each object.
This will help in your case, as you have only 1 animation to export for each object

**Closed by julienduroure** 2023-03-19 17:05 UTC
Labels: question
