### ISSUE TITLE
Multiple duplicated skins are exported for each mesh child of the armature

### ISSUE THREAD

**Issue by dpalacio** [KhronosGroup/glTF-Blender-IO#566] opened 2019-06-25 23:02 UTC
**Description**
When an armature in Blender has multiple children meshes, each mesh gets its own skin copy in the glTF export. The result is multiple skeletons, one for each child mesh, in the exported file. 

**To Reproduce**
1. Open the attached .blend file and check the hierarchy
2. Export scene to .gltf text
3. Verify that multiple skeletons have been created

**Expected behavior**
A single skin/skeleton should be made for each Blender armature

**Test case**
I have attached a blend file to help reproduce the behavior. I'm no 3D modeler so please excuse the content.
[blender_export_skin_test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3327531/blender_export_skin_test.zip)

**Version**
 - OS: Linux
 - Blender Version: blender-2.80-c0c1b4542f39-linux-glibc224-x86_64

**Additional context**
This behavior has been referenced also in issue #331, which I have also have seen happen.

**Comment by marstaik** [comment] 2019-08-05 07:04
I recently ran into this behavior on my own, without the test case, while trying to import to Godot.

This is a very annoying problem to deal with, every mesh has a skeleton copy.

**Comment by fire** [comment] 2019-08-06 11:39
Will review.

**Comment by julienduroure** [comment] 2019-08-09 18:19
@donmccurdy @emackey I have a question about inverseBindMatrices: If multiple mesh objects are linked to an unique armature, I don't know how to create only 1 skin object in glTF, because inverseBindMatrices are differents ... Any thoughts / test cases / info about that ?

**Comment by emackey** [comment] 2019-08-09 19:18
Sorry, I don't know about skins/armature.  @donmccurdy?

**Comment by donmccurdy** [comment] 2019-08-13 04:36
The child meshes are not just rigidly transformed by the parent bones, I assume, but their vertices are weighted and transformed? In the rigid case, like parts of the ["Robot" example](https://threejs.org/examples/?q=animatio#webgl_animation_skinning_morph), the child meshes do not need skins at all.

Assuming the more complex case where each child mesh's vertices are transformed, I believe one option would be to create a new skin with unique inverseBindMatrices for each mesh, while reusing the same joints (or a subset of the joints) for each skin. Then the skeleton hierarchy is not duplicated, and each mesh has its own matrix.

This test case covers the situation above: https://bghgary.github.io/glTF-Assets-Viewer/?manifest=https://raw.githubusercontent.com/KhronosGroup/glTF-Asset-Generator/v0.6.0/Output/Manifest.json&folder=2&model=8

/cc https://github.com/KhronosGroup/glTF/issues/1454

Is that approach sufficient? We've discussed other alternatives for sharing skins in the future, but this would require an extension and isn't in progress right now: https://github.com/KhronosGroup/glTF/issues/1285

**Comment by julienduroure** [comment] 2019-08-13 19:37
Currently the cache of gather_skin function has 2 parameters : blender_object (armature) and mesh_object (the skinned object). That's why 2 skins are generated, because the mesh_object is different. Mesh object is used to generate/calculate the inversedBindMatrix. So my main issue is that I use a unique IBM for multiple meshes only if mesh objects have same transformation...
@donmccurdy did I miss something? Do you have any link to explain exactly what are IBM?

**Comment by donmccurdy** [comment] 2019-08-13 20:39
> That's why 2 skins are generated, because the mesh_object is different...

As long as the 2 skins don't result in duplicate joints, I think that's not too bad. If the meshes _can_ use the same IBM, they might as well share a skin of course, but not doing so is not as bad as duplicating the joints.

Does this help, as an IBM explanation? https://github.com/KhronosGroup/glTF/issues/1504 ... afraid i'm not the best person to help with that. 😅

/cc @lexaknyazev just confirming the IBM transforms from the node's coordinate space into the joint's coordinate space, I think sharing joints in several skins is consistent with the spec?

**Comment by marstaik** [comment] 2019-08-20 08:35
To be honest this is what I dislike about the gltf spec. Joints can be used for multiple skins, but the joints mentioned in those skins *could* belong to a sunset of the "skeleton".

I put skeleton in quotes, because there is no way to know what actually establishes a full armature in the current spec.

You could have an armature, with two arms, and two meshes each bound to one arm. The exporter could export skin bindings separately for each arm, which only include the joints of the arms, and not the entire armature.

This results in two subsets of a skeleton in the two skin definitions, with no easy way to derive what the "entire" skeleton should be. You have to result to some combination of disjoint sets to establish a parent relationship, using either the "optionally" defined "skeleton" parameter, or just join all the sets at the root.

Not to mention I haven't seen anything in the spec that prevents a mesh from also being a joint. In this case, any game engine will have to do some manual "ghost" bone creation to get the actual expected behavior. No game engine off the top of my head allows using a mesh object as a target for animation.

Then, there's another issue with the multiple skins and animation channels, and having to remap the channel targets to your "derived" skeleton to get animation play back to work correctly.

The extra exported skins and lack of proper skeleton definitions make all of this infuriating to work with due to the additional complexity I have to build in order to handle these weird situations, not to mention just the extra parsing time required to go through all the duplicated inverse bind matrices and skin definitions.

**Comment by reduz** [comment] 2019-08-20 17:38
Actually, I don't blame the GLTF specification for this, I think the Blender exporter has misunderstood it. 

If you have a skeleton and different meshes, the spec is very clear that all the mesh transform (the transform in the actual nodes) code must be ignored. This means, that you must transform the mesh vertices, normals, tangents, etc. and make them skeleton-local.

This way, multiple meshes will work with a single skeleton. I don' t think there is any way around this, and the exporter does not seem to be doing the right thing.

**Comment by reduz** [comment] 2019-08-20 17:46
Please read here:

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#skins

`
Implementation Note: Client implementations should apply only the transform of the skeleton root node to the skinned mesh while ignoring the transform of the skinned mesh node. In the example below, the translation of node_0 and the scale of node_1 are applied while the translation of node_3 and rotation of node_4 are ignored.
`
The intention of the spec is that if you mesh has a transform different to the skeleton transform, you apply it before exporting it. This makes it much easier for importers. You are trying to work this limitation around by moving the skeleton to where the mesh is, and this goes against the intention of the spec, and makes you so pretty bad hack to support multiple skinned meshes with one skeleton.

**Comment by marstaik** [comment] 2019-08-21 11:33
Reading through it again, that makes more sense.

But it also seems unreasonable to expect implementers to ascertain the actual implications  of that line. As that note reads, it means that the *reader* should ignore any transforms on the meshes skinned to the skin, even if they are defined.

It mentions nothing about requiring the *exporter* to localize/apply the meshes transformations during export to that of the skeleton. But now, after reading that note, we can see that is what they intend.

This seems like a but of ambiguity in the specification that should probably be brought up in the gltf spec...

**Comment by reduz** [comment] 2019-08-21 12:19
@marstaik Yeah, you are right, I think this should be more explicit or, at least, a recommendation in the specification.

**Comment by emackey** [comment] 2019-08-21 14:37
Great discussion.  @marstaik Would you be willing to open a PR with that note on https://github.com/KhronosGroup/glTF ?

**Comment by marstaik** [comment] 2019-08-21 15:59
I would love to, but I am currently out of the country on vacation. ETA of return is ~1.5 weeks and all I have is my phone :)

Unless you would like to wait for me to return, I'd be willing to review the PR if someone else has the time to make it.

I do feel that this is quite an important change to get in, it would correct a lot of exporter issues.

**Comment by donmccurdy** [comment] 2019-08-21 18:10
It has been difficult to determine all of the use cases that should (or should not) be handled by skinning, and how to implement them consistently in runtime and DCC tools. See https://github.com/KhronosGroup/glTF/issues/1403 for some examples.

That said, I do think tightening glTF's requirements — or just adding solid best practices — would be very welcome additions to the spec and appendices. 👍

I realize this is a big ask, but would someone have time to attempt a PR fixing the exporter per the suggestion above? It has been a very bumpy road to get the addon's skinning export as stable as it is today (thank you to everyone who contributed!) and so we should plan to spend some time regression testing any major changes now.

**Comment by julienduroure** [comment] 2019-08-22 03:21
I started working on it

**Comment by marstaik** [comment] 2019-08-23 10:11
I made a post about potential sticter skinning requirements to make importing less complicated. I would appreciate some feedback.

**Comment by julienduroure** [comment] 2019-08-23 12:21
Some notes about the corrective development : 
I already be able to export correclty 2 meshes (with different transforms) deformed by only one armature (at a third transform) --> export with only 1 skin.
Still have to test lots of configuration, and still have to fix normals & tangents, but this is promising.
I hope to be able to provide a complete PR during next week.

**Comment by julienduroure** [comment] 2019-08-25 07:19
Not sure to export it correctly yet, but with glb file in attachment, I get some different results on few viewers: (generated with branch fix_IBM)

- https://gltf-viewer.donmccurdy.com/ (tree.js) : Seems OK
- https://sandbox.babylonjs.com/ : Seems OK
- godot 3.1.1 : Not OK
- own blender importer : Not OK

Original file: (skin_posed)
![image](https://user-images.githubusercontent.com/1696020/63646605-9932e180-c715-11e9-840b-dcede1acbe44.png)

Results in different viewers:

![skin](https://user-images.githubusercontent.com/1696020/63646597-7a344f80-c715-11e9-9c24-b3d583392485.png)

In order to understand what happen, I made a case identical to previous, except that pose is the same as rest pose. (Skin_not_posed): Everything seems to be OK in treejs, babylonjs, godot. Only Blender importer is wrong.

I tested with very simple case (skin_simple_not_posed):
Everything seems to be OK everywhere

And with very simple case, but with a pose != rest pose:
Seems that Godot do not take into account the current pose on the glb file when it's different to rest pose

![image](https://user-images.githubusercontent.com/1696020/63646774-72c27580-c718-11e9-8347-212f29fe77a2.png)
![image](https://user-images.githubusercontent.com/1696020/63646786-94236180-c718-11e9-9a96-cc647b293011.png)

To conclude:
We have to fix some things in importer, and I will contact @reduz in order to know if my guess is true about godot importer

All files:
[test_skin.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3537913/test_skin.zip)

**Comment by julienduroure** [comment] 2019-08-29 17:12
Doing the same exercice, but with a file with animation.

treejs, babylonjs and blender importer are displaying same result, that is the animation from original file.

![image](https://user-images.githubusercontent.com/1696020/63961246-a7279000-ca90-11e9-9151-b328aca55be4.png)


Godot 3.1.1 is not displaying the same result:

![image](https://user-images.githubusercontent.com/1696020/63961300-c58d8b80-ca90-11e9-80d7-462f36703b82.png)


See with @reduz --> I am going to open an issue in godot repository to understand where is the issue.

Files : 
[animated.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3556665/animated.zip)

**Comment by julienduroure** [comment] 2019-09-13 20:06
Should be fixed now!

**Closed by julienduroure** 2019-09-13 20:06 UTC
Labels: Skinning_&_Rigging, exporter
