### ISSUE TITLE
Normal Maps Export Incorrectly 

### ISSUE THREAD

**Issue by ManishJu** [KhronosGroup/glTF-Blender-IO#1473] opened 2021-10-04 13:19 UTC
**Describe the bug**

The normal map is not exported correctly with the model provided in the file. When you export and  import the model back you can see the incorrect normal map. After import, on changing the mode of Color-Space from Non-Color ( Correct ) to sRGB ( Incorrect ) in the Normal texture node  
the rendering results become correct !?

**To Reproduce**
1. Go to Shading tab and see the correct normal map and its settings
2. Click on File->Export->gltf2
3. Select Format type : gltf Binary
4. In Include , select the selection "Selected Objects"
5. In Transform, select +y option
6. In geometry select UV and NORMALS
7. In animation do not select anything.
8. Name the file anything and save.
9. Import back the saved file 
10. Go to the shading tab and you will see the model imported with incorrect normal.

**Expected behavior**
The normal map should behave correctly in Non-Color mode after import

**Screenshots**
You can see the incorrect import and the original correct model with the same shader graph
![bug1](https://user-images.githubusercontent.com/24234466/135856661-96aa58e0-cfa2-45bd-bb5e-bd21cd2d5a06.jpg)

**.blend file/ .gltf**
link to file : https://drive.google.com/file/d/1WE5Ku22UWeTxKJu46uUnHVaYjxjmuYTf/view?usp=sharing

**Version**
 - OS: Windows 10
 - Blender Version : 2.93.4
 - GLTF Exporter Version : Default 1.6.16 and Latest 1.17.30

**Comment by ikermozos** [comment] 2021-10-09 02:03
@donmccurdy I was having this very same issue a couple of days ago, and converting the EXR to PNG in Blender solved the issue indeed.

**Comment by optimus007** [comment] 2022-09-30 11:23
can confirm with most models from polyhaven as they use exr as default texture format for the models

 eg:  https://polyhaven.com/a/drawer_cabinet

the normal map texture seems to be exporting in linear color space instead of sRGB

Before
![exr](https://user-images.githubusercontent.com/6885294/193258973-57d27145-b7d2-4bdd-accd-ca2d17697fff.png)

After changing the normal map's color space from 'non-color data' to 'sRGB'
![exrsrgb](https://user-images.githubusercontent.com/6885294/193258983-9257b996-e9c3-460e-ac39-714426f022f5.png)

**Comment by JaduBen** [comment] 2022-10-05 16:57
we are having this issue as well. it appears the exported normal maps are being exported in the wrong color space. the source map is correctly set to non-color. but when you import the file the normal map color is wrong and you get the faceting issue. to resolve it you need to set the normal map image to srgb. not sure how to properly resolve this.

**Comment by JaduBen** [comment] 2022-10-05 17:55
follow up, it appears this is fixed in blender 3.3

**Comment by julienduroure** [comment] 2022-10-05 19:24
Yes, I just tested with 3.3.1 released today, and problem is now solved.
Closing

**Closed by julienduroure** 2022-10-05 19:24 UTC
Labels: bug, exporter, Material

**Comment by fuckasaurus** [comment] 2024-05-27 16:30
collada still has the issue

**Comment by fuckasaurus** [comment] 2024-05-27 16:30
as of blender 4.1

**Comment by daylanKifky** [comment] 2025-05-12 09:59
I'm seeing a very similar behavior in 4.4.1

Original normal map 

![Image](https://github.com/user-attachments/assets/f74179aa-7203-4a4f-b89a-12cbaaf44a77)

Exported and reimported one:

![Image](https://github.com/user-attachments/assets/eeca4d29-aa83-4cc4-8a5d-322e236e9959)

But the GLTF specification requires normal maps to be in linear color space. This is probably happening when the source normal map image is in sRGB. The exporter is just not taking care of the conversion for you, which is probably the expected behaviour
