### ISSUE TITLE
Animations and meshes duplicated, even with same animation, parent inverse and modifier set

### ISSUE THREAD

**Issue by Cyp** [KhronosGroup/glTF-Blender-IO#55] opened 2018-10-23 14:36 UTC
If multiple nodes use the same animation, and the nodes have different parent inverses, the animations are wrong for nodes with a different parent inverse to the first node.

I'm not sure what a sane solution is that doesn't involve duplicating the animation (with different parent inverses applied to it), but reporting in case there is a possible solution.

**Comment by UX3D-nopper** [comment] 2018-10-23 15:07
Let's see, if dublicating the nodes can be avoided ...

**Comment by UX3D-becher** [comment] 2018-11-01 17:53
A refactored exporter is now enabled by default. It now creates one animation per node, possibly fixing your issue. @Cyp, could you verify that the parent inverses are now correct?

**Comment by Cyp** [comment] 2018-11-15 16:14
Sorry for the late response.

Seemed to still be getting the issue, but actually it's completely failing to save anything, so I'm not sure…

Doesn't seem to be working, after trying to reset the settings, when saving I'm getting this:
```
Traceback (most recent call last):
  File "~/.config/blender/2.79/scripts/addons/io_scene_gltf2/__init__.py", line 376, in execute
    return gltf2_export.save(self, context, export_settings)
  File "~/.config/blender/2.79/scripts/addons/io_scene_gltf2/gltf2_export.py", line 85, in save
    generate_glTF(operator, context, export_settings, glTF)
  File "~/.config/blender/2.79/scripts/addons/io_scene_gltf2/gltf2_generate.py", line 2872, in generate_glTF
    generate_animations(operator, context, export_settings, glTF)
  File "~/.config/blender/2.79/scripts/addons/io_scene_gltf2/gltf2_generate.py", line 802, in generate_animations
    process_object_animations(blender_object, action)
  File "~/.config/blender/2.79/scripts/addons/io_scene_gltf2/gltf2_generate.py", line 628, in process_object_animations
    if blender_action.name not in animations:
AttributeError: 'NoneType' object has no attribute 'name'

location: <unknown location>:-1
```

And (not really related, I think), I couldn't even get back in to the export menu after selecting export indices to `UNSIGNED SHORT`.
```
Traceback (most recent call last):
  File "~/.config/blender/2.79/scripts/addons/io_scene_gltf2/__init__.py", line 291, in invoke
    setattr(self, k, v)
  File "/usr/share/blender/2.79/scripts/modules/bpy_types.py", line 611, in __setattr__
    return setattr(properties, attr, value)
TypeError: bpy_struct: item.attr = val: expected a string enum, not int

location: <unknown location>:-1
```

**Comment by Cyp** [comment] 2018-11-15 17:06
In `def process_object_animations(blender_object, blender_action):`, I'm getting `blender_action` is `None`, for one of the two objects I was testing with. Not sure if something weird happened to the object, I had one animation set, and somehow when searching in the outliner for an old animation that isn't used, blender was incorrectly saying that the object had it. I then manually deleted it in the outliner, and it finally disappeared. Before that, it seemed to be applying a combination of the animations when exporting.

For the weird object, the down-arrow for "Switch to editing action in animation layer below the current action in the NLA stack" is permanently enabled (clicking has no effect), while the up-arrow is permanently disabled. For a normal object, both arrow buttons are disabled. I don't know what a NLA stack is, and have never used one.

**Comment by Cyp** [comment] 2018-11-15 17:30
Finally managed to un-weirdify the object by deleting an "Action stash" in an "NLA Editor", and now it can again export animations for the object.

Now that I can actually test the issue, it seems to still be exporting the same animation for both objects, not taking the different `parent_inverse`s into account.

Here's a workaround for thrown exceptions I encountered while trying to export — don't know whether it's appropriate to push to master, since the animation with the [Action stash] ends up not being exported, adding here in case it's useful:
https://github.com/KhronosGroup/glTF-Blender-Exporter/commit/02fad15f41d56933455f4f44e5e1a13c6e5de4d5

**Comment by Cyp** [comment] 2018-11-16 14:17
The mesh of two objects with the same mesh but different sets of modifiers seems to not get duplicated either.

**Comment by donmccurdy** [comment] 2019-02-01 05:09
Thanks for following up on this @Cyp – when testing with glTF-Blender-IO now, are you using Blender 2.8 or 2.79? And could you share a model that reproduces the issue?

**Comment by Cyp** [comment] 2019-02-01 07:58
Using 2.79b. Haven't tried 2.8.

[test.blend.gz](https://github.com/KhronosGroup/glTF-Blender-IO/files/2820574/test.blend.gz) → [test.gltf](https://github.com/KhronosGroup/glTF-Blender-IO/files/2820578/test.gltf.txt) (had to rename the .gltf to .gltf.txt to be allowed to upload)

Note that `SphereA` and `SphereB` have duplicated mesh data, even though they have the same modifiers.
Note that `Cube` and `SphereA` have duplicated animation data, even though they have the same animation and same parent inverse.

Since modifiers can depend on vertex sets, which seem to be per object instead of per mesh, I think testing modifiers for equality might be complicated. But if possible, it's probably better to.

**Comment by donmccurdy** [comment] 2019-02-07 15:28
I think #280 and #281 may improve things, if you're able to check.

**Comment by Cyp** [comment] 2019-02-09 08:24
Tested — those didn't affect my test case. They seem to be to do with skinning, which I'm not currently using.

**Comment by UX3D-soares** [comment] 2019-03-07 15:28
> Note that SphereA and SphereB have duplicated mesh data, even though they have the same modifiers.

The two spheres have no logical connection to us. They both use the mesh data of the cube, but they both have modifiers so we have to create mesh data for them. That they both have the same modifier setup, is unknown to us.

**Comment by UX3D-schmithuesen** [comment] 2019-03-07 17:02
> Note that Cube and SphereA have duplicated animation data, even though they have the same animation and same parent inverse.

They need separate animation data in glTF **because they have the same parent inverse**. If they would share the same animation data, their resulting world space translation would be identical.

**Comment by Cyp** [comment] 2019-03-07 18:29
Sharing animation data should be possible. See #340 for a partial solution which at least shares the sampler inputs/outputs.

**Comment by UX3D-schmithuesen** [comment] 2019-03-08 10:03
That looks pretty cool!

**Comment by julienduroure** [comment] 2019-09-04 21:37
Is there still an issue here, or can I close this ticket?

**Closed** 2019-09-26 15:57 UTC
Labels: Animation, enhancement, exporter
