### ISSUE TITLE
gltf,export_image_format="WEBP",

### ISSUE THREAD

**Issue by ShortVanco** [KhronosGroup/glTF-Blender-IO#2089] opened 2023-12-18 09:20 UTC
```
WebP: Unsupported bytes per pixel: 1 for file: 'C:\Users\ADMINI~1\AppData\Local\Temp\tmprc_uvdr3\img'
C:\Users\ADMINI~1\AppData\Local\Temp\tmprc_uvdr3\img: No error
Error: Could not write image: No error
Error: Image 'ac26d2aed7f64ad884a3c044f9ce1cf9.jpeg.001' could not be saved to 'C:\Users\ADMINI~1\AppData\Local\Temp\tmprc_uvdr3/img'
Traceback (most recent call last):
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\__init__.py", line 1125, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 49, in save
    json, buffer = __export(export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 66, in __export
    __gather_gltf(exporter, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 95, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 40, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 46, in wrapper_cached
    result = func(*args, **kwargs)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 94, in __gather_scene
    node = gltf2_blender_gather_nodes.gather_node(
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 44, in gather_node
    children=__gather_children(vnode, export_settings),
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 91, in __gather_children
    node = gather_node(c, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 44, in gather_node
    children=__gather_children(vnode, export_settings),
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 91, in __gather_children
    node = gather_node(c, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 44, in gather_node
    children=__gather_children(vnode, export_settings),
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 91, in __gather_children
    node = gather_node(c, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 44, in gather_node
    children=__gather_children(vnode, export_settings),
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 91, in __gather_children
    node = gather_node(c, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 44, in gather_node
    children=__gather_children(vnode, export_settings),
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 91, in __gather_children
    node = gather_node(c, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 48, in gather_node
    mesh=__gather_mesh(vnode, blender_object, export_settings),
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 310, in __gather_mesh
    result = gltf2_blender_gather_mesh.gather_mesh(blender_mesh,
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 46, in wrapper_cached
    result = func(*args, **kwargs)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_mesh.py", line 68, in gather_mesh
    primitives=__gather_primitives(blender_mesh, uuid_for_skined_data, vertex_groups, modifiers, materials, export_settings),
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_mesh.py", line 145, in __gather_primitives
    return gltf2_blender_gather_primitives.gather_primitives(blender_mesh,
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 46, in wrapper_cached
    result = func(*args, **kwargs)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_primitives.py", line 67, in gather_primitives
    blender_primitives, addional_materials_udim = __gather_cache_primitives(materials, blender_mesh, uuid_for_skined_data,
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 46, in wrapper_cached
    result = func(*args, **kwargs)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_primitives.py", line 134, in __gather_cache_primitives
    blender_primitives, additional_materials_udim, shared_attributes = gltf2_blender_gather_primitives_extract.extract_primitives(
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_primitives_extract.py", line 39, in extract_primitives
    primitive_creator.manage_material_info() # UVMap & Vertex Color
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_primitives_extract.py", line 405, in manage_material_info
    base_material, material_info = get_base_material(material_idx, self.materials, self.export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\material\gltf2_blender_gather_materials.py", line 549, in get_base_material
    material, material_info = gather_material(
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 46, in wrapper_cached
    result = func(*args, **kwargs)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\material\gltf2_blender_gather_materials.py", line 85, in gather_material
    extensions, uvmap_info_extensions, udim_info_extensions = __gather_extensions(blender_material, emissive_factor, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\material\gltf2_blender_gather_materials.py", line 259, in __gather_extensions
    specular_extension, uvmap_info, udim_info = export_specular(blender_material, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\material\extensions\gltf2_blender_gather_materials_specular.py", line 97, in export_specular
    specularcolor_texture, uvmap_info, udim_info, _ = gather_texture_info(
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\material\gltf2_blender_gather_texture_info.py", line 38, in gather_texture_info
    return __gather_texture_info_helper(primary_socket, blender_shader_sockets, 'DEFAULT', filter_type, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 46, in wrapper_cached
    result = func(*args, **kwargs)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\material\gltf2_blender_gather_texture_info.py", line 59, in __gather_texture_info_helper
    index, factor, udim_image = __gather_index(blender_shader_sockets, None, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\material\gltf2_blender_gather_texture_info.py", line 192, in __gather_index
    return gltf2_blender_gather_texture.gather_texture(blender_shader_sockets, use_tile, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 46, in wrapper_cached
    result = func(*args, **kwargs)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\material\gltf2_blender_gather_texture.py", line 46, in gather_texture
    source, webp_image, image_data, factor, udim_image = __gather_source(blender_shader_sockets, use_tile, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\material\gltf2_blender_gather_texture.py", line 210, in __gather_source
    source, image_data, factor, udim_image = gltf2_blender_gather_image.gather_image(blender_shader_sockets, use_tile, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 46, in wrapper_cached
    result = func(*args, **kwargs)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\material\gltf2_blender_gather_image.py", line 62, in gather_image
    buffer_view, factor_buffer_view = __gather_buffer_view(image_data, mime_type, name, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 46, in wrapper_cached
    result = func(*args, **kwargs)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\material\gltf2_blender_gather_image.py", line 117, in __gather_buffer_view
    data, factor = image_data.encode(mime_type, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\material\extensions\gltf2_blender_image.py", line 194, in encode
    return self.__encode_happy(export_settings), None
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\material\extensions\gltf2_blender_image.py", line 207, in __encode_happy
    return self.__encode_from_image(self.blender_image(export_settings), export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\material\extensions\gltf2_blender_image.py", line 300, in __encode_from_image
    return _encode_temp_image(tmp_image, self.file_format, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\material\extensions\gltf2_blender_image.py", line 331, in _encode_temp_image
    tmp_image.save(quality=export_settings['gltf_image_quality'])
RuntimeError: Error: Could not write image: No error
Error: Image 'ac26d2aed7f64ad884a3c044f9ce1cf9.jpeg.001' could not be saved to 'C:\Users\ADMINI~1\AppData\Local\Temp\tmprc_uvdr3/img'

Error: Python: Traceback (most recent call last):
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\material\extensions\gltf2_blender_image.py", line 300, in __encode_from_image
    return _encode_temp_image(tmp_image, self.file_format, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\material\extensions\gltf2_blender_image.py", line 331, in _encode_temp_image
    tmp_image.save(quality=export_settings['gltf_image_quality'])
RuntimeError: Error: Could not write image: No error
Error: Image 'ac26d2aed7f64ad884a3c044f9ce1cf9.jpeg.001' could not be saved to 'C:\Users\ADMINI~1\AppData\Local\Temp\tmprc_uvdr3/img'
Location: D:\blender4\4.0\python\lib\bpy\4.0\scripts\modules\bpy\ops.py:109
2023-12-18 17:13:43,921 - ERROR - [runConvert:909] - Error: Python: Traceback (most recent call last):
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\material\extensions\gltf2_blender_image.py", line 300, in __encode_from_image
    return _encode_temp_image(tmp_image, self.file_format, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\material\extensions\gltf2_blender_image.py", line 331, in _encode_temp_image
    tmp_image.save(quality=export_settings['gltf_image_quality'])
RuntimeError: Error: Could not write image: No error
Error: Image 'ac26d2aed7f64ad884a3c044f9ce1cf9.jpeg.001' could not be saved to 'C:\Users\ADMINI~1\AppData\Local\Temp\tmprc_uvdr3/img'
Location: D:\blender4\4.0\python\lib\bpy\4.0\scripts\modules\bpy\ops.py:109
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\osgjs_to_glb\osg_to_glb.py", line 890, in runConvert
    bpy.ops.export_scene.gltf(
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\material\extensions\gltf2_blender_image.py", line 300, in __encode_from_image
    return _encode_temp_image(tmp_image, self.file_format, export_settings)
  File "D:\blender4\4.0\python\lib\bpy\4.0\scripts\addons\io_scene_gltf2\blender\exp\material\extensions\gltf2_blender_image.py", line 331, in _encode_temp_image
    tmp_image.save(quality=export_settings['gltf_image_quality'])
RuntimeError: Error: Could not write image: No error
Error: Image 'ac26d2aed7f64ad884a3c044f9ce1cf9.jpeg.001' could not be saved to 'C:\Users\ADMINI~1\AppData\Local\Temp\tmprc_uvdr3/img'
Location: D:\blender4\4.0\python\lib\bpy\4.0\scripts\modules\bpy\ops.py:109

Error: Not freed memory blocks: 25668, total unfreed memory 8.559055 MB

```
- 
- I'm using the latest version but it still causes this problem
- 
- I think it's the problem here：
- 
```
# Happy path = we can just use an existing Blender image
        if self.__on_happy_path():
            # Store that this image is fully exported (used to export or not not used images)
            for fill in self.fills.values():
                export_settings['exported_images'][fill.image.name] = 1 # Fully used
                break
            return self.__encode_happy(export_settings), None

        if self.__on_happy_path_udim():
            return self.__encode_happy_tile(export_settings), None

        # Unhappy path = we need to create the image self.fills describes or self.stores describes
        if self.numpy_calc is None:
            return self.__encode_unhappy(export_settings), None
        else:
            pixels, width, height, factor = self.numpy_calc(self.stored, export_settings)
            return self.__encode_from_numpy_array(pixels, (width, height), export_settings), factor

    def __encode_happy(self, export_settings) -> bytes:
        return self.__encode_from_image(self.blender_image(export_settings), export_settings)
```
-

**Comment by julienduroure** [comment] 2023-12-18 09:33
Hello,
This is a duplicate of #2081 
WebP can't export B&W image.
Please follow #2081 for any update on the fix.

Closing as duplicate

**Closed by julienduroure** 2023-12-18 09:33 UTC
