### ISSUE TITLE
export gltf with camera and import it again, camera will split into Camera and Camera_Orientation

### ISSUE THREAD

**Issue by deepkolos** [KhronosGroup/glTF-Blender-IO#1487] opened 2021-11-06 08:14 UTC
**Describe the bug**
export gltf with camera and import it again, camera will split into Camera and Camera_Orientation

**To Reproduce**

0. export gltf with option include `Cameras`
1. and import the exported gltf to blender again
2. the camera will split into `Camera` and `Camera_Orientation`

**Expected behavior**
export gltf with camera and import it again, gltf's camera will keep original structure, no matter how many time to export then reimport

**Screenshots**

![图片](https://user-images.githubusercontent.com/12824616/140602828-0e24f9f2-9bf8-4e14-b110-eb6133c5e174.png)

![图片](https://user-images.githubusercontent.com/12824616/140602857-25eff8d6-95f0-479b-a5bf-8c832a879e0a.png)

**Version**
 - OS: Window 10
 - Blender Version 2.93.5

**Comment by julienduroure** [comment] 2021-11-06 08:33
Hello,
This is a duplicate of #1328 
This will be fixed by #1378

**Closed** 2021-11-06 08:34 UTC
Labels: duplicate
