### ISSUE TITLE
Support POINT and LINE primitives

### ISSUE THREAD

**Issue by Dok11** [KhronosGroup/glTF-Blender-IO#376] opened 2019-03-21 16:14 UTC
Mesh with verts, edges and without faces doesnt save geometry in exported files

![image](https://user-images.githubusercontent.com/2697890/54766882-23c66080-4c0d-11e9-8559-083e17c0d779.png)

[gltf.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2992925/gltf.zip)

**Comment by emackey** [comment] 2019-03-21 19:23
Currently this project will only export `TRIANGLES`, not `LINES` or `POINTS` in glTF format, so this is expected behavior.

**Comment by Dok11** [comment] 2019-03-22 10:41
"project" — you mean this addon or blend-file?

**Comment by emackey** [comment] 2019-03-22 14:18
Sorry, this addon.  It doesn't look like we have a feature request open to support lines & points.  They're not very common in the glTF ecosystem, most renderers are focused on triangles.

**Comment by emackey** [comment] 2019-03-22 14:20
But is that what you're asking for?  What are you trying to get from this, just preserve exact edges, or render some lines?

**Comment by Dok11** [comment] 2019-03-22 14:25
@emackey if you interest my case:
In Blender we pain spline what will be as path to movement camera, then we convert spline to mesh (vertexes like in my screenshot) and export to gltf. Then we inport scene into threejs and try attach camera to camera path, but as you now leaned it is impossible — file doesnt have required data.

**Comment by Dok11** [comment] 2019-03-22 14:29
Maybe you can prompt what place in export script may realizes this logic?
I think around this place https://github.com/KhronosGroup/glTF-Blender-IO/blob/master/addons/io_scene_gltf2/blender/exp/gltf2_blender_extract.py#L521

**Comment by Dok11** [comment] 2019-04-16 14:31
@emackey how you think, what chance what this feature request will be approved?

**Comment by emackey** [comment] 2019-04-16 14:41
We're always eager to receive contributions from the community.  In this case though, exporting geometry without faces seems the wrong way to store the information in glTF.  Perhaps it would be better to assign a Blender camera to follow the path, and bake the animation to glTF?  I'm not a ThreeJS expert so I don't know if that would translate well to that library, but, I would imagine an animated camera node could be cleanly stored in the glTF format.

**Comment by donmccurdy** [comment] 2019-04-16 17:18
Merging some details from https://github.com/KhronosGroup/glTF-Blender-IO/issues/352 –

***

PRs for point and line support would be welcome. See:

- KhronosGroup/glTF-Blender-Exporter#50
- https://twitter.com/donrmccurdy/status/1104439928660746240

**Comment by nasser** [comment] 2019-07-16 11:24
@donmccurdy that tweet is a response to me! hello :wave: 

I am working on a PR for this, because my workflow depends on it. I have a patch against the latest 2.8 RC to add line export that seems to do the trick, though I am unsure about some of the technical details, specifically around mesh splitting (which other parts of the addon seem to do) and the like. I will not have a chance to organize this into a PR until later in August, but [here's the diff](https://gist.github.com/nasser/2d391ef90c6f8287f8b7c6c43e218e4b) against the addon that shipped with the RC.

How does that look? I am very open to feedback and guidance on getting this issue landed. Specifically I don't know
* About mesh splitting or other technical constraints of the glTF format that we'd need to make this work at scale
* The relationship between this repo and the addon that ships with 2.8

Thanks in advance for any help, and thank you to everyone involved for this addon. It has really transformed my workflow for the better :pray:

**Comment by donmccurdy** [comment] 2019-07-21 05:22
Thanks @nasser! The PR looks very promising. Some initial thoughts:

The exporter applies mesh splitting when (a) a mesh contains multiple materials, or (b) a mesh has too many triangles for the GPU to render it as a single primitive. The first would ideally be handled when exporting lines or points, although I think we could merge a PR without that if it doesn't break any existing functionality. The latter is not necessary here.

If I'm reading your PR correctly, a LINES primitive is created if at least one edge exists in the mesh that is not part of a triangle. Extending this to POINTS would mean that extraneous points also add a primitive. While it's certainly the most complete representation of what's in Blender, I wonder if this makes sense for the real workflows, or if it will just add unwanted draw calls for vertices that are left accidentally? An alternative would be to select a single draw mode for the entire mesh. TRIANGLES would be used if _any_ triangles exist, in which case detached lines and points are ignored. LINES would be used if _no_ triangles and _any_ lines exist, and so on. I think I prefer the simplicity of that approach. While glTF allows multiple primitive types in a single mesh, I'm not sure it's a practice I would want to promote without need. /cc @emackey 

> The relationship between this repo and the addon that ships with 2.8

This repository is merged into the Blender 2.8 codebase regularly, and a PR here will eventually make its way into Blender 2.8. 🙂

**Comment by nasser** [comment] 2019-08-20 22:20
> The exporter applies mesh splitting when (a) a mesh contains multiple materials, or (b) a mesh has too many triangles for the GPU to render it as a single primitive. The first would ideally be handled when exporting lines or points, although I think we could merge a PR without that if it doesn't break any existing functionality. The latter is not necessary here.

Interesting -- is there not a similar GPU limit for lines and points?

> If I'm reading your PR correctly, a LINES primitive is created if at least one edge exists in the mesh that is not part of a triangle. Extending this to POINTS would mean that extraneous points also add a primitive. While it's certainly the most complete representation of what's in Blender, I wonder if this makes sense for the real workflows,

I will be the first to admit that my usecase is esoteric, but I *have* had a need for exporting mixed triangle and line meshes, as in this model of a biplane in a game I recently wrapped up: https://twitter.com/ra/status/1152616341674831873

![](https://pbs.twimg.com/media/D_7qczFXsAEjqyz?format=png&name=small)
![](https://pbs.twimg.com/media/D_7qczOWsAA8d3Z?format=png&name=small)

That said, blender does not expose a lot in the way of associating UV coordinates or vertex colors to individual vertices outside of a face, so in practice I do end up separating the lines out. I think that's a separate issue, though. 

> or if it will just add unwanted draw calls for vertices that are left accidentally? An alternative would be to select a single draw mode for the entire mesh. TRIANGLES would be used if _any_ triangles exist, in which case detached lines and points are ignored. LINES would be used if _no_ triangles and _any_ lines exist, and so on. I think I prefer the simplicity of that approach. While glTF allows multiple primitive types in a single mesh, I'm not sure it's a practice I would want to promote without need. /cc @emackey

Are extraneous lines and points really such an issue that one would expect their exporter to clean them up for them? You could do that in Blender yourself, I would imagine?

Maybe a compromise could be an additional exporter option to enable line and point primitive export, with the default being the functionality you describe. How does that sound?

> > The relationship between this repo and the addon that ships with 2.8
> 
> This repository is merged into the Blender 2.8 codebase regularly, and a PR here will eventually make its way into Blender 2.8.

Gotcha. I am starting working on a proper PR now.

**Comment by emackey** [comment] 2019-08-21 14:55
@donmccurdy I think the `Meshes` or `Objects` UI tab could get a new option for "Allow LINES and POINTS", with the default being to not export them (for the common case of loose edges & points in complex meshes).

**Comment by donmccurdy** [comment] 2019-08-21 17:47
> Interesting -- is there not a similar GPU limit for lines and points?

See [this discussion](https://stackoverflow.com/questions/4998278/is-there-a-limit-of-vertices-in-webgl). The limits I'm aware of are related to indices, and not the number of vertices, so primitive types like LINES or POINTS (which aren't indexed) would not need to worry about the bounds of 16- or 32-bit indices.

> I will be the first to admit that my usecase is esoteric, but I have had a need for exporting mixed triangle and line meshes, as in this model of a biplane in a game I recently wrapped up...

I love seeing stylized uses of glTF like this, really nice work! 🙂

> Are extraneous lines and points really such an issue that one would expect their exporter to clean them up for them? 

I'm not sure. Somewhat related, users complain if this exporter reorders their vertices during export, which isn't always avoidable, but if we applied that requirement to mixed-type geometry, we might end up with `[1 point, 1 mesh, 3 points, 1 mesh, 2 points, ...]` and a user could easily have 50 unwanted drawcalls in their model, just because they didn't know to clean up loose edges and points. This would be hard for users to diagnose.

> I think the Meshes or Objects UI tab could get a new option for "Allow LINES and POINTS", with the default being to not export them

Ok, I like this idea – with lines and points omitted from the export by default. It sounds simpler to implement than a whole second mode for my suggestion above. The FBX exporter has a similar checkbox, *Loose Edges*, so I would suggest *Loose Edges and Vertices* for consistency.

**Comment by lexaknyazev** [comment] 2019-08-21 17:51
> The limits I'm aware of are related to indices, and not the number of vertices, so primitive types like LINES or POINTS (which aren't indexed) would not need to worry about the bounds of 16- or 32-bit indices.

Lines and points can use indexed draw calls (although there's no reason to use them for the latter).

**Comment by nasser** [comment] 2019-08-21 18:44
> Ok, I like this idea – with lines and points omitted from the export by default. It sounds simpler to implement than a whole second mode for my suggestion above. The FBX exporter has a similar checkbox, _Loose Edges_, so I would suggest _Loose Edges and Vertices_ for consistency.

I like it! I will give it a shot!

**Closed** 2021-02-24 05:15 UTC
Labels: Mesh_&_Object, enhancement, exporter
