### ISSUE TITLE
Exporting NLA composition doesn't work correctly

### ISSUE THREAD

**Issue by jjcasmar** [KhronosGroup/glTF-Blender-IO#1337] opened 2021-02-25 12:56 UTC
I am testing the NLA to group animation tracks, but its not working as expected.

I have done three cases:
Two actions in the same NLA track
![image](https://user-images.githubusercontent.com/2644001/109155661-1f4b4080-7770-11eb-82d2-6811abe8bcf8.png)

In this case, the exporter doesn't generate any animation

Two actions in different tracks with different name:
![image](https://user-images.githubusercontent.com/2644001/109155783-47d33a80-7770-11eb-8b5e-d3f82bfc6b25.png)

In this case, I get two different animations in glTF. One containing the CubeAction and Cube.001.Action and another one containing the CubeAction.002. As expected

Two actions in different tracks with same name:
![image](https://user-images.githubusercontent.com/2644001/109155914-77824280-7770-11eb-89b7-3a9d662b3fc2.png)

In this case, I get one single animation and everything is correct

Two actions in different tracks with same name but starting at different time:
![image](https://user-images.githubusercontent.com/2644001/109156216-df388d80-7770-11eb-82e9-f484ebb900be.png)

In this case, I get one single animation in glTF, but both start at the same time. 

I would expect the exoprter respect what is defined in the NLA. Maybe we could add a "use_nla_composition" option to the exporter, and if that is on, export the animations taking into account the delays that are defined in the NLA. 

Otherwise, when you have hundreds of animations that must be synchronized, its a huge task to synchronize them in the glTF player.

**Comment by donmccurdy** [comment] 2021-02-25 18:04
More discussion in https://github.com/KhronosGroup/glTF-Blender-IO/issues/763. I think we agree that NLA composition should be exported — I don't even think it needs an option but should be done by default. The problem is that this is not trivial to do, see discussion in that thread.

**Comment by Blackclaws** [comment] 2022-04-27 14:13
I think the approach that was discussed in #763, namely baking the animation is probably the right one here as well. Another quick workaround might be to just increase the length of the Cube.001Action by padding it infront with a null action (same pose as at the start but just a keyframe thats way sooner).

**Comment by julienduroure** [comment] 2023-02-26 10:13
Hello,
This is now fixed in current main branch, after animation refactor 64e3532f48ebdf878a1c9b81ade6d1a19c8ff890

You now have an "NLA Tracks" option at export, to export tracks instead of actions.

**Closed by julienduroure** 2023-02-26 10:13 UTC
Labels: duplicate, enhancement, exporter, Animation
