### ISSUE TITLE
Export: extra node added to cameras

### ISSUE THREAD

**Issue by Alexeyt89** [KhronosGroup/glTF-Blender-IO#1370] opened 2021-04-10 21:35 UTC
There are two interrelated problems.
1) I add a camera to the sceen, add rotation animation to it and export it to glTF file.
On exporting a new node is added. The animation is taken from the camera node and moved to the new node. Then the camera is added to this node. So the animation is not applied to the camera anymore, but to the unexpectedly added parent node.
![structure](https://user-images.githubusercontent.com/16538686/114284880-a708b800-9a5b-11eb-8f86-ba4594fca23b.png)
2) On reexporting the model to glTF each time a new dummy node is added, which makes it difficult to programmatically match animations to the cameras.
![camera](https://user-images.githubusercontent.com/16538686/114284926-08308b80-9a5c-11eb-9e40-bc4fef611828.png)

Suggestion - don't create extra node but connect animation directly to the camera node:

`            "channels" : [
                {
                    "sampler" : 0,
                    "target" : {
                        "node" : 0, // for camera animations this should point to the node with "camera" != -1
                        "path" : "translation"
                    }
                }
            ],`

**Comment by scurest** [comment] 2021-04-10 22:58
#1328

**Comment by julienduroure** [comment] 2021-04-11 09:01
As spotted by scurest, this is a duplicate of an already existing ticket.
Closing this one

**Closed by julienduroure** 2021-04-11 09:01 UTC
Labels: duplicate
