### ISSUE TITLE
Importer leaves color space for non-color textures as sRGB

### ISSUE THREAD

**Issue by DataBeaver** [KhronosGroup/glTF-Blender-IO#1584] opened 2022-03-05 09:45 UTC
**Describe the bug**
When importing glTF files, the colorspace on created images is left as sRGB (the default).  However the glTF spec says that only base color and emissive textures should be sRGB.  This can be observed to have a visual impact in Blender when toggling the colorspace of such an image between sRGB and linear.

**To Reproduce**
1. Obtain and import a glTF model
2. Go to shader nodes (the shading tab in the default Blender workspace works well for this)
3. Observe colorspace in metallic/roughness and normalmap textures being set to sRGB
4. Toggle colorspace to Linear
5. Observe visual appearance of the objects changing

**Expected behavior**
Colorspace of non-color texture should be set to linear for correct visual results.

**.blend file/ .gltf**
Example glTF file: https://sketchfab.com/3d-models/oak-tree-variations-with-low-poly-variants-a4c05606689d47b9b9ca56d563b27998

**Version**
 - OS: Linux
 - Blender Version: 3.0.1+dfsg-7

**Additional context**
My primary use case is exporting the data to my own engine using my own exporter, so I can ignore the incorrect colorspaces easily enough, but it would be nice if it was correct to begin with.

**Comment by julienduroure** [comment] 2022-03-05 11:20
Hello,
What material are you talking about in your tree files?
Example: Tree_0Mat_2, BaseColor is sRGB, and normal and metallic/roughness is set as Non-Color

So I can't reproduce for now, I can't find where normal and metallic/roughness are set to sRGB

**Comment by DataBeaver** [comment] 2022-03-05 11:32
Here's the shader graph I'm getting for Tree0_Mat0 (all of the materials seem to have the same settings):
![image](https://user-images.githubusercontent.com/1126732/156881000-442d9706-cf41-4822-91ff-6e1ec899d477.png)

And a .blend file where I've imported the glTF:
[oaks.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/8190546/oaks.zip)

I also verified that sketchfab still offers the same file I have, which has an sha1sum of e20ee5337ff5d6888ae5b312f626568aac4eccfc.

The files in /usr/share/blender/scripts/addons/io_scene_gltf2 identify themselves as being version 1.7.33 of the plugin.  It seems to be a few months old, so I'll try with the latest version to see if it's different.

**Comment by DataBeaver** [comment] 2022-03-05 11:43
Nope, still getting sRGB colorspace with the git version of the importer (it did warn about compatibility since the plugin is annotated for Blender 3.1, but there's no obvious errors about missing attributes or such).

**Comment by julienduroure** [comment] 2022-03-05 13:08
Can you please try with a more recent version of Blender itself?
I still can't reproduce. I tested with 3.1 RC from today ( https://builder.blender.org/download/daily/ ), and still have Non-color

**Comment by DataBeaver** [comment] 2022-03-05 13:30
Okay, looks like this is probably an issue in Debian's packaging of Blender.  They're having issues with a new version of opencolorio, and without that Blender is lacking most of its colorspace settings, including non-color.  I'll take it up with the Debian maintainers.

**Comment by julienduroure** [comment] 2022-03-05 14:16
Closing this ticket, issue is not linked to this addon

**Closed by julienduroure** 2022-03-05 14:16 UTC
Labels: question
