### ISSUE TITLE
"Apply modifiers" option does nothing

### ISSUE THREAD

**Issue by iirelu** [KhronosGroup/glTF-Blender-IO#546] opened 2019-06-13 11:55 UTC
When exporting meshes with modifiers, the "Apply modifiers" option doesn't actually apply any modifiers. The original mesh is the only thing exported.

Reproduce by putting a bevel modifier on a cube and exporting to glb/gltf with "Apply modifiers" on. The resulting gltf file has the cube's original geometry instead of the modified geometry.

Blender 2.80.190609.030c7df19da9-1, glTF exporter 0.9.24

**Comment by julienduroure** [comment] 2019-06-13 12:17
Hello,
Thanks for reporting. 
This is a know issue, duplicate of first part of #525 , and #536

**Comment by julienduroure** [comment] 2019-06-13 21:45
Fixed by #547

**Closed by julienduroure** 2019-06-13 21:45 UTC
Labels: duplicate, exporter
