### ISSUE TITLE
Incorrect armature structure on import

### ISSUE THREAD

**Issue by NotNite** [KhronosGroup/glTF-Blender-IO#1893] opened 2023-04-03 23:32 UTC
Heya,

Me and a few friends have been working on [a tool to export models from the game FINAL FANTASY XIV](https://github.com/xivdev/Xande), written in C# using [SharpGLTF](https://github.com/vpenades/SharpGLTF). I came across an issue that I originally thought was a SharpGLTF bug, but after trying with several other glTF importers online and the Godot Engine, I think(?) this is a bug in Blender importing glTF files. I'm using Blender 3.5.0, addon 3.5.30, Windows 10 22H2 (19045).

For reference, we're trying to build a custom exporter for glTF compared to the game community's current FBX exporter.

---

SharpGLTF's API for adding a skinned mesh is `AddSkinnedMesh(MESHBUILDER mesh, Matrix4x4 meshWorldMatrix, params NodeBuilder[] joints)` - our old approach (on the `model-export` branch of our repository) was to pass *every single bone* into the `joints` parameter.

This resulted in 100+ vertex groups on every single mesh when only a few were being used (left: reference model, right: our model):

![](https://namazu.photos/i/idpx7ak6.png)

I refactored the code (on the `model-export-but-broken` branch) to only pass the bones that get used to `AddSkinnedMesh` (while still keeping the entire skeleton node inside of the scene). However, that turned this (`model-export`):

![](https://namazu.photos/i/byxq1pe6.png)

into this (`model-export-but-broken`):

![](https://namazu.photos/i/ngfduho2.png)

It seems that Blender is now unable to detect that `n_root` is the actual root of the skeleton. Furthermore, some bones (`j_mune_l`, for example) aren't even in the skeleton at all - just loose objects.

Trying with the Godot Engine model import correctly detects the `n_root` bone as the root, and you can notice `j_mune_l` is where it is supposed to be:

![](https://namazu.photos/i/r43kgpk0.png)

---

Some resources:

- [Previous iteration model code](https://github.com/xivdev/Xande/blob/model-export/Xande/ModelConverter.cs) (works, but specifies 100+ vertex groups on each model)
- [Current iteration model code](https://github.com/xivdev/Xande/blob/model-export-but-broken/Xande/ModelConverter.cs) (does not work)
- [Previous iteration exported model](https://cdn.discordapp.com/attachments/884364510964621353/1092486898523570246/model-2023-04-03-12-32-36.7z) (working; 7z archive - contains .gltf, .glb, and .obj)
- [Current iteration exported model](https://cdn.discordapp.com/attachments/884364510964621353/1092583034378797089/model-2023-04-03-18-54-26.7z) (broken; 7z archive - contains .gltf, .glb, and .obj)
- [Reference exported model](https://cdn.discordapp.com/attachments/884364510964621353/1091775933129703494/c0101e0000_top.fbx) - (exported from [TexTools](https://github.com/TexTools/FFXIV_TexTools_UI); .fbx - only contains body)

**Comment by julienduroure** [comment] 2023-04-05 16:30
Hello,
During import:
- joints (that are in joints list) will be created as bones.
- nodes that are descendants and ancestors of joints (that are in joints list) will be created as bones. (https://github.com/KhronosGroup/glTF-Blender-IO/blob/c9f638d75358ce00231860e4ff2a10810c8d9bf4/addons/io_scene_gltf2/blender/imp/gltf2_blender_vnode.py#L151)

But in your case, some descendants of joints, that are not in joints list, and are not meshed, are created as empties.
I am not sure we can be sure that these nodes should be created as bone or as empties.

One solution should be to mask as bones any descendants of bones until finding a node that is not "empty" (mesh or lamp, camera, etc...). Not sure this is what we want. 
The best way to be sure to create these nodes as bones is to add them to the joint list (this is the aims of this list). 
What is the purpose to be sure they are bones? (as they don't have any weights assigned, as they are not in join list) ?

@scurest any thoughts?



(In 3.5, I am not able to reproduce your issue about n_root, that is created as bone)

![image](https://user-images.githubusercontent.com/1696020/230144909-77ae1a93-0e67-476a-932a-c8549c64d880.png)

**Comment by NotNite** [comment] 2023-04-06 01:37
> What is the purpose to be sure they are bones? (as they don't have any weights assigned, as they are not in join list) ?

As this is a tool primarily intended for modders of the game, we plan to also get importing glTF->proprietary model format to work, and it would be much harder to build with an incorrect armature.

**Comment by julienduroure** [comment] 2023-06-17 06:17
Hello,

Let's close this ticket, as we currently set as bone cases where we are sure that nodes are bones. 
Any other case are cases where we can't be sure if we need bone or empty, depending on user workflow.

**Closed by julienduroure** 2023-06-17 06:17 UTC
Labels: question
