### ISSUE TITLE
Support new Emission Strength on Principled BSDF

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Blender-IO#1216] opened 2020-09-17 18:37 UTC
A new Emission Strength input was added to the Principled BSDF node in [D4971](https://developer.blender.org/D4971).

Emission strength from the original Emission BSDF node was added in #1159.  It should be updated to include the new strength input as well.

**Comment by emackey** [comment] 2020-09-17 18:41
Ah, correction: #1159 already [includes code to look for emission strength](https://github.com/KhronosGroup/glTF-Blender-IO/pull/1159#discussion_r464088810) on Principled BSDF.  We should add test(s) for this once we get a daily build with the new input added.

**Comment by julienduroure** [comment] 2020-09-17 19:17
So, seems exporter already manage it. 
Importer still need to be updated?

**Comment by scurest** [comment] 2020-09-18 02:58
Emission Strength is in the latest build. I can confirm exporting works.

The importer can use the strenght socket for grayscale emissiveFactors at least.

**Comment by astrand130** [comment] 2020-09-18 10:25
Hi! Author of the Emission Strength Socket patch.

https://developer.blender.org/D8777 is needed to access the socket via python using the Principled BSDF wrangler. It is in review but the API should remain the same.

You can find the WIP updated OBJ importer here which contains code to handle importing/exporting emission strength by doing a sort of RGBM encoding/decoding. https://developer.blender.org/D8868

Thanks

**Comment by julienduroure** [comment] 2020-09-18 13:41
Hello @astrand130 , current implementation of glTF is not using node_shader_utils wrangler.

Exporting is already manage since yesterday, and importer will be via #1217

**Comment by julienduroure** [comment] 2020-09-23 06:04
Import part is now merge. Closing

**Closed by julienduroure** 2020-09-23 06:04 UTC
Labels: Material, enhancement, exporter, importer
