### ISSUE TITLE
Export with Rigging: 'NoneType' object has no attribute 'matrix_world'

### ISSUE THREAD

**Issue by simongloor** [KhronosGroup/glTF-Blender-IO#910] opened 2020-02-03 06:33 UTC
**Describe the bug**
When I try to export my object, it throws this error call-stack:
```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\io_scene_gltf2\__init__.py", line 420, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 40, in save
    json, buffer = __export(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 54, in __export
    __gather_gltf(exporter, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 69, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 36, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather.py", line 55, in __gather_scene
    node = gltf2_blender_gather_nodes.gather_node(blender_object, blender_scene, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 45, in gather_node
    node = __gather_node(blender_object, blender_scene, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 63, in __gather_node
    mesh=__gather_mesh(blender_object, export_settings),
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_nodes.py", line 297, in __gather_mesh
    export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_mesh.py", line 41, in gather_mesh
    primitives=__gather_primitives(blender_mesh, blender_object, vertex_groups, modifiers, material_names, export_settings),
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_mesh.py", line 117, in __gather_primitives
    export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_primitives.py", line 50, in gather_primitives
    vertex_groups, modifiers, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_primitives.py", line 94, in __gather_cache_primitives
    None, blender_mesh, blender_object, vertex_groups, modifiers, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_extract.py", line 636, in extract_primitives
    v = convert_swizzle_location(vertex.co, armature, blender_object, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_extract.py", line 94, in convert_swizzle_location
    apply_matrix = armature.matrix_world.inverted() @ blender_object.matrix_world
AttributeError: 'NoneType' object has no attribute 'matrix_world'

location: <unknown location>:-1
```

**To Reproduce**
1. Open my .blend wit Blender v2.81a
1. Select the hat
1. Export selected with animations and sampiling as gltf + bin + textures

**Expected behavior**
Successful export

**.blend file/ .gltf**
[BugReport_HatAnimExport.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4146537/BugReport_HatAnimExport.zip)

**Version**
 - Windows 10
 - Blender v2.81a

**Additional context**
The armature was simplified to allow for easier debugging. I can upload the full model if desired. Also the model was initially created in older Blender versions but hasn't ever failed to export as fbx.

**Comment by julienduroure** [comment] 2020-02-03 08:45
Root cause : You unchecked "skinning" checkbox at export. 
Because skinning mesh are exported in armature space, this cause error, because armature is not pass in function
I will add a check to avoid the traceback

**Comment by simongloor** [comment] 2020-02-03 16:29
Awesome! That solves my problem.  
From the UX perspective, I was not used to being able/required to de-/activate the skinning export.

**Comment by julienduroure** [comment] 2020-02-05 08:28
Seems to be a duplicate of #789
So closing this ticket, #789 will remain the main ticket for this problem

**Closed by julienduroure** 2020-02-05 08:28 UTC
