### ISSUE TITLE
There is no draco compression option in the exporter of blender 4.3.

### ISSUE THREAD

**Issue by chen649285912** [KhronosGroup/glTF-Blender-IO#2408] opened 2024-11-21 08:05 UTC
There is no draco compression option in the exporter of blender4.3（released）, and there is no draco compression effect after testing the export

![微信截图_20241121160213](https://github.com/user-attachments/assets/7dbc1ba2-0dee-4948-9968-af81eeb5395b)

This is the exported test file
[test.zip](https://github.com/user-attachments/files/17842000/test.zip)

**Comment by julienduroure** [comment] 2024-11-21 08:11
Hello,
I supposed that you are using Windows OS?
(Note that all requirement information needed in the issue template are useful :) )

This is a know issue on Blender side, that should be solved soon (and will be maybe part of a 4.3.1 release)
See https://projects.blender.org/blender/blender/issues/130545

Closing this ticket, avoiding following multiple duplicate ticket for the same root cause.

Feel free to comment again if you are not on Windows

**Closed by julienduroure** 2024-11-21 08:11 UTC

**Comment by chen649285912** [comment] 2024-11-21 08:25
Yes, I am using Windows, thanks, I will check out the blender update
