### ISSUE TITLE
Blender 2.81 doesn't initialize imported images

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF-Blender-IO#674] opened 2019-09-13 19:29 UTC
In Blender 2.80, delete the cube and import [tests/roundtrip/01_textured_sphere](https://github.com/KhronosGroup/glTF-Blender-IO/tree/master/tests/roundtrip/01_textured_sphere).  Go to the `Shading` tab on the UI.  This is the expected result:

![ImportBlender280](https://user-images.githubusercontent.com/1235080/64889137-ab2fe200-d63a-11e9-8ffe-901e8831bf9b.png)

But in Blender 2.81 experimental (today's build), the same actions result in this:

![ImportBlender281](https://user-images.githubusercontent.com/1235080/64889181-c1d63900-d63a-11e9-882d-ac8578fa6208.png)

What's happened is that the images are 'temporarily' blank, all zeros.  They don't show in the LookDev preview, and they don't export (and hence fail the roundtrip tests).

BUT, if the user goes and views the images, by selecting them from the image dropdown in the lower-left sub-window shown here, the images will populate, one at a time, as they are selected by the user.  This causes the LookDev window to update to the correct results once all three images have been visited, and the glTF export works correctly after that as well.

This happens with or without "Pack Images" during import.  It may be a Blender bug, or some new behavior is needed from the importer, I'm not sure.

/cc @julienduroure We should get to the bottom of this before 2.81.

**Comment by julienduroure** [comment] 2019-09-13 20:48
I commited a workaround and create a new task on 2.81 release task #645 

This seems to be a regression in Blender. I created a bug report here: https://developer.blender.org/T69857

I propose to close this report, because there is no more issue here

**Closed by julienduroure** 2019-09-13 20:48 UTC
Labels: importer

**Comment by emackey** [comment] 2019-09-13 20:53
I've confirmed that this bug affects the OBJ importer the same way.  Looks like a Blender 2.81 issue.

**Comment by emackey** [comment] 2019-09-13 20:57
@julienduroure Awesome.  Also, tests are passing again with your workaround.

**Comment by julienduroure** [comment] 2019-09-13 21:38
OK ... Blender bug is already solved.
I will wait that next build is ready to remove my workaround, in order to keep passing tests
