### ISSUE TITLE
Some meshes are corrupted if exported as part of a complex scene

### ISSUE THREAD

**Issue by Silverlan** [KhronosGroup/glTF-Blender-IO#1291] opened 2020-12-07 14:36 UTC
**Describe the bug**
When exporting a complex scene, some of the objects/meshes in the scene may become corrupted when the scene is re-imported.

**To Reproduce**
1. Download Blender 2.91.0 (Steam version)
2. Install version 1.5.8 of glTF-Blender-IO
3. Download the Class room demo project: https://download.blender.org/demo/test/classroom.zip
4. Open the project in Blender
5. Remove all scenes from the project except for "_mainScene" (to prevent #639)
6. Export as glb with the default export settings
7. Open a new empty project and import the glb file

**Expected behavior**
The scene should have been the same after the import, however some of the meshes are corrupted (primarily the chairs).
This is the original scene: https://pragma-engine.com/share/blender_2020-12-07_15-15-26.png
This is the scene after importing the glb file: https://pragma-engine.com/share/blender_2020-12-07_15-16-14.png
The legs of the chairs have turned into circles.

**However**, if you remove all of the objects in the original project **except** for some of the chairs, then export the scene as glb and re-import it, the chairs will be correct:
https://pragma-engine.com/share/blender_2020-12-07_15-15-14.png
https://pragma-engine.com/share/blender_2020-12-07_15-33-16.png

**.blend file/ .gltf**
Class room demo: https://download.blender.org/demo/test/classroom.zip
Class room demo with just the chairs (does not include assets, i.e. above file is also required): https://pragma-engine.com/share/classroom_chairs.blend

**Version**
- OS: Windows 10 x64
- Blender Version 2.91.0
- glTF-Blender-IO version: 1.5.8

**Comment by julienduroure** [comment] 2020-12-07 18:28
Confirmed.
Need more investigation, but maybe a duplicate of #1049

**Comment by julienduroure** [comment] 2021-07-04 19:59
Seems to be fixed by #1378

**Comment by julienduroure** [comment] 2022-03-02 20:44
Fixed by 69746b2b31eeee080d5dfd3c74f1e02742795ed2

**Closed by julienduroure** 2022-03-02 20:44 UTC
Labels: bug, exporter, Mesh_&_Object
