### ISSUE TITLE
Error when exporting with linked scenes

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-IO#1236] opened 2020-10-13 17:23 UTC
_Originally posted by @Taroslord in https://github.com/KhronosGroup/glTF-Blender-IO/issue_comments/707860938_

I've reproduced my scene to an neutral example, where the problem appears. See my .blend file below to reproduce the problem.

**Read this first:**
The example model is animated and has two parent empties, like in my original scene.
There is a second scene created. It is called _Scene_Linked_. The content is linked with the scene called: _Scene_.

**How to reproduce the bug:**
1. Select the "root_Torus" and its child objects in the outliner window. (Select Hierarchy)
2. Export to .glb
-> Error appears. Export impossible.

**To avoid the bug:**
1. Delete "Scene_Linked" completely.
2. Select the "root_Torus" and its child objects in the outliner window. (Select Hierarchy)
3. Export to .glb
-> All works.

**What I expect:**
I want to use linked scenes in my Blend files and keep the ability to export my object hierarchies to _.glb_ files, even if they are linked within other scenes.

Thank you for your time.

[cw_LinkedScene_ExportBug.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5372674/cw_LinkedScene_ExportBug.zip)

**Comment by julienduroure** [comment] 2020-10-13 17:45
Hello,
@Taroslord : Seems you uploaded a glb file, not a .blend file

**Comment by Taroslord** [comment] 2020-10-13 18:18
> Hello,
> @Taroslord : Seems you uploaded a glb file, not a .blend file

Sorry! My attached ZIP is updated.

[cw_LinkedScene_ExportBug.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5373302/cw_LinkedScene_ExportBug.zip)

**Comment by julienduroure** [comment] 2020-10-13 20:10
This is a duplicate of #639 

This is not "linked" to linked scene, you can reproduce when an **animated** object is instanced in 2 different scene.
Linked to the way actions are converted into glTF animations at end of each scene export.

**Comment by Taroslord** [comment] 2020-10-14 06:36
> This is a duplicate of #639
> 
> This is not "linked" to linked scene, you can reproduce when an **animated** object is instanced in 2 different scene.
> Linked to the way actions are converted into glTF animations at end of each scene export.

Thank you. But it seem not be fixed. OK. I'll post my upcoming comments for this issue into #639.

**Comment by julienduroure** [comment] 2021-07-04 19:52
Seems to be fixed by #1378

**Comment by julienduroure** [comment] 2022-03-02 20:46
Fixed by 69746b2b31eeee080d5dfd3c74f1e02742795ed2

**Closed by julienduroure** 2022-03-02 20:46 UTC
Labels: bug, duplicate, exporter, Animation
