### ISSUE TITLE
Wrong scaling in animation/armature export

### ISSUE THREAD

**Issue by youaresoomean** [KhronosGroup/glTF-Blender-IO#828] opened 2019-12-12 06:33 UTC
**Describe the bug**
When importing a .fbx Model from Adobe's mixamo and then exporting it to GLTF, the scale of the model is wrong. In Blender **2.80** the scale was **correct**.

The armature has a scale factor of 0.01 apply to it when importing from .fbx. This might cause the scaling issue in 2.81.

**To Reproduce**
1. Import ybot@idle.fbx via Import > FBX in Blender **2.81** (default settings)
2. Click on Export > GLTF (default settings, output to .gltf + bin.. but doesnt matter, also happens with .glb)
3. View resulting .gltf -> scale is wrong

**Expected behavior**
Correct scale, same as in 2.80.

**.blend file/ .gltf**
The ybot from mixamo is in the attached zip file. It contains the .fbx downloaded from mixamo, the .blend file and the resulting .gltf. 
[gltf_armature_scale_issue.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3954159/gltf_armature_scale_issue.zip)

**Version**
 - OS:  Windows 10 (1909)
 - Blender Version 2.81

**Comment by julienduroure** [comment] 2019-12-12 06:46
Hello,
This is a duplicate of #783 
You can find a workaround on #783 comments before the bug/enhancement is fixed

**Comment by julienduroure** [comment] 2019-12-20 09:55
(Closing, as #783 will remain open until this is fixed)

**Comment by julienduroure** [comment] 2020-01-08 14:50
Was investigating this issue, and have some question:
What viewer are you using to check the scale issue ?

Because I found some weird stuff:

(tested with Blender 2.82 alpha)
Exporting ybot file and viewing in https://gltf-viewer.donmccurdy.com/ : Scale seems to be very big.

![image](https://user-images.githubusercontent.com/1696020/71986630-14141900-322d-11ea-912f-6c453b2356d9.png)

Exporting ybot file and viewing in https://sandbox.babylonjs.com/ : Scale seems to be OK.
![image](https://user-images.githubusercontent.com/1696020/71986737-3c037c80-322d-11ea-8e57-20c92812321b.png)

Exporting ybot file and viewing in Godot 3.2 beta : Seems to be OK
![image](https://user-images.githubusercontent.com/1696020/71986796-589fb480-322d-11ea-9ea6-541ca71c5c79.png)

Now, in ybot file, I added a cube near the character, to check scaling:

![image](https://user-images.githubusercontent.com/1696020/71987045-c0ee9600-322d-11ea-973c-b3e1b3ffaf31.png)

Viewing in https://gltf-viewer.donmccurdy.com/ :

![image](https://user-images.githubusercontent.com/1696020/71987159-f4c9bb80-322d-11ea-9192-809c2965311b.png)

Viewing in https://sandbox.babylonjs.com/ :

![image](https://user-images.githubusercontent.com/1696020/71987331-496d3680-322e-11ea-8075-cfd984e2dde7.png)

Viewing in Godot 3.2 beta :

![image](https://user-images.githubusercontent.com/1696020/71987434-76214e00-322e-11ea-9644-3a7a53a7d148.png)

So ... not sure there is some issue here in blender exporter (but maybe in viewer @donmccurdy ?)
Can you please confirm ?

**Comment by youaresoomean** [comment] 2020-01-08 15:18
Used the built-in Windows 10 3D Viewer and our own engine to view the gltf data. Noticed the scale diff between 2.80 and 2.8x exports.

**Comment by julienduroure** [comment] 2020-01-08 17:17
I added a cube in the .blend file, and exported scene, using 2.80 and 2.82 alpha.
I can't see any scale issue.
Can you please share some screenshots and corresponding glb or gltf files ?
Thanks

**Comment by donmccurdy** [comment] 2020-01-08 18:39
@julienduroure there is a known issue in my viewer (https://github.com/donmccurdy/three-gltf-viewer/issues/147), that the skinning deformation is not taken into account for the default camera position. So if the skinning deformation applies a 100x scale (very possible if the model was converted from FBX), the camera will focus on an area 100x too small. Adding an unskinned cube at the same size fixes that issue, because the viewer will position the camera to include it.

You can get a rough sense of the "world scale" of the model by enabling the "Grid" option in my viewer's settings. Based on the grid sizing (1 unit / square), it looks like the object's scale is correct and it's just the default viewport choice that is wrong. See screenshot:

![Screen Shot 2020-01-08 at 10 37 55 AM](https://user-images.githubusercontent.com/1848368/72005676-08136180-3203-11ea-915d-7d9d72bce06b.png)

**Comment by youaresoomean** [comment] 2020-01-13 07:26
The explaination regarding @donmccurdy 's viewer might also apply to the built-in Windows 10 3d viewer. If i place a box next to the model it looks ok. The grid also indicates camera/viewer distance is off. 
I have to check our GLTF loading code to find out what scaling/transform i am missing. 
The remaining question is why it changed between 2.80 <-> 2.81..or what changed?

[gltf_armature_scale_issue_2.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4052438/gltf_armature_scale_issue_2.zip)

**Comment by julienduroure** [comment] 2020-01-13 08:57
@youaresoomean Between 2.80 and 2.81, we fixed some bugs regarding InverseBindMatrix, and how skin data are exported.
See #566 if you want some details about this discussion.

So, seems there is no bug here is exporter --> Closing this ticket

**Closed by julienduroure** 2020-01-13 08:57 UTC
Labels: Animation, Skinning_&_Rigging, exporter, question
