### ISSUE TITLE
Documentation: explain how to export smooth/sharp shading (actually, maybe bug or regression?)

### ISSUE THREAD

**Issue by Vinc3r** [KhronosGroup/glTF-Blender-IO#911] opened 2020-02-03 08:59 UTC
On Blender 2.79, users was allowed to use autosmooth to export smooth & sharp shading in gltf files (which was very convenient by the way, should be a great default behaviour to remerge IMO), but [that's not anymore the case since 2.8 series](https://user-images.githubusercontent.com/3873421/73638928-9d234200-466b-11ea-8931-b5722c0844f9.jpg): user now must use Edge Split modifier and check "apply modifier" option on export (in large scenes this extend the export time, that's why autosmooth option could be great also).

In short, the documentation should mention the workflow to save mesh normals.

**Comment by emackey** [comment] 2020-02-04 19:44
I don't think this was intentionally turned off.  It sounds like a bug, or a regression.

**Comment by Vinc3r** [comment] 2020-02-05 10:45
If it's possible to make this functionnality comes back, I'm all in!

**Comment by julienduroure** [comment] 2020-02-05 11:51
Maybe linked to #877, and child tickets

**Comment by emackey** [comment] 2020-02-11 21:31
Looks like I'm wrong, this is not a regression.  It's a bug that somehow I thought was fixed that never seems to have been fixed: #799

One workaround (for non-skinned models at least) is to check "Apply Modifiers".  There's an implicit "Edge Split" modifier that is temporarily applied during glTF export when this is checked, and that's what causes the correct auto smooth effects to happen.

Another workaround is to click the button to "Add Custom Split Normal Data".  I haven't tested this much but I think it essentially bakes the results of auto-smoothing into the custom normals, and the exporter uses those.  Should work with skinned models, but might need to be redone (remove and re-add custom normals) after geometry changes (unless Blender does this already, I didn't test it).

**Comment by Vinc3r** [comment] 2020-02-12 08:21
'was'nt aware about the implicit edge split modifier, great to know (but as I said on my first message, on large scene it's an export-time killer).

About the Add Custom Split Normal Data from what I've tested for now it works. I will add this functionnality to my [ReTiCo](https://github.com/Vinc3r/ReTiCo#retico) addon since user can't apply this operation on multiple selected meshes (using the alt + click trick).

**Comment by julienduroure** [comment] 2020-02-14 05:44
Closing this ticket, as #877 will remain the main ticket about normal export refactoring

**Closed by julienduroure** 2020-02-14 05:44 UTC
Labels: Material, bug, exporter
