### ISSUE TITLE
Vertices order

### ISSUE THREAD

**Issue by tasticad** [KhronosGroup/glTF-Blender-IO#1185] opened 2020-08-21 21:33 UTC
Vertices are reordered after geometry export. 
This might be in order to lighten the file, however could an option like "not optimizing vertices" be added for exporting glTF/glb files?
It would be very helpfull in order to work with three.js and multi-materials meshes.

**Comment by donmccurdy** [comment] 2020-08-23 23:12
@tasticad Part of the problem is that Blender vertices can't necessarily translate 1:1 with vertices in the exported file. Data like color or normals might sometimes require vertices to be split, n-gons have to be triangulated, rendered points and lines separated from triangles, and so on. Doing that export correctly and efficiently is not trivial, and so while we aren't intentionally changing order, it could potentially happen for a number of reasons. And moreover, it's not really clear (to me at least) how to observe order of vertices in Blender to determine whether the exporter has maintained that order.

It sounds like triangulating in advance is doing what you need, so I'll close this issue, but if you still have a problem and can share how to clearly observe the order that you expect, please let us know.

**Closed by donmccurdy** 2020-08-23 23:12 UTC
