### ISSUE TITLE
Can't export occlusion map with gltf material output group

### ISSUE THREAD

**Issue by kokotron** [KhronosGroup/glTF-Blender-IO#2112] opened 2024-01-12 16:08 UTC
[occlusion_test_402.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/13921220/occlusion_test_402.zip)
I try to export a glb with various setting combinations in Blender 4.0.2, but I can't get the occlusion map to export along. I've tried both with and without uv map assignment in the shading editor. I tried exporting with my settings of preference on and off (compression, apply modifiers, export renderable), but it made no difference. I attach a suitable blend and exported glb file.

**Comment by julienduroure** [comment] 2024-01-12 17:26
This is a duplicate of #2083 
Closing this one, please follow information on the other one

**Closed by julienduroure** 2024-01-12 17:26 UTC
