### ISSUE TITLE
Export to .glb and .gltf results in near-empty files

### ISSUE THREAD

**Issue by cor-rine** [KhronosGroup/glTF-Blender-IO#1066] opened 2020-05-13 07:21 UTC
**Describe the bug**
Exporting to .glb or .gltf produces near-empty files that do not contain any geometry, mesh, or scene information.

**To Reproduce**
1. Open the sheep.blend file provided in the link below
2. Select sheep and go to File > Export > glTF 2.0
3. Select either .glb or .glTF export format (Include: Selected Objects, Geometry: Apply Modifiers)
4. Press Export, and observe created export files (also included in the Dropbox link for reference)

**Expected behavior**
Files should contain all scene and geometry and mesh information.  Export is successful so that the files can be loaded into Three.js web application.

**Actual behavior**
Files do not contain all scene and geometry and mesh information.  Export is unsuccessful and files cannot be loaded into Three.js web application.

**.blend file/ .gltf**
Files: https://www.dropbox.com/sh/nigh8m2yzd1i0fg/AAA2OU6lKB58Q_ZztaC9aVNMa?dl=0

**Version**
 - OS: macOS Mojave
 - Blender Version 2.82a 2020-03-12

**Comment by julienduroure** [comment] 2020-05-13 13:46
Hello,
Seems to be a duplicate of #193 
Currently, to export your sheep, you have to select the armature too.

**Comment by cor-rine** [comment] 2020-05-13 16:28
Ah! Excellent - thank you very much!

**Comment by sofiavera24** [comment] 2020-08-24 22:23
I am having an error when I want to export this model in GLTF format (I have followed this tutorial: https://www.youtube.com/watch?v=g4LmR-TYxVo ), I try to export it and it gives me an error, I attach error, I need to solve it as soon as possible, if someone can help me I would really appreciate it!

Error: Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/__init__.py", line 506, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 42, in save
    json, buffer = __export(export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 55, in __export
    __gather_gltf(exporter, export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 64, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 37, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 60, in __gather_scene
    blender_scene, None, export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 47, in gather_node
    node = __gather_node(blender_object, library, blender_scene, dupli_object_parent, export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 65, in __gather_node
    mesh=__gather_mesh(blender_object, library, export_settings),
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 333, in __gather_mesh
    export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py", line 44, in gather_mesh
    primitives=__gather_primitives(blender_mesh, library, blender_object, vertex_groups, modifiers, material_names, export_settings),
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py", line 136, in __gather_primitives
    export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_primitives.py", line 62, in gather_primitives
    export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py", line 54, in gather_material
    normal_texture=__gather_normal_texture(blender_material, export_settings),
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py", line 164, in __gather_normal_texture
    export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_material_normal_texture_info_class.py", line 30, in gather_material_normal_texture_info_class
    if not __filter_texture_info(blender_shader_sockets_or_texture_slots, export_settings):
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_material_normal_texture_info_class.py", line 58, in __filter_texture_info
    if any([__get_tex_from_socket(socket) is None for socket in blender_shader_sockets_or_texture_slots]):
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_material_normal_texture_info_class.py", line 58, in <listcomp>
    if any([__get_tex_from_socket(socket) is None for socket in blender_shader_sockets_or_texture_slots]):
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_material_normal_texture_info_class.py", line 141, in __get_tex_from_socket
    gltf2_blender_search_node_tree.FilterByType(bpy.types.ShaderNodeTexImage))
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_search_node_tree.py", line 101, in from_socket
    return __search_from_socket(start_socket, shader_node_filter, [])
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_search_node_tree.py", line 90, in __search_from_socket
    linked_results = __search_from_socket(input_socket, shader_node_filter, search_path + [link])
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_search_node_tree.py", line 90, in __search_from_socket
    linked_results = __search_from_socket(input_socket, shader_node_filter, search_path + [link])
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_search_node_tree.py", line 90, in __search_from_socket
    linked_results = __search_from_socket(input_socket, shader_node_filter, search_path + [link])
  [Previous line repeated 967 more times]
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_search_node_tree.py", line 86, in __search_from_socket
    if shader_node_filter(linked_node):
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_search_node_tree.py", line 57, in __call__
    return isinstance(shader_node, self.type)
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by sofiavera24** [comment] 2020-08-24 22:25
I am having an error when I want to export this model in GLTF format (I have followed this tutorial: https://www.youtube.com/watch?v=g4LmR-TYxVo ), I try to export it and it gives me an error, I attach error, I need to solve it as soon as possible, if someone can help me I would really appreciate it!

Sistem: MacOS Catalina

Error: Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/__init__.py", line 506, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 42, in save
    json, buffer = __export(export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 55, in __export
    __gather_gltf(exporter, export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 64, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 37, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather.py", line 60, in __gather_scene
    blender_scene, None, export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 47, in gather_node
    node = __gather_node(blender_object, library, blender_scene, dupli_object_parent, export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 65, in __gather_node
    mesh=__gather_mesh(blender_object, library, export_settings),
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_nodes.py", line 333, in __gather_mesh
    export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py", line 44, in gather_mesh
    primitives=__gather_primitives(blender_mesh, library, blender_object, vertex_groups, modifiers, material_names, export_settings),
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_mesh.py", line 136, in __gather_primitives
    export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_primitives.py", line 62, in gather_primitives
    export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py", line 54, in gather_material
    normal_texture=__gather_normal_texture(blender_material, export_settings),
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_materials.py", line 164, in __gather_normal_texture
    export_settings)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_cache.py", line 65, in wrapper_cached
    result = func(*args)
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_material_normal_texture_info_class.py", line 30, in gather_material_normal_texture_info_class
    if not __filter_texture_info(blender_shader_sockets_or_texture_slots, export_settings):
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_material_normal_texture_info_class.py", line 58, in __filter_texture_info
    if any([__get_tex_from_socket(socket) is None for socket in blender_shader_sockets_or_texture_slots]):
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_material_normal_texture_info_class.py", line 58, in <listcomp>
    if any([__get_tex_from_socket(socket) is None for socket in blender_shader_sockets_or_texture_slots]):
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_material_normal_texture_info_class.py", line 141, in __get_tex_from_socket
    gltf2_blender_search_node_tree.FilterByType(bpy.types.ShaderNodeTexImage))
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_search_node_tree.py", line 101, in from_socket
    return __search_from_socket(start_socket, shader_node_filter, [])
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_search_node_tree.py", line 90, in __search_from_socket
    linked_results = __search_from_socket(input_socket, shader_node_filter, search_path + [link])
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_search_node_tree.py", line 90, in __search_from_socket
    linked_results = __search_from_socket(input_socket, shader_node_filter, search_path + [link])
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_search_node_tree.py", line 90, in __search_from_socket
    linked_results = __search_from_socket(input_socket, shader_node_filter, search_path + [link])
  [Previous line repeated 967 more times]
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_search_node_tree.py", line 86, in __search_from_socket
    if shader_node_filter(linked_node):
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_search_node_tree.py", line 57, in __call__
    return isinstance(shader_node, self.type)
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by donmccurdy** [comment] 2020-08-24 22:25
@sofiavera24 could you open a new issue, and attach the `.blend` file when you do? Without an example file we won't be able to fix the issue.

**Closed** 2020-09-02 19:47 UTC
Labels: duplicate
