### ISSUE TITLE
Normals export for morph targets seems to be broken for mesh with custom normal data.

### ISSUE THREAD

**Issue by taranjlu** [KhronosGroup/glTF-Blender-IO#976] opened 2020-03-15 09:45 UTC
**Describe the bug**
When viewing the output GLTF in a viewer such as https://gltf-viewer.donmccurdy.com/ enabling morph targets breaks normal shading (seems to revert to plain smooth shading or something similar).

I created a simple test scene exported to FBX from Maya which brought in custom normal data and shape keys, but the attached scene was made directly in Blender 2.82.

I also tried various combinations of the different export settings (enabling tangets and morph tangets, embedded gltf vs glb, etc.) but nothing seemed to fix the normals issue.

**To Reproduce**
1. Generate simple scene with custom normals (via import or set using "Geometry Data -> Add Custom SPlit Normals Data") and shape keys.
2. Make sure "Auto Smooth" is enabled to show (apply?) the custom normal data (should be enabled by default if importing FBX).
3. Export GLTF file with default settings.
4. View in this viewer (or other threejs based viewers): https://gltf-viewer.donmccurdy.com/

**Expected behavior**
When the morph targets are applied, the shading should reflect the interpolated custom normals (instead of using generated smooth shading).

When viewed with the linked viewer, the shading looks correct while all of the morph target weights are set to zero (i.e. the basis) and then is immediately broken as soon as any morph targets are given weights.

**Screenshots**
![image](https://user-images.githubusercontent.com/6187278/76698949-8c4fee00-6665-11ea-8861-c0f84c3ff219.png)
Correct normals when no morph targets are active
![image](https://user-images.githubusercontent.com/6187278/76698943-75110080-6665-11ea-87d7-b0ceb5f75dfe.png)
Broken morph normals when morph targets are active

**.blend file/ .gltf**
[gltf_morph_normals_broken.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4333981/gltf_morph_normals_broken.zip)

**Version**
 - OS: macOS, Windows
 - Blender Version: 2.82

**Additional context**
- This seems to likely be an issue with the exporter, but it is also possible that the viewer is not correctly interpreting the morph normal data.
- I think this issue might be related to #230

**Comment by julienduroure** [comment] 2020-03-15 10:18
This is a duplicate of #100

**Comment by taranjlu** [comment] 2020-03-15 18:33
@julienduroure Ah, sorry, didn't realized that had already been reported. I assume there aren't currently any workarounds that use this exporter? If that is the case, do you know of any other exporters/converters that do handle morph target custom normals?

**Comment by taranjlu** [comment] 2020-03-15 18:37
I would also be interested in trying to help fix this issue once I have some time to look at the code.

**Closed** 2020-07-21 18:26 UTC
Labels: duplicate
