### ISSUE TITLE
custom split normals data not exported

### ISSUE THREAD

**Issue by Lexpartizan** [KhronosGroup/glTF-Blender-IO#458] opened 2019-05-12 19:09 UTC
I smoothing mesh with normal editor blend4web.
In blender this mesh look OK.
In exported obj this mesh look OK.
In exported gltf this looks,like normals not editing.
Blend and glb files attached.
Sorry for my english.

[normals not exported.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3170453/normals.not.exported.zip)

**Comment by Cyp** [comment] 2019-05-15 21:51
Is this a duplicate of #436?

**Comment by Lexpartizan** [comment] 2019-05-16 04:45
Maybe. My english bad. I Use smooth shading, not flat.

**Comment by donmccurdy** [comment] 2019-07-17 01:34
Fixed by https://github.com/Cyp/glTF-Blender-IO/commit/c9e33f3c8838cc9c6f6cf51c65e28b5ee073e4f0

**Closed by donmccurdy** 2019-07-17 01:34 UTC
Labels: Material, exporter
