### ISSUE TITLE
Vertex Bone Indices (JOINTS_0) are incorrect when using Draco compression

### ISSUE THREAD

**Issue by atteneder** [KhronosGroup/glTF-Blender-IO#1332] opened 2021-02-16 11:46 UTC
**Describe the bug**
It appears that the vertex bone indices produce incorrect values when using draco compression.

**To Reproduce**
1. Download the sample file [skin test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5988207/skin.test.zip)
It's a minimum use case with one triangle and an armature with one bone per vertex. I exported the triangle to glTF twice. In folder 'gltf' it's not compressed and in folder 'gltf-draco' it has Draco compression.
Created with Blender 2.91.2 and glTF-Blender-IO 1.4.40

2. Reading the values in the non-compressed version (using hex editor) gives the bone indices (one line per vertex):

1 / 0 / 0 / 0
2 / 0 / 0 / 0
0 / 0 / 0 / 0

> note: UNSIGNED_BYTE

3. Trying to retrieve the values via draco lib (current master branch; via small C++ test app I hacked) gives these values:

1 / 0 / 2 / 0
0 / 0 / 0 / 0
48304 / 11301 / 1 / 0

> note: UNSIGNED_SHORT

Looking at the alignment, it seems like the uncompressed source values (in unsigned bytes) is just copied into the destination (which is unsigned shorts) 

4. Practical usage example

I tried loading both glTFs in the [three.js editor](https://threejs.org/editor/) and move the bones to see if it works.
uncompressed worked as expected, the draco version not.

**Expected behavior**
I'd expect the skinning to work with Draco as well and identical indices values.

> Bonus: use unsigned bytes in draco as well, if indices fit into that range.

**Screenshots**
not required

**.blend file/ .gltf**
See ZIP file above

**Version**
 - OS: macOS Big Sur 11.1
 - Blender Version 2.91.2
 - glTF-Blender-IO 1.4.40

**Additional context**
none required

**Comment by julienduroure** [comment] 2021-02-22 16:58
@McNopper Hello. Can someone from you team can have a look?

**Comment by scurest** [comment] 2021-02-22 17:42
@atteneder Works fine for me in 2.93. Draco stuff changed since 2.91 so try a more recent version -> https://builder.blender.org/download/

**Comment by UX3D-nopper** [comment] 2021-02-22 17:52
@UX3D-eckerlein Can you please support this issue?

**Comment by atteneder** [comment] 2021-02-22 18:06
Couldn't test Blender 2.93 due to (presumably) unrelated error:

```
'/Applications/Blender2.93Alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/libextern_draco.dylib' exists, draco mesh compression is available
Python: Traceback (most recent call last):
  File "/Applications/Blender2.93Alpha/Blender.app/Contents/Resources/2.93/scripts/addons/io_scene_gltf2/__init__.py", line 457, in execute
    from .blender.exp import gltf2_blender_export
  File "/Applications/Blender2.93Alpha/Blender.app/Contents/Resources/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 23, in <module>
    from io_scene_gltf2.blender.exp.gltf2_blender_gltf2_exporter import GlTF2Exporter
  File "/Applications/Blender2.93Alpha/Blender.app/Contents/Resources/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gltf2_exporter.py", line 23, in <module>
    from io_scene_gltf2.io.exp import gltf2_io_buffer
  File "/Applications/Blender2.93Alpha/Blender.app/Contents/Resources/2.93/scripts/addons/io_scene_gltf2/io/exp/gltf2_io_buffer.py", line 15, in <module>
    import base64
  File "/Applications/Blender2.93Alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/base64.py", line 11, in <module>
    import binascii
ImportError: dlopen(/Applications/Blender2.93Alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/lib-dynload/binascii.cpython-39-darwin.so, 2): Library not loaded: libz.1.dylib
  Referenced from: /Applications/Blender2.93Alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/lib-dynload/binascii.cpython-39-darwin.so
  Reason: unsafe use of relative rpath libz.1.dylib in /Applications/Blender2.93Alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/lib-dynload/binascii.cpython-39-darwin.so with restricted binary

location: <unknown location>:-1
```

I can try it on Windows later this week.

Thanks!

**Comment by scurest** [comment] 2021-02-22 18:13
https://developer.blender.org/T85648

Someone posted a workaround in the first comment.

**Comment by atteneder** [comment] 2021-02-22 18:18
> https://developer.blender.org/T85648
> 
> Someone posted a workaround in the first comment.

That's interesting, thanks. Not an option on my corporate work machine though => Will test later on another computer.

**Comment by UX3D-eckerlein** [comment] 2021-02-23 12:17
Just for clarification, this problem is indeed unrelated to the actual issue:

> Couldn't test Blender 2.93 due to (presumably) unrelated error:
> 
> ```
> '/Applications/Blender2.93Alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/libextern_draco.dylib' exists, draco mesh compression is available
> Python: Traceback (most recent call last):
>   File "/Applications/Blender2.93Alpha/Blender.app/Contents/Resources/2.93/scripts/addons/io_scene_gltf2/__init__.py", line 457, in execute
>     from .blender.exp import gltf2_blender_export
>   File "/Applications/Blender2.93Alpha/Blender.app/Contents/Resources/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_export.py", line 23, in <module>
>     from io_scene_gltf2.blender.exp.gltf2_blender_gltf2_exporter import GlTF2Exporter
>   File "/Applications/Blender2.93Alpha/Blender.app/Contents/Resources/2.93/scripts/addons/io_scene_gltf2/blender/exp/gltf2_blender_gltf2_exporter.py", line 23, in <module>
>     from io_scene_gltf2.io.exp import gltf2_io_buffer
>   File "/Applications/Blender2.93Alpha/Blender.app/Contents/Resources/2.93/scripts/addons/io_scene_gltf2/io/exp/gltf2_io_buffer.py", line 15, in <module>
>     import base64
>   File "/Applications/Blender2.93Alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/base64.py", line 11, in <module>
>     import binascii
> ImportError: dlopen(/Applications/Blender2.93Alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/lib-dynload/binascii.cpython-39-darwin.so, 2): Library not loaded: libz.1.dylib
>   Referenced from: /Applications/Blender2.93Alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/lib-dynload/binascii.cpython-39-darwin.so
>   Reason: unsafe use of relative rpath libz.1.dylib in /Applications/Blender2.93Alpha/Blender.app/Contents/Resources/2.93/python/lib/python3.9/lib-dynload/binascii.cpython-39-darwin.so with restricted binary
> 
> location: <unknown location>:-1
> ```
> 
> I can try it on Windows later this week.
> 
> Thanks!

**Comment by UX3D-eckerlein** [comment] 2021-02-23 12:25
I could not reproduce the bug using Blender 2.92. There was a major [PR fixing and enhancing the Draco exporter/importer](https://developer.blender.org/D9642) which has been merged into Blender 2.92 (not into the gltf-Blender-IO addon).
So, just using Blender 2.92 or later fixes the issue.

**Comment by julienduroure** [comment] 2021-02-25 18:34
Ok, seems this bug is already fixed in recent build.
And now 2.92 is officially released

**Closed by julienduroure** 2021-02-25 18:34 UTC
Labels: draco, exporter

**Comment by atteneder** [comment] 2021-02-27 19:29
Can confirm now: fixed in master!
