### ISSUE TITLE
Normal export seems incorrect (Blender 2.79 and 2.8)

### ISSUE THREAD

**Issue by TheMoye** [KhronosGroup/glTF-Blender-IO#230] opened 2019-01-14 16:21 UTC
Importing a gltf file exported from Blender 2.79 or 2.8, normals do not conform to the one of the created object.

![normalesgltf](https://user-images.githubusercontent.com/46683101/51124873-a999ea00-181f-11e9-912f-11c3bf5fc043.jpg)
On the left the object created in Blender, on the right the same object exported and reimported.
Same result imported into Godot: normals are not correct.

It seems that the vertex and face normals are ok, but not the edge normals.

![normalesgltf3](https://user-images.githubusercontent.com/46683101/51125098-2d53d680-1820-11e9-8d6f-5b4bf5ecbeb9.gif)

Attached the blend file and the gltf file.

[BlendAndGltf.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2756021/BlendAndGltf.zip)

**Comment by UX3D-nopper** [comment] 2019-01-17 13:43
If one solves the autosmooth issue, the export is correct.

**Comment by Cyp** [comment] 2019-01-18 08:06
Is it a problem with autosmooth? If so, it might be relevant that autosmooth was ignored when exporting until 85d2490c7ca97ed2a5aacd3359d8208d3dcb88e7 (merged in f97ae8220fbbdd465e2008980115e45d8fddd151).

**Comment by JohnnieWooker** [comment] 2019-01-21 13:13
Hey,
I just wanted to know if there are any plans to solve this issue. The only workaround our studio found is exporting model as FBX and convert it to GLTF using Clay Viewer (https://github.com/pissang/clay-viewer).

**Comment by emackey** [comment] 2019-01-26 01:05
I've been researching this.  Blender doesn't make this simple, but, there are things we need to fix in the exporter to get this working better.

Let's start with a quick refresher on the intentions of the glTF format:  It's a delivery format, not an asset interchange format.  The internal structure of glTF, particularly of its binary section, is as close as possible to typical GPU data, ready-to-render.  This means there are no quads or Ngons in glTF, only triangles, as graphics hardware under the hood only renders triangles.  The triangles come from a pool of vertices, and each vertex can have "vertex attribute" data associated with it, such as one normal vector, one tangent vector, one UV per UV map in the material, etc.  There's an implication here about what Blender users would consider "shared" vertices.  Blender, like most 3D tools, has a concept of per-vertex-per-face normal vectors (where a single vertex appears to have different normals on different adjoining faces).  Blender likewise can show different UVs _from the same UV map_ on a per-vertex-per-face basis.  This is needed for example by cylindrical UV mapping, where one edge is the "seam" that has the 1-to-0 discontinuity down one side.  This whole concept of "per vertex per face" is just at the application level though, the underlying graphics hardware has no such concept, and so neither does glTF (by design, it mirrors what the underlying hardware needs to render).  Preserving the "per face" aspect is done in glTF the same way it's done for hardware, by splitting into separate vertices under the hood.

Try importing the [Water Bottle](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/WaterBottle/glTF-Binary/WaterBottle.glb) sample into Blender 2.80.  The texture is like a cylinder, and the Blender +Y side hides a seam where the vertices have been split to allow for discontinuous UVs along the edge of the texture.  But we don't see a seam in Eevee or Cycles, why not?  The glTF model includes normal vectors that define smooth shading everywhere, including along the seam, and the Blender Importer has brought these normals in as "Custom Split Normals Data."

Blender thinks of these as user-defined normal data.  They obviously don't match flat shading, but interestingly they don't match smooth shading either, because those vertices along the edge really are duplicated as a result of the lack of per-vertex-per-face data.  If you clear the custom normals, you'll see a tiny bit of flat shading appear, along one edge loop running down the +Y side of the bottle where the vertices are duplicated.  Actually if you "remove double vertices" you'll see the seam vanish as Blender reinstates the per-vertex-per-face UV mapping, but of course this only moves us a step farther from how the data needs to be stored in glTF.

There's a quirk of Blender at play here as well:  Blender's "Custom Split Normals Data" (ie, customized or user-edited normals) are only visible when the "Auto smooth" checkbox is enabled, and on top of that, the angle setting that normally governs the "auto" portion of auto-smooth is darker gray because it's being overridden by the custom normals.  Blender actually offers a whole menu in edit mode, under Mesh->Normals with things like rotate, point to target, etc., for hand-editing of individual normal vectors, but these options only work when "Auto smooth" is checked, because these options all operate in the custom normal data (and will create that data if it doesn't exist).

Long story short, the Blender importer is doing the "correct" thing, as best it can, taking vertex normals from glTF, applying them as Blender's custom normal data, and turning on Auto smooth not for the sake of automatically calculating anything, but merely as a prerequisite for Blender to enable the custom normal data.  So the glTF normals are previewed and rendered in Blender.

The exporter, however, doesn't appear to be storing custom normal data in the output glTF.  To make matters worse, the custom data has the ability to be per-vertex-per-face, meaning the exporter would need to be smart enough to split these vertices in the glTF for any that differed per-face.  I need to check if the exporter is already doing that for per-vertex-per-face UVs, because if so, some similar functionality could probably be used for the normals (and tangents).

**Comment by marcatec** [comment] 2019-03-11 12:46
Because I needed custom normals for a project, I tested different glTF exporters for Blender 2.79.
This one https://github.com/Kupoman/blendergltf exported them correctly.
Maybe it could be some inspiration.
Testfile: https://github.com/aframevr/assets/blob/gh-pages/controllers/microsoft/default/right.glb

**Comment by marcatec** [comment] 2019-04-10 14:00
Thanks to @pjoe this problem seems to be fixed in #414.
My tests with the mentioned glTF file result in correctly exported custom normals.

**Closed** 2019-04-10 14:13 UTC
Labels: bug, enhancement, exporter

**Comment by MunoDevelop** [comment] 2020-10-05 13:00
export obj file instead fbx worked for me , but fbx export still wrongly export vertex normal

**Comment by julienduroure** [comment] 2022-02-02 14:56
Hello,
This repository is about glTF, not obj or fbx.
If you have an issue with glTF, please do not comment an old (already solved) issue : Create a new one, and follow guideline, providing all necessary information to be able to reproduce (including an example file). Thanks!
