### ISSUE TITLE
Error trying to add extension to animation

### ISSUE THREAD

**Issue by pepperoni505** [KhronosGroup/glTF-Blender-IO#1568] opened 2022-02-13 03:16 UTC
I'm developing an addon that adds an extension to all animations in a glTF. Here's my code that throws an error:

```python
from io_scene_gltf2.io.com.gltf2_io_extensions import Extension

def gather_gltf_hook(self, gltf2_plan, export_settings):
    for animation in gltf2_plan.animations:
        animation.extensions["test_extension"] = Extension(
            name="test_extension",
            extension={
                "test": [
                    {
                        "test": 1
                    }
                ]
            },
            required=False
        )
```
Here's the error:
```
03:13:26 | ERROR: An error occurred on line 71 in statement return [f(y) for y in x]
03:13:26 | ERROR: An error occurred on line 392 in statement result["channels"] = from_list(lambda x: to_class(AnimationChannel, x), self.channels)
03:13:26 | ERROR: An error occurred on line 66 in statement return x.to_dict()
03:13:26 | ERROR: An error occurred on line 331 in statement result["target"] = to_class(AnimationChannelTarget, self.target)
03:13:26 | ERROR: An error occurred on line 65 in statement assert isinstance(x, c)
03:13:26 | ERROR: An error occurred on line 46 in statement return f(x)
03:13:26 | ERROR: An error occurred on line 38 in statement assert x is None
```
The example provided is a very oversimplified example of the issue

**Comment by julienduroure** [comment] 2022-02-13 05:53
Duplicate of #1501 ?

**Comment by pepperoni505** [comment] 2022-02-13 18:20
Yep, appears to be so. Is there any workaround for the isuse?

**Comment by julienduroure** [comment] 2022-02-15 20:56
__gather_gltf_hook__ hook should be used only for modifying/adding extension at root of glTF. 
You can't modify data already in glTF json, except in "extensions" at root of file

![image](https://user-images.githubusercontent.com/1696020/154146643-ca1bf797-9cdb-494c-b1bd-bd6a373194a1.png)

If you want modifying an animation, you have to use the __gather_animation_hook__**
If you want to add a new animation to existing list of animations, I don't think there is a hook yet. This is probably what you are looking for.

**Comment by julienduroure** [comment] 2022-02-15 21:00
Maybe we have to rename the hook __gather_animation_hook__

**Comment by julienduroure** [comment] 2022-02-15 21:26
@pepperoni505 Can you please have a look on #1571?
You will be able to create new animations with this one. And with your #1553 , are you able to create what you want?

**Comment by pepperoni505** [comment] 2022-02-15 21:57
Your PR looks good - thanks for making it. Would you mind checking my comment on your PR?

**Comment by julienduroure** [comment] 2022-02-15 22:02
Fixed

**Closed** 2022-02-16 10:46 UTC
