### ISSUE TITLE
module 'numpy' has no attribute 'bool'. Did you mean: 'bool_'?

### ISSUE THREAD

**Issue by madqueensaph** [KhronosGroup/glTF-Blender-IO#1844] opened 2023-01-27 17:32 UTC
**Describe the bug**
When attempting to import a `.vrm` file using the [VRM-Addon-for-Blender](https://github.com/saturday06/VRM-Addon-for-Blender), a Python stacktrace is shown and printed to the terminal stating:
`module 'numpy' has no attribute 'bool'. Did you mean: 'bool_'?`

This seems to be an issue with `io_scene_gltf2` and the version of NumPy that's being used and not the VRM Addon.

**To Reproduce**
1. Install the VRM Addon by going to [the GitHub repo](https://github.com/saturday06/VRM-Addon-for-Blender) and following the instructions
2. Go to `File -> Import -> VRM (.vrm)`
3. Select a file
4. View Python Error popup (showing stacktrace) in Blender and/or view Python stacktrace in terminal/console

**Expected behavior**
The model should import and become available for modification to bones, textures, etc.

**Version**
 - OS: Gentoo Linux
 - Blender Version: 3.4.1

**Additional context**
This happened after I updated my packages and seems to be an issue regarding NumPy's removal of aliases to built-in types (which I found from the [1.20.0 release notes](https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated)). This was not an issue before I updated, but when checking my NumPy version I discovered it was version 1.24.0, which means this change to NumPy applies.

When I decided to edit the file and line shown in the stacktrace, which in my case was line 612 of `/usr/share/blender/3.4/scripts/addons/io_scene_gltf2/blender/imp/gltf2_blender_mesh.py`, I was able to modify `np.bool` to `bool` and the add-on worked as intended. I also tested `np.bool_` and it also worked as intended.

**Comment by julienduroure** [comment] 2023-01-27 17:35
Hello,

You have this issue, because Gentoo packager is not using the python package provided by Blender, but the python package from Gentoo system.

Anyway, this bug is already fixed in current main branch ( 621378b193f6fba193e0cdc9582450fe74e8c632 )

Thanks !

**Closed by julienduroure** 2023-01-27 17:35 UTC

**Comment by alice-i-cecile** [comment] 2023-02-07 14:50
Just confirmed: this is fixed in the Blender 3.5 release.
