### ISSUE TITLE
baseColorFactor is always set to 1.0 no matter what the materials alpha says

### ISSUE THREAD

**Issue by aguaviva** [KhronosGroup/glTF-Blender-IO#784] opened 2019-11-22 13:24 UTC
**Describe the bug**

baseColorFactor is always set to 1.0
```
             "baseColorFactor" : [
                    0.800000011920929,
                    0.800000011920929,
                    0.800000011920929,
                    1.0
                ],
```

It should be set to whatever the material specifies:

![image](https://user-images.githubusercontent.com/5200915/69429242-68257580-0d33-11ea-9e72-882b7c1826a8.png)

**To Reproduce**
Create a box, set its material to be just a color. Set the alpha to some number, export, notice how the alpha was set to 1

**Version**
 - Blender Version 2.81

**Comment by emackey** [comment] 2019-11-25 19:03
Currently, this exporter (wrongly) uses the alpha value of the baseColor itself as the 4th component of the baseColorFactor.

**Comment by donmccurdy** [comment] 2019-11-25 20:02
That Alpha socket is a more recent addition to the Principled BSDF node, but agreed that we should support it.

**Comment by mattrossman** [comment] 2020-06-22 16:46
@donmccurdy per your comment [on StackOverflow](https://stackoverflow.com/a/62335262) do you want to change the label to bug?

**Comment by donmccurdy** [comment] 2020-06-22 16:55
I believe we do support the alpha socket now — before marking this as a bug could we find a `.blend` file that reproduces the issue?

**Comment by mattrossman** [comment] 2020-06-22 17:11
Here is a `.blend` I just made in Blender 2.83.0. I exported "Cube Original" as `alpha.glb` and then reimported it into the scene as `Cube Reimported`. You can see the alpha socket has been reset to 1. I also tested it in Blender 2.9.0 alpha. Not sure if the issue is on export or import.

[alpha.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4814573/alpha.zip)

**Comment by scurest** [comment] 2020-06-22 21:01
> Not sure if the issue is on export or import.

It's on export.

**Comment by donmccurdy** [comment] 2020-06-29 04:43
PR in https://github.com/KhronosGroup/glTF-Blender-IO/pull/1106.

**Closed** 2020-07-10 10:54 UTC
Labels: Material, enhancement, exporter
