### ISSUE TITLE
T63479: GLFT export with linked external file causes an exception

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#420] opened 2019-04-11 06:31 UTC
See issue on Blender tracker:
https://developer.blender.org/T63479

**Comment by capnm** [comment] 2019-04-11 06:36
Duplicate of #225

**Comment by emackey** [comment] 2019-04-11 14:09
Thanks @capnm.  Closing as duplicate.  Follow #225 for updates here.

**Closed by emackey** 2019-04-11 14:09 UTC
Labels: bug, exporter
