### ISSUE TITLE
PBR base color export issue

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-IO#160] opened 2018-12-11 20:50 UTC
Importing this model... https://sketchfab.com/models/de3051373c3b48bb8280a8ffa61af10e ... on the current master branch gives a correct result in Blender, but incorrect on export.

| before | after |
|---|---|
| ![screen shot 2018-12-11 at 12 46 29 pm](https://user-images.githubusercontent.com/1848368/49829256-cfc0fb80-fd42-11e8-9cea-b4376b4e6702.png) | ![screen shot 2018-12-11 at 12 46 06 pm](https://user-images.githubusercontent.com/1848368/49829269-d6e80980-fd42-11e8-9aab-bf41aa6f1a08.png) |

Losing AO is expected per #123 but I think there's more happening than that. Compare these ORM textures:

| before | after |
|--|--|
| ![body_metallicroughness](https://user-images.githubusercontent.com/1848368/49829310-f7b05f00-fd42-11e8-9d04-0183fa7ceef4.png) | ![body_metallicroughness png](https://user-images.githubusercontent.com/1848368/49829316-fb43e600-fd42-11e8-93ab-5c338a6071e5.png) |

**Comment by emackey** [comment] 2018-12-11 21:46
I took a screenshot of your two ORM maps above, and separated the channels in GIMP.  The red channel has been lost, but green and blue look the same when isolated.

Check your base color images.  I was able to reproduce this, and some of my exported base color textures have extremely bright yellow in them, which appears to be the main cause of the problem here.

**Comment by donmccurdy** [comment] 2018-12-11 22:18
Ah you're right, that looks like the cause. Maybe related to https://github.com/KhronosGroup/glTF-Blender-IO/issues/130 and re-rendering textures when we should just copy them?

| before | after |
|--|--|
| ![body_basecolor](https://user-images.githubusercontent.com/1848368/49833758-51b72180-fd4f-11e8-889f-85c3eacb2acf.jpeg) | ![body_basecolor](https://user-images.githubusercontent.com/1848368/49833763-54197b80-fd4f-11e8-980e-ec810f264b4b.png) |


This model also has vertex colors — I didn't check to see how/if they're used, but per https://github.com/KhronosGroup/glTF-Blender-IO/issues/127 that's another known issue.

**Comment by donmccurdy** [comment] 2018-12-11 22:19
Here's the shader graph generated by the importer:

![screen shot 2018-12-11 at 12 45 04 pm](https://user-images.githubusercontent.com/1848368/49833892-c722f200-fd4f-11e8-976e-8844cd72937d.png)

**Comment by emackey** [comment] 2018-12-11 22:36
The vertex colors are certainly one problem.  Search the Sketchfab download for the following string:

```
    "material": 0,
```

You will find eleven occurrences of material zero.  Some of the meshes that use it have `COLOR_0` vertex colors, and some do not.  This is legal, in glTF, but unfortunate.  I know we fixed a bug in Cesium some time ago, internally splitting materials like this into two, one for the vertex-colored primitives and one for the non-vertex-colored primitives.  Babylon and Three are likewise able to handle this correctly.

But the Blender _importer_ here uses only a single Blender material, and wires up the nodes for vertex colors.  Some of the colors are missing, for example the top of the back of the Llama has no vertex colors, so looks black in the Blender preview.

![cyber_llama_missing_back](https://user-images.githubusercontent.com/1235080/49834622-dcf1e080-fd6a-11e8-8518-a49d76c32932.png)

I suspect this is a separate issue from the base color channel configuration export issue.  The Cyberllama may be displaying multiple bugs.

**Comment by julienduroure** [comment] 2018-12-12 05:41
@emackey You're right, there is maybe a problem in importer linked to material / vertex color, because vertex color is store at primitive level. This is a problem I started to understand in #30

**Comment by UX3D-nopper** [comment] 2018-12-12 07:38
We revisit the bug, if it comes to the export part again.

**Comment by UX3D-nopper** [comment] 2018-12-12 09:08
Also, for the exporter, it would be much more convenient, if the color attribute is just multiplied with the base color.

**Comment by julienduroure** [comment] 2018-12-15 05:30
Problem of material sometimes uses vertex color and sometimes does'nt (#30) is now fixed

**Comment by julienduroure** [comment] 2018-12-15 05:34
Seems problem of exporting is still there

Original glb (in Don's viewer):
![before](https://user-images.githubusercontent.com/1696020/50039463-473ca680-0033-11e9-821c-9bb312b3fd7d.png)

In blender after import:
![blender](https://user-images.githubusercontent.com/1696020/50039467-4dcb1e00-0033-11e9-9f3c-b4aea650c079.png)

In Don's viewer after glb exporting:
![after](https://user-images.githubusercontent.com/1696020/50039468-528fd200-0033-11e9-8092-459d25b00da1.png)

**Comment by julienduroure** [comment] 2018-12-15 05:38
@McNopper You're request about using multiply with color base will be done as part of #78 
Will try to do it ASAP

**Comment by julienduroure** [comment] 2018-12-15 06:42
@UX3D-nopper It's done for base color ( texture with or without factor).

Note that it's still TODO for emissive & for extensions

**Comment by UX3D-schmithuesen** [comment] 2018-12-18 14:15
I can not reproduce this on the current master, both the glTF and glb export look fine in Don's viewer.

**Closed by UX3D-schmithuesen** 2018-12-18 14:15 UTC
Labels: bug, exporter
