### ISSUE TITLE
The exported objects have wrong transforms in O3DE

### ISSUE THREAD

**Issue by kursad-k** [KhronosGroup/glTF-Blender-IO#2159] opened 2024-03-13 02:14 UTC
**Describe the bug**
I have been testing the glTF pipeline with O3dE and Blender. While the crucial stuff works I cant get the orientation to work properly between these two apps.  The FBX files from Blender works perfectly but the glTF files not so much. 

I tested Yup and without Yup, and both options produced the wrong orientation in the target app.

**To Reproduce**
1. Open the attached scene
2. Exported the selection as glTF
3. Try Yup as an option

**Expected behavior**
I would expect the orientation to match in O3DE.

**Screenshots**
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/67970138/47f79fdf-dc11-4ec7-b491-3d3f7b0d119e)

**.blend file/ .gltf (mandatory)**
(includes the exported gltf and fbx file along with the originating .blend file)

[Assets.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/14580990/Assets.zip)

**Version**
 - OS: Windows
 - Blender Version 4.2 Nightly

**Comment by julienduroure** [comment] 2024-03-13 14:07
Hello,
I can't reproduce, trying to display the exported glTF in:

- https://sandbox.babylonjs.com/
- https://gltf-viewer.donmccurdy.com/
- Import it back on Blender
- Godot Engine
- Windows 10 viewer

May I suggest the problem may come from O3DE? You should report it to it.

Closing this ticket

**Closed by julienduroure** 2024-03-13 14:07 UTC

**Comment by kursad-k** [comment] 2024-03-13 16:05
Thanks for testing it. I was not sure where the problem was originating from it. I will investigate it from that end.
