### ISSUE TITLE
Add Leaf Bones check on Export in Blender

### ISSUE THREAD

**Issue by DigitalN8m4r3** [KhronosGroup/glTF-Blender-IO#1705] opened 2022-08-08 12:03 UTC
**Is your feature request related to a problem? Please describe.**
Using leaf bones would improve the physics hand in Godot VR/XR and ease the process of a full body vr system for godot vr/xr

**Describe the solution you'd like**
The Option in Blender for a so called Add Leaf Bones on export of the .gltf
the attached Screenshots show how this looks when exporting it as .fbx, since blenders .fbx export conatins a optional add leaf bones check.

**Describe alternatives you've considered**
An alternative is to export the Model as .fbx and import the exported .fbx back into blender (since the .fbx format supports the option of Add Leaf Bones), once the model is imported into blender it will have those end bones.
Now exporting it as .gltf and the needed end bones are there.

**Additional context**

![grafik](https://user-images.githubusercontent.com/56046022/183413150-27988aba-11ab-4a92-b376-60308b2de5a3.png)

![grafik](https://user-images.githubusercontent.com/56046022/183413217-55869dc4-bf3f-41a7-bade-c01d9d02f5ff.png)

**Comment by julienduroure** [comment] 2022-08-08 13:50
This is a duplicate of #1261

**Comment by DigitalN8m4r3** [comment] 2022-08-08 13:51
ooh i was not aware of this, my appologies

**Comment by julienduroure** [comment] 2024-08-30 04:41
This is now fixed

**Closed by julienduroure** 2024-08-30 04:41 UTC
Labels: duplicate, enhancement, exporter, Skinning_&_Rigging
