### ISSUE TITLE
camera animation support with constraints

### ISSUE THREAD

**Issue by AndrewPrifer** [KhronosGroup/glTF-Blender-IO#731] opened 2019-10-12 22:39 UTC
**Is your feature request related to a problem? Please describe.**
When an object is animated through a follow path constraint, I have to bake it manually for the animation to export. I'm not the first to have filed this issue, the old repo already had an issue filed for it (https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/44). These animations don't export whether or not "Always sample animations" is enabled.

**Describe the solution you'd like**
I'd like the glTF exporter to automatically bake these animations.

**Describe alternatives you've considered**
I can't think of any that's more convenient than checking a checkbox in the exporter.

**Comment by julienduroure** [comment] 2019-10-13 05:19
This is a duplicate of #481

**Closed** 2021-02-24 05:41 UTC
Labels: Animation, duplicate, enhancement
