### ISSUE TITLE
glTF export fails for armatures with animation if armature resides in a collection shared by a linked copy scene

### ISSUE THREAD

**Issue by imphenzia** [KhronosGroup/glTF-Blender-IO#1561] opened 2022-02-07 00:46 UTC
**Describe the bug**

**To Reproduce**
1. Start Blender 3.0.1
2. Top Right Corner, click right to "Scene" and click the "New Scene" icon and select Linked Copy
3. Scene.001 should now also exist in addition to Scene
4. Delete the default cube (sorry)
5. Shift A - Add new Armature
6. Select Armature and Ctrl + Tab into Pose Mode
6. Go to Animation Tab
7. Change from DopeSheet to Action Editor
8. Click on New Action
9. Insert a Location & Rotation keyframe for the armature bone
10. Ctrl + Tab out of Pose Mode
11. File > Export > glTF 2
12. Enter a file name, and tick Includer > Selected Objects (ensure the armature is selected still)
13. Export > Error Message:
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\io_scene_gltf2\__init__.py", line 637, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 46, in save
    json, buffer = __export(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 71, in __export
    json = __fix_json(exporter.glTF.to_dict())
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 1189, in to_dict
    result["animations"] = from_union([lambda x: from_list(lambda x: to_class(Animation, x), x), from_none],
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 56, in from_union
    assert False
AssertionError

location: <unknown location>:-1

**Expected behavior**
The Armature should be exported with animation. This is the behavior for FBX exports for example.

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://www.dropbox.com/s/459f9u28cbp6gei/glTF-bug.PNG?dl=0)

**.blend file/ .gltf**
https://www.dropbox.com/s/3b9tiqf883rjr4j/glTF-ArmatureCollectionBugRepro.zip?dl=0

**Version**
 - OS: Windows 10
 - Blender Version 3.01 (and 2.93, 3.0)

**Additional context**
After doing the repro steps above, moving the armature out of the collection to the root (or another, non-linked collection) results in a successful export.

**Comment by julienduroure** [comment] 2022-02-07 05:15
Duplicate of #639 
Will be fixed in #1378 planned for 3.2

**Comment by julienduroure** [comment] 2022-03-02 20:45
Fixed by 69746b2b31eeee080d5dfd3c74f1e02742795ed2

**Closed by julienduroure** 2022-03-02 20:45 UTC
Labels: duplicate
