### ISSUE TITLE
Exported animations do not match Blender [gltf]

### ISSUE THREAD

**Issue by RockyMadio** [KhronosGroup/glTF-Blender-IO#1613] opened 2022-04-03 14:00 UTC
**Describe the bug**
Exported animations do not match Blender.

Detected with @fire

**To Reproduce**
1. Open Blendfile - Export gltf (selected objects) 
2. Open this gltf in Blender again
3. See error

**Expected behavior**
Everything should match

**Screenshots**
Source
![source](https://user-images.githubusercontent.com/11413664/161431334-f1db13a1-3e6c-42ae-8460-0ae5406ed591.PNG)
Result
![result](https://user-images.githubusercontent.com/11413664/161431333-6c0e131e-1f38-408a-8d0b-9e6ccbb00d3a.PNG)

**.blend file/ .gltf**
[files.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/8404652/files.zip)
Do not use this animation out of the bug report.

Property of [ElefantastiqueGames](https://twitter.com/ElefantastiqueG)

**Version**
 - Blender 3.2.0 Alpha (April,2, 2022)  and Blender 3.0.1

**Comment by julienduroure** [comment] 2022-04-03 15:47
What exactly is wrong in exported animation?

I re-import my exports (in attachment), and I can't see any difference with original animation.
file:///tmp/this_seems_ok.zip

I can see that the glTF file you attached is buggy, so maybe you used a non default option during export?

**Comment by fire** [comment] 2022-04-03 16:38
Activating the star causes the bug. 

![Screenshot from 2022-04-03 09-37-59](https://user-images.githubusercontent.com/32321/161438388-fb1f5843-881a-4977-a02e-fbcbc4d1f23e.png)

**Comment by julienduroure** [comment] 2022-04-03 17:09
Ok, I think I found the root cause.
Problem is not the STAR.
Some bones have constant animation (I mean always the same keyframe). By default, the exporter delete this animation on these bones.
If you uncheck the option "Optimize Animation Size", seems everything is OK.

Maybe time to think about unchecking this option by default ...

**Comment by RockyMadio** [comment] 2022-04-03 17:11
> Ok, I think I found the root cause. Problem is not the STAR. Some bones have constant animation (I mean always the same keyframe). By default, the exporter delete this animation on these bones. If you uncheck the option "Optimize Animation Size", seems everything is OK.
> 
> Maybe time to think about unchecking this option by default ...

I am glad you found the solution. Thank you very much!
Also, we somehow found out that "selected objects only" in the export menu doesnt seem to work correctly, according to @fire

**Comment by julienduroure** [comment] 2022-04-03 17:14
> Also, we somehow found out that "selected objects only" in the export menu doesnt seem to work correctly, according to @fire

Don't hesitate to open a new ticket if you have something reproducible about that. (and don't forget to test on 3.2 alpha only, because of a big refactoring between 3.1 and 3.2)

**Comment by fire** [comment] 2022-04-03 17:28
As far as I know, the "selected objects only" is fixed on 3.2 alpha.

**Comment by fire** [comment] 2022-04-03 17:32
@julienduroure I propose that the default always work. That means "Optimize Animation Size" is not safe. We may be able to fix the algorithm later. Like special case for constant tracks but that requires qa validation..

**Comment by julienduroure** [comment] 2022-04-03 19:21
> As far as I know, the "selected objects only" is fixed on 3.2 alpha.

Good to know :)

> Maybe time to think about unchecking this option by default ...

I just push. Option is now off by default. Closing this ticket

**Closed by julienduroure** 2022-04-03 19:21 UTC
