### ISSUE TITLE
Unable to export gltf.

### ISSUE THREAD

**Issue by tiancaipipi110** [KhronosGroup/glTF-Blender-IO#505] opened 2019-05-29 18:21 UTC
Hi, this model <a href="https://drive.google.com/open?id=10aZzi6RfDbDCYD-UloraL3SNOriVX9qT">Donut</a> copyright Jun Wang, with multiple actions, is unable to be exported .gltf with Blender 2.8. 

However <a href="https://github.com/KhronosGroup/glTF-Blender-Exporter"> gltfBlExporter</a>, <a href="https://github.com/Kupoman/blendergltf">blenderGltf</a>, are both able to export ONE animation correctly. When push down the actions, mesh will be distorted, and ONE animation will be lost.

**Comment by julienduroure** [comment] 2019-05-29 19:06
This is a duplicate of #461 

+ some other minor

**Comment by tiancaipipi110** [comment] 2019-05-30 01:48
> This is a duplicate of #461
> 
> plus some other minor issue
Alright will bake them till fixed.

**Comment by julienduroure** [comment] 2019-06-01 09:25
Seems the filr on google drive is no more accessible, so I can't test again, but the problem should be solved

**Closed by julienduroure** 2019-06-01 09:26 UTC
Labels: Animation, duplicate, exporter

**Comment by tiancaipipi110** [comment] 2019-07-05 14:10
> Seems the file on google drive is no more accessible, so I can't test again, but the problem should be solved

Unfortunately not, still the same.
