### ISSUE TITLE
Multiple tracks on armature no work independentely in .gltf ? 

### ISSUE THREAD

**Issue by headwindmsfs** [KhronosGroup/glTF-Blender-IO#1531] opened 2022-01-09 00:25 UTC
Hello,

### Describe the bug

I have made an armature, on this armature i have added 3 animations tracks. 
In blender, the 3 tracks work independently: you can disable or play one of the animations.
However, after exporting in .GLTF the 3 tracks wont work independently. If you enable one animation, all animations are played.

### Exemple

Open the .gtlf on https://gltf-viewer.donmccurdy.com/ and try yo disable only one animation : no work, all animations keep played.

.blend : [blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/7835020/blend.zip)
.gltf + .bin : [exported.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/7834987/exported.zip)

### Screenshots

3 tracks in blender
![image](https://user-images.githubusercontent.com/95131493/148681716-4c7fa517-5f29-40b2-84ee-477799183bef.png)

but i can't start or stop one tracks. the red encircled mesh are again animated whereas the checkbox are unchecked:
![image](https://user-images.githubusercontent.com/95131493/148681701-6e6615a9-722c-4466-bbf9-2e7d4fed20cd.png)

### Version

OS: Windows 10
Blender Version 2.93.2

### Context
Creating aircraft for microsoft flight simulator 

Thank you,
Thomas

**Comment by julienduroure** [comment] 2022-01-09 07:48
Hello,
As requested in the ticket template, can you please provide a blend file to be able to reproduce, and indicate what version of Blender you are using.

If there are 2 actions in the viewer, these actions are independents, so I am not sure to get what you said.

Thanks !

**Comment by julienduroure** [comment] 2022-01-09 11:19
Maybe a duplicate of #1386 ?

**Comment by headwindmsfs** [comment] 2022-01-09 12:25
> Hello, As requested in the ticket template, can you please provide a blend file to be able to reproduce, and indicate what version of Blender you are using.

Hello Julien, 
Sorry, i have updated the issue from the template and added .blend/.gltf file.

> If there are 2 actions in the viewer, these actions are independents, so I am not sure to get what you said.

Yes, This is what I should have but the behavior seems different.

> Maybe a duplicate of #1386 ?

Seem different, he use multiple armatures, me only one :-) . 

Thank you,
Thomas

**Comment by julienduroure** [comment] 2022-01-10 10:47
I confirm that this is a duplicate of#1386

All bones are not keyed in each action, so, because there is no default pose values, value of previous action is kept.
Discussion about a solution will be on #1047 

Workaround : Key all your bone on every action

**Comment by headwindmsfs** [comment] 2022-01-10 10:58
Ok, thank you ! 

I have found a working workaround : uncheck this before exporting and all work in game : 

![image](https://user-images.githubusercontent.com/95131493/148754960-4d8ce1ea-9c3c-4d17-8c3d-4ad28e636df9.png)

Maybe i can close this issue if duplicated ?

**Comment by julienduroure** [comment] 2022-01-10 12:02
Yes, sure, let's close this one

**Closed by julienduroure** 2022-01-10 12:02 UTC
Labels: duplicate, exporter, Animation
