### ISSUE TITLE
Import camera fov

### ISSUE THREAD

**Issue by pixue** [KhronosGroup/glTF-Blender-IO#1001] opened 2020-03-27 01:16 UTC
All fov of cameras imported from gltf/glb files are lost.

**To Reproduce**
1. Import a gltf or glb with cameras defined.
2. All camera fov-s are lost
![Blender282a](https://user-images.githubusercontent.com/1937898/77709562-cc02c800-6fcb-11ea-8610-7800c9c18dd4.png)

**Expected behavior**
Camera fov defined (or its equivalent in mm), not default focal length of 50mm.

**Test files gltf&glb**
[Test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4390830/Test.zip)

**Version**
 - OS: Windows 10
 - Blender Version 2.82a

**Additional context**
Test files are created using ThreeJS editor, adding some cameras and customizing their fov. Then I export to gltf and glb.
![Captura](https://user-images.githubusercontent.com/1937898/77711091-403f6a80-6fd0-11ea-8455-7e72f39e422b.png)
I see that the fov is stored in the definition of each camera inside the cameras array of gltf file.

**Comment by VForsmann** [comment] 2020-04-20 08:41
I have the same problem. The camera in the gltf has a yFOV value, which is calculated down to the default FocalLength of 50mm after importing the gltf.

Blender: blender2.83a
System: Linux Mint 19.3 Cinnamon (4.4.8)

I am also using a GLTF-File exported from three.js using the [GLTFExporter](https://threejs.org/docs/#examples/en/exporters/GLTFExporter).

The result as part of a JSON looks like this:
![image](https://user-images.githubusercontent.com/40580801/79731473-9b742c80-82f2-11ea-8e2c-566d7c106b91.png)

In Blender I can find the camera, but not with yFOV but with a default FocalLength of 50mm (~ 40 degrees fov):
![image](https://user-images.githubusercontent.com/40580801/79731923-42f15f00-82f3-11ea-96a3-2dab4ff03eed.png)
![image](https://user-images.githubusercontent.com/40580801/79732008-5b617980-82f3-11ea-97e1-f5aec5c1e7a4.png)

**Comment by SakuPartamies** [comment] 2020-04-22 10:24
I can confirm the issue as well. The camera is imported as default 50mm, which is not correct. I have made a three.js WebGL scene and exported is as glTF. In Blender camera FOV is not imported.

Below is an image to present the issue. I can manually change the camera lens to Focal Length and convert the FOV value in glTF file to degrees to type in Blender. That will correct the problem, but this should be automatically done by the importer.

**Software:**
**Windows 10:** 10.0.18363
**Chrome:**  80.0.3987.163 (64bit)
**Blender:** 2.81
**Import-Export:** glTF 2.0 (v. 1.0.5)

![gltf_blender_camera-FOV_problem](https://user-images.githubusercontent.com/63749481/79970962-60156180-849c-11ea-963f-0666ca4db5ab.jpg)

**Comment by VForsmann** [comment] 2020-04-22 10:33
Hey,

I could find out, that they already fixed it, but its not released in the newest Blender I guess.

So to workaround this clone this git repo, and copy the glTF-Blender-IO/addons/io_scene_gltf2 folder to replace your local blender/x.xx/scripts/addons/io_scene_gltf2 folder.

For me this worked, you can find the camera fix in io_scene_gltf2/blender/imp/gltf2_blender_camera.py where you can find the added:

```
cam.angle_y = pycamera.perspective.yfov
cam.lens_unit = "FOV"
cam.sensor_fit = "VERTICAL"
```

Hope I could help out :)

**Comment by SakuPartamies** [comment] 2020-04-22 11:51
Yes, you are right. It is in 2.83 branch like you mentioned and at least import was working correct in my Blender 2.81. Other branches didn't have that change as I checked.

Thanks.

**Closed** 2020-04-22 12:35 UTC

**Comment by pixue** [comment] 2020-04-22 12:36
Hello, 
I just tried it and it seems to have the expected behavior.  
Thank you!
