### ISSUE TITLE
An empty node is added for any armature at export

### ISSUE THREAD

**Issue by mikejsavage** [KhronosGroup/glTF-Blender-IO#511] opened 2019-05-31 14:59 UTC
**Describe the bug**
If you export and reimport any model it adds a new armature to the hierarchy

Additionally with [bigvic.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3241743/bigvic.zip) it deletes the animations

**Expected behavior**
Exporting and reimporting should give the original model without extra armatures or deleting the animations

**Version**
 - OS: Linux
 - Blender Version 2.80.190527.89207df7222a

**Comment by julienduroure** [comment] 2019-05-31 15:11
Hello,
Please provide a .blend file to be able to reproduce exporting then importing.
I can't reproduce for now, there is no second armature added.

About "delete the animations" : When ? In glb exported, or after re-importing?

**Comment by mikejsavage** [comment] 2019-05-31 16:09
Sorry, I don't know blender terminology too well. I've made some videos:

https://streamable.com/eaeh4 - I import/export/reimport the model and you can see in the top right it has added an extra armature to the model
https://streamable.com/s9v4t - I import/export/reimport the model and it no longer animates

Here is a zip of the glbs: [models.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3241994/models.zip)

**Comment by julienduroure** [comment] 2019-05-31 16:38
Hello,
This is not adding an another armature, but an empty named "Armature".
I don't have the history why the armature is not directly linked to the parent, but I will check it.
This is how it is working at export for now. Setting as enhancement, as there is no visible error in mesh / rig / animation

**Comment by mikejsavage** [comment] 2019-05-31 17:53
Should I file a separate issue for the second video? Missing the animations is not just a cosmetic issue

**Comment by julienduroure** [comment] 2019-05-31 18:25
@mikejsavage. Sorry, I missed this second part of the report. It seems to be an importer issue, because it seems to be OK with external glb viewer.
SO yes, please fill another issue with importer issue.

Thanks for your help :)

**Comment by scurest** [comment] 2020-07-27 14:51
The video was deleted. Is the issue talking about the extra Empty named "Armature" shown in the image in [this comment](https://github.com/KhronosGroup/glTF-Blender-IO/pull/857#issuecomment-571925025)? If so, this has been fixed.

**Comment by mikejsavage** [comment] 2020-07-27 15:03
To be honest I don't remember.

Your fixes should be in the newest blender right? I will poke around again and see if anything strange happens.

**Comment by scurest** [comment] 2020-07-27 15:08
That'd be cool, thanks! Yeah, that change should be in since 2.83.

**Comment by mikejsavage** [comment] 2020-07-27 23:02
Not seeing any issues this time around, thanks

**Comment by scurest** [comment] 2020-07-28 01:26
Awesome.

@donmccurdy Can you close this one too please? (Thanks for closing them.)

**Closed** 2020-07-28 02:28 UTC
Labels: Skinning_&_Rigging, enhancement, exporter
