### ISSUE TITLE
Import supports KTX

### ISSUE THREAD

**Issue by Jeggery** [KhronosGroup/glTF-Blender-IO#2282] opened 2024-07-15 09:33 UTC
GLB files with compressed textures cannot be imported.

![image](https://github.com/user-attachments/assets/dfeb36c4-59fb-4c2d-9cf8-8dfdefa88f7b)

Hope to support this feature, The texture compression inside uses KTX

**Comment by julienduroure** [comment] 2024-07-15 12:35
Hello,
Closing this ticket, as a duplicate of #1896

**Closed by julienduroure** 2024-07-15 12:35 UTC
