### ISSUE TITLE
needs_neutral_bone: please provide more information

### ISSUE THREAD

**Issue by manavortex** [KhronosGroup/glTF-Blender-IO#2070] opened 2023-12-03 22:52 UTC
**Is your feature request related to a problem? Please describe.**
When importing into Cyberpunk, the .glb file must not have any bones that aren't present in the target mesh, or the tooling won't allow the import. The glb exporter's habit of assigning a neutral bone without telling me where it comes from (e.g. which vertices I need to fix or which groups are invalid) is a pretty big impediment on the way there. 

**Describe the solution you'd like**
Since there are never unassigned vertices in any glb export (also prevented by tooling), please provide information about which vertex groups are invalid or can't be mapped to armature bones. Printing them to console is perfectly fine for me.

**Describe alternatives you've considered**
I've poked around in the code. By throwing an exception, I could at least find out which meshes were affected, but I have no idea how to get the group names assigned to the currently-active vertex. I'd also take a code snippet that I can throw into the current plugin's file.

**Comment by julienduroure** [comment] 2023-12-04 07:18
In Blender, you can have some vertices not assigned to any Skin Vertex Groups.
In glTF, you can't. 
So the exporter creates an additional joint (bone), the "neutral bone", and the corresponding Vertex Group weights to this joint.

I better suggest you to fix your model by selecting all your not assigned vertices to any vertex group instead of trying to tweak the glTF exporter. This is the best way to get an glTF exported without this neutral bone

**Comment by manavortex** [comment] 2023-12-04 07:22
> I better suggest you to fix your model by selecting all your not assigned vertices to any vertex group instead of trying to tweak the glTF exporter.

Here's the problem, that's what I did. Selecting un-grouped vertices gives me nothing, and I don't know which of them to even look at. Hence my request to provide extra information.

**Comment by julienduroure** [comment] 2023-12-04 07:56
As requested, please provide the .blend file, I can't investigate without it

**Comment by manavortex** [comment] 2023-12-04 08:12
[kimono_pwa.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/13543461/kimono_pwa.blend.zip)

Thank you for looking into this. I had hoped for a more long-term solution, but I really appreciate your help.

**Comment by julienduroure** [comment] 2023-12-04 08:34
You have some vertex (at least 1, didn't check) that is assigned to multiples bones, but all with 0 weights (so is equivalent to have not assigned weights)

![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1696020/229c3b56-e736-46db-b7de-e34e03d795c6)


Don't think we can display all data that are in that case, it can be very verbose in the console.
I suggest to display only the first vertex index found:
![image](https://github.com/KhronosGroup/glTF-Blender-IO/assets/1696020/155b1f58-0780-4a3e-b84c-9a0f5dfcbe3e)

**Comment by julienduroure** [comment] 2023-12-05 18:57
If you are able to run scripts, I think the best way is to prevent it before export.
You can check index using this script

```
import bpy

groups = {}

object = bpy.context.object

for vertex in object.data.vertices:
    if not vertex.groups:
        groups[vertex.index] = [0]
    for g in vertex.groups:
        groups.setdefault(vertex.index,[]).append(g.weight)
            
print([k for (k,v) in groups.items() if sum(v) == 0])
```

**Comment by julienduroure** [comment] 2023-12-06 07:26
Closing this ticket, as there is no bug here.
Some workaround and way to detect issue in the model was provided

**Closed by julienduroure** 2023-12-06 07:26 UTC

**Comment by ford-jones** [comment] 2026-06-26 05:27
Hi @julienduroure 
This all makes sense to me and I understand that this is an intended behavior.

One request, though: It's my understanding that the index of a `"neutral_bone"` is included inside of the `skins.joints` property and has an accompanying `inverseBindMatrix` generated for it, just like any other bone. Could some zeroed out keyframe data also be included for it too? 

I've written a glb parser and it runs into issues with `"neutral_bone"`'s as their presence changes the total size of the armature in a way that isn't reflected in the timesteps/keyframes, leading to out-of-range exceptions while doing keyframe lookups during parsing if `"neutral bones"`s aren't explicitly guarded against. 

Alternatively / additionally: would it be possible to add a warning on export for rigged meshes which contains unweighted vertexes?

EDIT: I just saw you posted a screenshot of a terminal warning for the issue previously. Would it be possible to create a GUI element for this?

If this makes sense to you and sounds like something worth pursuing; I would be happy to submit a new issue for this and could even try resolving it myself too 👍
