### ISSUE TITLE
High res textures as height for bump node cause massive freeze

### ISSUE THREAD

**Issue by Justin113D** [KhronosGroup/glTF-Blender-IO#790] opened 2019-11-23 14:37 UTC
**Description**
When having a material with a bump node, which takes a high resolution texture as input (in my tests they were 8k textures) and exporting as gltf 2.0, the (or at least my) PC slowly hangs up and almost crashes. I thought it might be my CPU. which couldn't keep up with the exporter, so i tried to let it sit for some time, with no results (at one point i have waited 90 minutes), but it might also be that the RAM isn't sufficient (when looking at blender in the task manager, its RAM use raises from ~500mb to almost 5gb, where it stops and freezes the whole computer, and even closes other programs).
This problem can be prevented by disabling "Material" under "Geometry" in the export setting, but it would still be great if this problem didnt exist in the first place.

**How to reproduce**
1. Create any type of 3D mesh object, and add a material
2. Create a bump node, and connect it to the normal input of the principled node
3. Create a new texture in the image panel with a high resolution (i tested with 8192x)
4. create an image texture node, select the newly created image, and connect it with the 'height' slot of the bump node
5. export the scene as gltf (with materials)
**CAUTION: This might lead your PC to freeze for half an hour or longer!**

**Expected behavior**
The Exporter creates the primitives of the mesh with the material (see console output) and then freezes. The RAM usage of blender raises tremendously, until the whole computer freezes.

**Version**
 - OS: Windows 10, Version 1903
 - Blender Version 2.80 / 2.81

My CPU is an Intel Ceon E3-1231 v3, and i have 8GB RAM, if those stats matter.

**Comment by julienduroure** [comment] 2019-11-23 14:48
Duplicate of #203 

Please follow submission template and provide an example .blend file, it will save a few minutes for developer that will investigate it.
Thanks!

**Closed** 2020-01-02 20:16 UTC
Labels: Material, duplicate, exporter
