### ISSUE TITLE
Objects in scene jump around on export

### ISSUE THREAD

**Issue by hybridherbst** [KhronosGroup/glTF-Blender-IO#2041] opened 2023-11-02 21:32 UTC
**Describe the bug**
When exporting a glb, some objects in the scene jump to different positions and then stay in those incorrect positions.

**To Reproduce**
1. Download [boneStudy2.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/13244735/boneStudy2.zip)
2. Import in Blender 4.x
3. Export as glb
4. Note scene objects jump around

**Expected behavior**
Scene shouldn't change just because I'm exporting a model.

**Screenshots**

https://github.com/KhronosGroup/glTF-Blender-IO/assets/2693840/5df04e58-2c26-4d12-8f0e-0aca80fb3ba8

**.blend file/ .gltf**
[boneStudy2.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/13244735/boneStudy2.zip)

**Version**
 - OS: Windows11
 - Blender Version 4.0.0 beta

**Comment by hybridherbst** [comment] 2023-11-02 21:54
Seems I'm able to work around the issue by saving the scene and restarting Blender from time to time. Glad I made a video, please let me know if you can reproduce / know what might be going on :)

**Comment by julienduroure** [comment] 2023-11-03 06:07
Unfortunately, I am not able to reproduce for now :(
Next time you get it, can you make a copy of your file that contains the issue, and share it?

**Comment by hybridherbst** [comment] 2023-11-03 07:52
I'll try – however, this file I attached _is_ the exact file that had the issue, after I reported it the issue went away by restarting Blender.

**Comment by julienduroure** [comment] 2023-12-06 07:27
More that a month without any news. Closing this ticket.
Of course, we will re-open it again if someone get lucky enough to reproduce it.

**Closed by julienduroure** 2023-12-06 07:27 UTC
Labels: question

**Comment by hybridherbst** [comment] 2023-12-06 10:45
Yeah, sorry, the behaviour was very erratic and I wasn't able to find 100% repro steps. It does happen when just working on complex nested skinned mesh structures occassionally though.
