### ISSUE TITLE
Animation seems to always use frame_start = 0

### ISSUE THREAD

**Issue by Vinc3r** [KhronosGroup/glTF-Blender-IO#387] opened 2019-03-27 15:24 UTC
[A BabylonJS user was confronted to an issue](https://forum.babylonjs.com/t/blender-to-gltf-walk-cycle-animation-shortly-pauses-in-the-beginning/2179/6?u=vinc3r), not specific of BabylonJS, and found that the issue came from difference between Blender default starting frame (1) and what seems to be the default gltf export starting frame (0).

So I've made a few checks and it seems custom starting frame is indeed not take into account.
Here a simple Blender animation starting from 5 to 25, the animation loop without break:
![img](https://i.imgur.com/rT4E0ZC.gif)
Here the glb export (into BabylonJS Sandbox) where we can see a break into the animation, which seems to be ghost frames from 0 to 5:
![img](https://i.imgur.com/JrZ7Oue.gif)

It's maybe a gltf standard limitation for animations to start at frame = 0, if so I think it deserves to be mentionned in the Blender Manual.

**Comment by mauricedoepke** [comment] 2019-03-27 15:31
There is actually an option to deal with that in the export settings. The tab animations contains the option "Limit to playback range", which is true by default. Searching through the code, it seems like the functionality for this option is not implemented yet.

**Comment by Vinc3r** [comment] 2019-03-27 15:33
ok! (I've forgot to mention I've play with some exporter options too), thanks for the clarify.
So wait&see :)

**Comment by emackey** [comment] 2019-03-29 15:00
> The tab animations contains the option "Limit to playback range", which is true by default. Searching through the code, it seems like the functionality for this option is not implemented yet.

If we have an un-implemented option still in the mix at this point, that's a bug.  We should yank the option out, at least until someone has time to write the supporting code.

**Comment by MiikaH** [comment] 2019-04-16 14:44
I also ran into this issue when trying to export low FPS looping scene. There was a noticeable freeze in the exported animation because of this issue.

Here is a very minimal .blend file to better see and test the issue:
[2_point_loop_anim_blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3085372/2_point_loop_anim_blend.zip)

It is a 3 frame scene played back at 1 fps that loops a cube back and forth with linear interpolation.
![anim_range](https://user-images.githubusercontent.com/1881360/56219235-11561000-606f-11e9-9131-5ba94eebe208.png)

When exported with the old Blender 2.79 gltf exporter that has the "keyframes start at 0" option enabled by default, the exported file loops flawlessly without any gaps. GlTF-Blender-IO export however has the animation frozen for first 1 second of the loop.

This happens because first exported sampler keyframe is placed at timestamp matching frame 1 (exported keyframe times are [1,2,3] when they should be [0,1,2]). It produces a frozen duration equal of 1 frame because glTF spec states that sampler times are to be considered relative to time=0 and clamped if first keyframe is later than that.

**Comment by donmccurdy** [comment] 2019-06-18 23:37
Marking this as a bug rather than an enhancement - and confirmed the example above does work if the keyframes are shifted back to 0–2. Since animations start at 1 by default in Blender, we should fix this to ensure exports loop cleanly.

**Comment by schroef** [comment] 2019-12-29 00:30
Looking into the code the range is set by bake_range_start and bake_range_end.

**Comment by FaradayNova** [comment] 2020-09-19 02:23
Has this bug been resolved yet??
Running into this issue and the option is still available in 2.9

**Comment by obviousscholar** [comment] 2020-12-02 00:46
Would be nice to get this looked at: NLA tracks with a defined `Frame Start` and `End` aren't clipped at all, as far as I can tell. That's a big problem for even something as simple as a walk cycle, where offsetting frames (for naturalness' sake) leads to negative keyframes and keyframes after the animation's end and a baked range for the animation to loop right.

**Comment by HumanRobot3D** [comment] 2021-01-12 12:11
Hi, big +1 for a fix on this please.

**Comment by BlomenJoel** [comment] 2022-01-03 10:57
+1!

**Comment by schroef** [comment] 2022-01-03 17:41
I have not checked the code in a while, i actually never use this addon. Would an easy fix be to use current_frame vs start_frame. Im not 100% sure though that start_frame is always 0 or if start_frame is always the start IN of the timeline.

On the other hand
![Screen Shot 2022-01-03 at 13 40 07](https://user-images.githubusercontent.com/6923008/147961986-f0323e8c-4dfb-486e-981d-586145df9e5e.png)
![Screen Shot 2022-01-03 at 13 31 40](https://user-images.githubusercontent.com/6923008/147961989-10f0d7f8-f0ba-4113-ba56-cf232bdc702c.png)
. perhaps the option "limit to Playback Range" fix this issue. Though normally this means the end of the animation.

Could be also updated by adding start and end frame like other exporters have

**Comment by schroef** [comment] 2022-01-03 18:34
I think the issue with this goes deeper and is more challenging. It seems the addon export complete actions and NLA strips. Therefor it doesnt check the main timeline and thus i wonder if this current_frame and use playback range even have any use. The Limit playback Range doesnt do anything, im also seeing the "Current Frame" does do anything

**Comment by Phrogz** [comment] 2022-07-14 22:39
IMHO this could be fixed (perhaps inelegantly) by simply subtracting the "Frame Start" value from every keyframe's frame number when calculating the keyframe's glTF time.

**Comment by julienduroure** [comment] 2023-02-26 10:06
Hello,
This is now fixed in current main branch, after animation refactor 64e3532f48ebdf878a1c9b81ade6d1a19c8ff890

There is now an option ("Set all glTF animation starting at 0") that shift animations to start at 0 during export. This way, animations can be looped smoothly

**Closed by julienduroure** 2023-02-26 10:06 UTC
Labels: bug, exporter, Animation
