### ISSUE TITLE
Parent to Bone not being exported as expected

### ISSUE THREAD

**Issue by Zalez95** [KhronosGroup/glTF-Blender-IO#907] opened 2020-02-02 12:02 UTC
**Describe the bug**
I created a blend file that has an armature and some meshes attached to it with the "Parent to Bone" type of parenting. When I export that 3D model with the last version of glTF-Blender-IO (2.81) the result isn't the expected. It seems like the meshes appear with some offset applied to them:

![minimal](https://user-images.githubusercontent.com/12982523/73607828-8b826180-45bb-11ea-8e09-8cd314429e71.png)

**To Reproduce**

    Open the attached file
    Export to gltf.
    Open the gltf file

**.blend file/ .gltf**
[nodetest3.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4144089/nodetest3.zip)

**Version**
    OS: Windows 10
    Blender Version 2.81a

**Comment by julienduroure** [comment] 2020-02-03 07:26
Confirmed. I will check

**Comment by julienduroure** [comment] 2020-02-04 14:55
Maybe linked to "Bone Relative" parenting.
I can't reproduce using "Bone" parenting, but I got some weird results with "Bone Relative".
Investigation in progress ...

**Comment by julienduroure** [comment] 2020-02-06 13:01
Dev note:
bpy.context.object.data.edit_bones['Bone'].use_relative_parent in edit mode to retrieve if user used Bone Parenting or Bone Relative Parenting

**Comment by ProgSys** [comment] 2020-06-16 21:51
I have the same Problem with "Parent to Bone". The rotation seams to break, in my test scene for example the sphere was rotated 90 degree:
![boneParentBug](https://user-images.githubusercontent.com/4257741/84831711-1d9b7b80-b02c-11ea-8f83-a922c9d05972.png)

**.blend file/ .gltf**
[boneParentBug.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4789255/boneParentBug.zip)

**Version**
OS: Windows 10
Blender Version 2.83

**Comment by julienduroure** [comment] 2022-02-06 07:36
First test case (original post) will be solved in #1378 
Still an issue with boneParentBug

**Comment by julienduroure** [comment] 2022-02-06 08:52
Now both cases will be fixed by #1378

**Comment by julienduroure** [comment] 2022-03-02 20:48
Fixed by 69746b2b31eeee080d5dfd3c74f1e02742795ed2

**Closed by julienduroure** 2022-03-02 20:48 UTC
Labels: bug, exporter, Skinning_&_Rigging
