### ISSUE TITLE
Intensity units when exporting point lights 

### ISSUE THREAD

**Issue by 4DA** [KhronosGroup/glTF-Blender-IO#564] opened 2019-06-24 11:30 UTC
Blender uses watts as units for power of point light sources.
On the other hand, KHR_punctual_lights use lm/sr as light intensity units.

I can see that values from point light power settings are **directly** written to gltf file without watts -> lumen -> candela conversion.

**Comment by donmccurdy** [comment] 2019-06-24 16:52
/cc https://github.com/KhronosGroup/glTF-Blender-IO/issues/24 and https://github.com/KhronosGroup/glTF-Blender-IO/issues/528.

Previously we weren't sure what Blender's units were, but the UI does pretty clearly show watts now anyway...
<img width="277" alt="Screen Shot 2019-06-24 at 9 50 49 AM" src="https://user-images.githubusercontent.com/1848368/60037187-be4b9b00-9665-11e9-9b51-563817bad000.png">

**Comment by 4DA** [comment] 2019-06-24 20:24
As far as I understand Power is *emitted* by light source, not *consumed*, otherwise everything may be even more difficult.

I've done some back-of-the-envolope computation, so here it goes:

```
Kv (683) - maximum spectral luminous efficacy of radiation for photoscopic vision for 555 nm wavelength, that is most perceptually efficient for human vision
Φe - radiant flux [watts]
Φv - luminous flux [lumens]
Iv - luminous intensity [lm/sr or candela]
--
Φv = Kv * Φe
Iv = Φv / 4PI
=>
Lv = Kv * Φe / 4PI
```

https://seblagarde.files.wordpress.com/2015/07/course_notes_moving_frostbite_to_pbr_v32.pdf

**Comment by aguaviva** [comment] 2019-08-01 14:37
Any chance to get this tagged as a bug? The units for the light intensity seems to be wrong.

According to the glTF specs:
1) point and spot lights use luminous intensity in candela (lm/sr), this exporter uses Watts 
2) directional lights use illuminance in lux (lm/m2), this exporter uses "Strength"

the exported units should be as specified in the glTF specs.

**Comment by julienduroure** [comment] 2019-08-01 16:40
Tagged as bug

**Comment by johndrmiller** [comment] 2020-09-29 19:14
Not for nothing, but it took me about three hours of searching to find this thread so that I could find out how to convert watts to lumens because I'm primarily a designer with a limited math background. I'm currently trying to import a gltf into three.js that was exported from blender by another designer.

On one hand, thank you so much for posting those formulas. On the other, is there any idea when the fix for this might be implemented?

Thank you!

**Comment by toji** [comment] 2021-04-16 22:16
*Raises hand ✋*

Add one more developer to the list of "People who sunk multiple hours into figuring out the issue in their code only to learn it was a problem in Blender's export." It would be really great if this could be fixed!

**Comment by donmccurdy** [comment] 2022-01-03 19:24
You can find the current export code here:

https://github.com/KhronosGroup/glTF-Blender-IO/blob/bb488b245f0c83fdd566b43c2c762d469c044326/addons/io_scene_gltf2/blender/exp/gltf2_blender_gather_lights.py#L64-L84

**Comment by j-conrad** [comment] 2022-03-10 23:35
Forgive me if this has already been discussed here or elsewhere, but it's worth noting Blender's manual that explains how the power of lights are calculated. It doesn't seem to be particularly standard with other software since it specifies:

1. Direct (Sun) lights use **Watts _per square meter_**
2. The other light types don't use typical 'electrical Watts'

> 
> The power of sun lights is specified in Watts per square meter. The power of point lights, spot lights, and area lights is specified in Watts. But this is not the electrical Watts that consumer light bulbs are rated at. It is [Radiant Flux or Radiant Power](https://en.wikipedia.org/wiki/Radiant_flux) which is also measured in Watts. It is the energy radiated from the light in the form of visible light.
> 
> If you want to set the power to real world values, you have to convert the wattage of consumer bulbs or LED lights to radiant flux, but it is not a straightforward process. The wattage of bulbs means the electrical power required to power them. LED lights have a “Watt equivalent” which is neither the electrical power they require nor the amount of light they put out. Some consumer lights specify [lumens or luminous flux](https://en.wikipedia.org/wiki/Lumen_(unit)) which is the radiant flux weighted with the wavelengths perceived by the human eye.

It goes on to list a couple handy conversion charts.
[Blender Manual:  The Power of Lights](
https://docs.blender.org/manual/en/dev/render/lights/light_object.html#power-of-lights)

**Comment by atteneder** [comment] 2022-06-13 10:17
@mindinsomnia Thanks for jumping ahead and providing the conversion functions.

Is it a good idea to pick the luminous efficacy of 555nm wavelength light (essentially a green laser) as conversion reference?

The luminous efficacy depends on the type of light (see [examples](https://en.wikipedia.org/wiki/Luminous_efficacy#Photopic_vision)). I'd argue most Blender users try to replicate the sun or consumer lights (LED, halogen or incandescent lights) whose luminous efficacy is a lot lower.

I'm not an expert, but it seems the most physically accurate way would be to defer the luminous efficacy off of the light's color, right? (No idea how to calculate that though; maybe blend 3 defined values based on RGB factors).

**Comment by atteneder** [comment] 2022-06-13 10:22
Also: For directional lights we need to convert W/m² to lux (i.e. lumen/m²), so no need to divide by the area of a sphere, right?

**Comment by donmccurdy** [comment] 2022-10-13 03:15
Further discussion in KhronosGroup/glTF repository —

https://github.com/KhronosGroup/glTF/pull/2214

The conversion does not seem to be correct with just a watts-to-lux formula, unfortunately.

**Comment by donmccurdy** [comment] 2022-10-18 15:12
FYI – @will-ca has opened a PR with a proposed fix in https://github.com/KhronosGroup/glTF-Blender-IO/pull/1760, testing would be welcome! Important to note that when exporting with physically-based units (per the glTF spec) you will almost certainly need to adjust the exposure in your viewer.

The PR does include a second "compatibility" mode that exports a unitless light intensity value. That isn't spec-compliant or physically-based, but seems to be a common workflow and may work out of the box in viewers without exposure controls.

**Closed** 2022-10-21 16:47 UTC
Labels: bug, exporter, Mesh_&_Object

**Comment by DrewImm** [comment] 2023-11-27 22:36
Just downloaded blender the other day and this still seems to be an issue. Blender shipped with 4.0.44

Not sure why this is closed?

**Comment by DrewImm** [comment] 2023-11-27 23:01
Thanks @donmccurdy!! I found the Lighting dropdown and tried Unitless, which seems **way** closer to what I'd expect. Is there documentation on the options?

**Comment by donmccurdy** [comment] 2023-11-28 03:22
Not more than is in the tooltips, at the moment. Short summary:

- **Raw:** Matches previous Blender versions, but probably isn't useful for much beyond that.
- **Standard**: Does exact exports of light intensities with physically-based units. This is the only "correct" option, but there is a catch.... having the correct units doesn't guarantee the same result in two different renderers. Likely you'll need to adjust the exposure in the application viewing the model.
- **Unitless**: Exports lights with unitless values, relative to default exposure. If both Blender and the viewing application are using their default exposure, this is likely to give fairly close results, but it isn't technically correct as a conversion of units, or according to the glTF specification.

To get a perfect reproduction (or as close as you can get, given inherent differences in applications...) I think you would need to also transfer the exposure and tone mapping to the target application, and I don't have a simple answer on how to do that.
