### ISSUE TITLE
constant interpolation ignored in export, scale to zero introduces frame with weird negative scale

### ISSUE THREAD

**Issue by TimKraemer** [KhronosGroup/glTF-Blender-IO#2236] opened 2024-05-17 14:22 UTC
**Describe the bug**
Whenever I try to export this example scene (a cube with a **linear** `translation` animation and a **constant** `scale` animation from `1,1,1` to `0,0,0` at the end) the exporter is giving me two `LINEAR` interpolations:

```gltf
{
	"asset":{
		"generator":"Khronos glTF Blender I/O v4.1.63",
		"version":"2.0"
	},
...
	"animations":[
		{
			"channels":[
				{
					"sampler":0,
					"target":{
						"node":0,
						"path":"translation"
					}
				},
				{
					"sampler":1,
					"target":{
						"node":0,
						"path":"scale"
					}
				}
			],
			"name":"CubeAction",
			"samplers":[
				{
					"input":4,
					"interpolation":"LINEAR",
					"output":5
				},
				{
					"input":4,
					"interpolation":"LINEAR",
					"output":6
				}
			]
		}
	],
...
}

```

when I then manually change the second one to a `STEP` interpolation, it gives me a weird scale for one frame with `x: -1.083`, `y: -1.083`, `z: -1.083` before it scales to zero.

**To Reproduce**

1. Download the example blender file
2. Export as gltf2.0 with Operator Presets (optional export als gltf to see the source)

**Expected behavior**
Ideally **linear** interpolation should get exported as `"interpolation":"LINEAR",` while **constant** interpolation get's exported as `"interpolation":"STEP"` independent from each other.
Since it's easy to write a script to do this manually, the second problem, that one frame leads to a weird scale of `-1.083` should be prevented completely.

**.blend file/ .gltf (mandatory)**
Example blender file and output gltf with already modified STEP interpolation: 
[simple_test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/15351059/simple_test.zip)

**Version**
 - OS: tested Windows 11 and Linux Mint 21.3 
 - Blender Version: 4.1

**Additional context**
related: #2137

**Comment by TimKraemer** [comment] 2024-05-17 14:26
in case someone is interested to replace `"interpolation":"LINEAR"` with `"interpolation":"STEP"` for every scale animation, I'm using this python script to do so:

```python
import json
import sys

def modify_gltf(input_path, output_path):
    # Load the GLTF file
    with open(input_path, 'r') as file:
        gltf = json.load(file)

    # Iterate over the animations
    for animation in gltf.get('animations', []):
        for channel in animation.get('channels', []):
            target = channel.get('target', {})
            # Check if the target path is "scale"
            if target.get('path') == 'scale':
                sampler_index = channel.get('sampler')
                if sampler_index is not None:
                    sampler = animation.get('samplers', [])[sampler_index]
                    # Change the interpolation to "STEP"
                    if sampler:
                        sampler['interpolation'] = 'STEP'

    # Save the modified GLTF file
    with open(output_path, 'w') as file:
        json.dump(gltf, file, indent=2)

    print(f"GLTF file has been modified and saved as '{output_path}'")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python modify_gltf.py <input_path> <output_path>")
    else:
        input_path = sys.argv[1]
        output_path = sys.argv[2]
        modify_gltf(input_path, output_path)
```

**Comment by julienduroure** [comment] 2024-05-18 05:43
Hello,

- You are using "Scene" animation mode, that is a full bake mode, where we can't retrieve interpolation
- In your case, I suggest changing to "Action" for example.
    - If you still disable sampling
       - Some of your scale keyframe are not in CONSTANT interpolation, so sampling will be forced. You should set all your keyframe in CONSTANT mode, so export will use STEP
    - If you enable sampling, same thing. Correct STEP retrieving will need correct interpolation for each keyframe of your fcurve, so be sure that all keyframes are in CONSTANT. This is not the case for now


- Seems I can't reproduce your issue with negative scale when changing to STEP

**Comment by julienduroure** [comment] 2024-06-18 02:49
More than a month without any answer, closing this ticket.
Feel free to comment and provide the .blend file if you want me to have a look

**Closed by julienduroure** 2024-06-18 02:49 UTC
Labels: question
