### ISSUE TITLE
Apply Modifier seems to have effect on "Auto Smooth" of the final GLB Exported

### ISSUE THREAD

**Issue by enzyme69** [KhronosGroup/glTF-Blender-IO#799] opened 2019-11-25 01:37 UTC
**Describe the bug**
Related to Auto Smooth,  

**To Reproduce**
Have a 3D mesh that takes advantage of Auto Smooth, then when exporting GLB, turn on Apply Modifier and see the Auto Smooth seems unchecked on all other mesh(s)! Surprised.

**Expected behavior**
Expecting Apply Modifier to have no effect whatsoever on the Auto Smooth of other objects in the scene.

**Screenshots**
<img width="1079" alt="Screen Shot 2019-11-25 at 12 33 46 pm" src="https://user-images.githubusercontent.com/3952687/69505807-dfe7e000-0f7f-11ea-9389-47d6a7dfa9f5.png">
<img width="1080" alt="Screen Shot 2019-11-25 at 12 33 42 pm" src="https://user-images.githubusercontent.com/3952687/69505809-dfe7e000-0f7f-11ea-937a-7c8a9684d795.png">

**.blend file/ .gltf**
[auto_smooth_bug_002.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3884447/auto_smooth_bug_002.blend.zip)

**Version**
 - OS: MacOS Catalina 10.15.2 Beta (19C46a)
 - Blender Version 2.81 official, November 21, 2019

**Additional context**
I found out about this while working on a project BLEND that requires both Apply Modifier, but I am losing a lot of "Auto Smooth" and lots of objects become ... edgy.

**Comment by enzyme69** [comment] 2019-11-25 01:38
As GLB and as well as USDZ, below you can see:
With "Apply Modifier" turned on, somewhat it affects the Auto Smooth (OFF)

<img width="605" alt="Screen Shot 2019-11-25 at 12 37 52 pm" src="https://user-images.githubusercontent.com/3952687/69505923-68ff1700-0f80-11ea-81dd-e672c9947ad2.png">

With "Apply Modifier" turned off, somewhat it affects the Auto Smooth (ON, as expected)
<img width="604" alt="Screen Shot 2019-11-25 at 12 37 40 pm" src="https://user-images.githubusercontent.com/3952687/69505924-68ff1700-0f80-11ea-834f-723b65f3f4db.png">

**Comment by enzyme69** [comment] 2019-11-25 01:42
One more time, more obvious:
* pink object has Solidify Modifier, and I like to Apply Modifier and it is affecting Auto Smooth

<img width="469" alt="Screen Shot 2019-11-25 at 12 41 40 pm" src="https://user-images.githubusercontent.com/3952687/69506052-f3477b00-0f80-11ea-8a19-fac5819fe172.png">


<img width="459" alt="Screen Shot 2019-11-25 at 12 41 26 pm" src="https://user-images.githubusercontent.com/3952687/69506054-f3477b00-0f80-11ea-9ec9-fb4c6d3a3f67.png">

**Comment by enzyme69** [comment] 2019-11-25 01:43
[auto_smooth_bug_003.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3884466/auto_smooth_bug_003.blend.zip)

**Comment by emackey** [comment] 2019-11-25 21:05
Related to #761?  Did you test with that fix included?

**Comment by julienduroure** [comment] 2019-11-26 08:04
Tested on alpha 2.82:
Blender:
![image](https://user-images.githubusercontent.com/1696020/69609705-740e8180-102a-11ea-96de-91698ac59a2b.png)

glb with Apply modifier not checked:
![image](https://user-images.githubusercontent.com/1696020/69609806-acae5b00-102a-11ea-916d-48672dead55a.png)

glb with Apply modifier checked:
![image](https://user-images.githubusercontent.com/1696020/69609877-db2c3600-102a-11ea-812e-dd81ac636ab3.png)

blend file after export (no changes):
![image](https://user-images.githubusercontent.com/1696020/69609916-f26b2380-102a-11ea-9af5-a15fafad9e02.png)


* Checked in code: AutoSmooth (with angle or with custom normals) are managed like a modifier, so they are exported only when "Apply modifier" is checked


So ... Not sure to understand what is exactly your problem.

can you please test again with blender 2.82 alpha? And display screenshots from blender before / glb on https://gltf-viewer.donmccurdy.com/ / blender after?

Thanks :)

**Comment by capnm** [comment] 2019-11-29 20:22
> So ... Not sure to understand what is exactly your problem.

I think the enabled **Auto Smooth** blender option should produce a gltf with same normals as blender renders and the viewport. There is no blender modifier involved, hence the option should be irrelevant.

Tested https://github.com/capnm/b8TransportRobot/tree/master/blender81 
with the current gltf tip (1.1.16) + blender 2.81:

![image](https://user-images.githubusercontent.com/4047289/69888701-8ec44d00-12ed-11ea-98e0-0341d9df24b7.png)


![image](https://user-images.githubusercontent.com/4047289/69888626-2d03e300-12ed-11ea-8c2b-a6c3ca059205.png)

![image](https://user-images.githubusercontent.com/4047289/69888654-50c72900-12ed-11ea-8723-d0c1a5ea4cf6.png)

**Comment by NEONFIVE** [comment] 2019-12-04 09:57
Tested with Blender 2.82.3 and 2.80.75
Normals are broken when exporting with apply Modifiers checked. See image below.

![Broken_Normals](https://user-images.githubusercontent.com/56956825/70132597-d7c92800-1684-11ea-8cf1-096104b906e5.jpg)

**Comment by julienduroure** [comment] 2019-12-06 13:27
This is not the same case, because you seems to have some custom normals, where the previous example was about using auto-smooth with split angle (without custom normals)
Can you please provide the .blend file?
(We should try reimporting it not in Blender too, to be sure that the bug is not in blender importer)

**Comment by mikepan** [comment] 2019-12-06 22:15
I agree with @capnm , currently the default setting for the GLTF exporter does not export a visually identical mesh as the blender viewport since it does not respect the 'autosmooth' setting. There is a workaround which is to add a custom split normal, which seems to bake the 'autosmooth' setting into the geo.

**Comment by scurest** [comment] 2020-08-13 14:13
This appears to be fixed in master (by #1127 probably).

![tef](https://user-images.githubusercontent.com/11024420/90145041-274c1180-dd45-11ea-88d1-76c4cd2e6fb1.png)

capnm's file is also fixed.

**Comment by capnm** [comment] 2020-08-13 21:32
@scurest Thanks, perfect work!
I can confirm this is fixed in the current beta of b9 (v1.3.48).

**Closed** 2020-09-07 18:51 UTC
Labels: Mesh_&_Object, bug, exporter
