### ISSUE TITLE
Player Import Error from Older Blend file

### ISSUE THREAD

**Issue by fire** [KhronosGroup/glTF-Blender-IO#1092] opened 2020-06-14 04:51 UTC
**Describe the bug**
We are trying to update the export from an older Blender file. The goal is to export a gltf2 which we can used in Godot Engine.

**To Reproduce**

1. Go to https://github.com/godotengine/tps-demo/blob/master/player/model/player.blend
2. Click on export gltf2 and the "Apply Modifier" causes a stack track when enabled, and broken model when disabled.

[blender_export_gltf_modifier.txt](https://github.com/KhronosGroup/glTF-Blender-IO/files/4775879/blender_export_gltf_modifier.txt)

3. Open in Godot Engine or Visual Studio Code's Three js import or even Blender

**Expected behavior**
It should look like this.

![image](https://user-images.githubusercontent.com/32321/84584972-45d27280-adbf-11ea-89a8-063f5fea2d1e.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/32321/84584951-17549780-adbf-11ea-8d58-90f740c859c9.png)

![image](https://user-images.githubusercontent.com/32321/84584953-1f143c00-adbf-11ea-909f-0ec90cd20d77.png)

**.blend file/ .gltf**

If applicable, a zipped folder containing a .blend file for exporter issues and a .gltf file for importer issues. Please take care to include all resources, such as textures in the .zip file.

[player.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4775877/player.zip)

**Version**

 - OS: Windows 10
 - Blender Version 2.83

**Comment by aaronfranke** [comment] 2020-06-14 04:56
I can confirm these issues on both Windows and Linux with Blender 2.83 stable. The player file comes from the [Godot TPS demo](https://github.com/godotengine/tps-demo), and you can also find more examples there (red_robot.blend, door.blend).

**Comment by julienduroure** [comment] 2020-06-15 07:43
Hello,
Confirmed (seems to happen on 2.82 too)
Investigation in progress, but here are some first thoughts:
File has some big issues:
* Some depend cycle on armature because of how piston are rigs. This can have an impact on how rigs are exported. 
* you assigned some armature animation on mesh object.

Problem seems to be linked to depgraph evaluation. I had a quick hack that solve the issue, but I need to investigate more, because I can't reproduce on simple example.

**Comment by julienduroure** [comment] 2020-06-17 19:36
More info:
You have lots of non visbile objects on your scene that are exported, that explains why you see more object in three.js

Select visible meshes + armature and use "use_selection" to export only player+rig

**Comment by aaronfranke** [comment] 2020-06-17 20:04
Perhaps there should be an option in Blender to only export visible objects?

**Comment by julienduroure** [comment] 2020-06-18 05:54
Currently, exporter is not well designed to export only part of hierarchy tree
See #193 discussion

**Comment by aaronfranke** [comment] 2020-09-03 03:44
Here is a simpler model as a test case:

https://github.com/godotengine/tps-demo/tree/master/door/model

The existing `.dae` file works fine. When exporting the blend as `.glb` it's very weird. If all of the non-visible parts are deleted, exporting works almost fine, but it is missing an animation (it has `doorsimple_closing`, `doorsimple_closed-cycle`, and  `doorsimple_opening`, but is missing  `doorsimple_open-cycle`).

By the way, it is perfectly possible that these models have problems on their own (I'm not the artist that created them), or maybe just problems caused by opening old Blender files in a newer version of Blender. I'm not knowledgeable enough in Blender to figure out which problems are bugs in Blender, which problems are bugs in this file, or how to fix either of those categories of bugs.

**Comment by scurest** [comment] 2020-09-03 08:44
@aaronfranke The reason doorsimple_open-cycle isn't exported is because it isn't pushed to an NLA track or assigned as the active action. This exporter uses NLA tracks to organize how actions get arranged into animations. Set it up like this

![nla](https://user-images.githubusercontent.com/11024420/92092325-8c6cb300-ed97-11ea-9f5e-c0638c84cb00.png)

and it will export.

**Comment by julienduroure** [comment] 2022-02-09 18:11
Tested with #1378 + #1563 (selected object + apply modifiers)
All actions are exported with #1560 

Still have some issue with negative frame, but is out of scope of #1378
Seems to work without problem in Godot 3.4.2

![image](https://user-images.githubusercontent.com/1696020/153263434-9bf9ab46-1406-47f0-857c-3267d526824f.png)

**Comment by fire** [comment] 2022-02-09 19:05
Great! Looking forward to testing this. Is this in the steam 3.0 beta daily build yet?

**Comment by julienduroure** [comment] 2022-02-10 04:15
@fire : No, not yet.
You can find #1378 here : https://builder.blender.org/download/experimental/gltf_vtree/

**Comment by julienduroure** [comment] 2022-03-02 20:49
Fixed by 69746b2b31eeee080d5dfd3c74f1e02742795ed2

**Closed by julienduroure** 2022-03-02 20:49 UTC
Labels: bug, exporter
