### ISSUE TITLE
Materials linked to objects (and not to object's data) are not exported

### ISSUE THREAD

**Issue by atteneder** [KhronosGroup/glTF-Blender-IO#430] opened 2019-04-13 17:34 UTC
**Describe the bug**
In Blender's material tab you can choose wheter you link the material to the data (mesh) or the object.
The benefit (also for the glTF) is that you can instantiate the same mesh with different materials applied.

**To Reproduce**
1. Extract the attached zip
2. There are two blend files with 3 materials on 3 objects each. In `omnicase_data.blend` the objects have dedicated meshes and materials applied to the data. In `omnicase_object.blend` the objects share a mesh, but have different materials applied to the objects:
<img width="421" alt="Screenshot 2019-04-13 at 19 26 14" src="https://user-images.githubusercontent.com/2593014/56083224-6f41e800-5e22-11e9-8335-e1d6fcdb90e5.png">

3. `omnicase_data.blend` exported as separate glTF looks like this:
<img width="451" alt="Screenshot 2019-04-13 at 19 24 53" src="https://user-images.githubusercontent.com/2593014/56083238-95678800-5e22-11e9-9538-4837e677eaf8.png">

4. `omnicase_object.blend` exported as separate glTF looks like this:
<img width="492" alt="Screenshot 2019-04-13 at 19 24 39" src="https://user-images.githubusercontent.com/2593014/56083250-b334ed00-5e22-11e9-8c6f-b9edf02865f5.png">

Clearly just the material from the meshes is exported

**Expected behavior**
All materials applied to objects are exported accordingly. The mesh itself is re-used and not duplicated in data.

**.blend file/ .gltf**
[obj_materials.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3076511/obj_materials.zip)

**Version**
 - OS: macOS
 - Blender Version 2.80 beta

**Additional context**
I reported this one in the legacy exporter, where it was partially solved (meshes were still duplicated):
https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/186

**Comment by jamespedid** [comment] 2019-08-18 20:55
This would be a great enhancement for my use case :)

**Comment by emackey** [comment] 2019-08-19 18:33
I think this issue was fixed in #526, and we forgot to close this issue.

@jamespedid Are you seeing this behavior in the 2.80 release?  Or did you just find this in a search?  I can't reproduce it from the test model linked above, and I think it's fixed.

**Closed by emackey** 2019-08-19 18:33 UTC
Labels: Material, enhancement, exporter

**Comment by jamespedid** [comment] 2019-08-20 01:46
I think I might have different ideas or expectations and the issue might be slightly different.

For me, I want to create a single model and attach 5 textures to it. I want to export the model with a default texture chosen, but also with the other textures with the intention to change the model to a different texture at a later point in time.

I'm also very new to this technology, so there might be reasons to not do this.

**Comment by emackey** [comment] 2019-08-20 15:52
That's an interesting use.  Certainly there's been glTF spec talk of materials being swapped like this, see the thread on asset variants here:  https://github.com/KhronosGroup/glTF/issues/1569

Nothing like this exists in the Blender exporter as yet.  I think you have to use each material that you want exported to the model, but you might be able to use it with object linking as described above.  Still there's no way, yet, for the glTF to specify that the app must choose a material, at least until some asset variant mechanism is specified.
