### ISSUE TITLE
Diffuse BSDF and use_nodes=False are not supported.

### ISSUE THREAD

**Issue by samanthajo2** [KhronosGroup/glTF-Blender-IO#571] opened 2019-06-27 10:15 UTC
**Describe the bug**

Materials colors are not exported

Taking this file

[Cow.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3334088/Cow.blend.zip)

Exporting with the old exporter I get this

<img width="426" alt="Screen Shot 2019-06-27 at 18 46 27" src="https://user-images.githubusercontent.com/49654280/60258136-7fd90900-990f-11e9-9fb9-1674883d5d6b.png">

With the current export (cloned from the repo) I get this

<img width="442" alt="Screen Shot 2019-06-27 at 18 46 52" src="https://user-images.githubusercontent.com/49654280/60258158-8b2c3480-990f-11e9-95d7-71ff7cd27597.png">

**To Reproduce**
1. Download the attached file, unzip, double click the .blend file
2. File->Export->glTF 2.0
3. Export
4. Load in a viewer

**Expected behavior**

There are material colors

Checking the gltf data the old exporter has this

```
    "materials" : [
        {
            "name" : "Black",
            "pbrMetallicRoughness" : {
                "baseColorFactor" : [
                    0.02327823673603291,
                    0.02327823673603291,
                    0.02327823673603291,
                    1.0
                ],
                "metallicFactor" : 0.0
            }
        },
        {
            "name" : "Pink",
            "pbrMetallicRoughness" : {
                "baseColorFactor" : [
                    0.640000066757203,
                    0.1408390542989828,
                    0.1733517791830268,
                    1.0
                ],
                "metallicFactor" : 0.0
            }
        },
        {
            "name" : "White",
            "pbrMetallicRoughness" : {
                "baseColorFactor" : [
                    0.6400000190734865,
                    0.6400000190734865,
                    0.6400000190734865,
                    1.0
                ],
                "metallicFactor" : 0.0
            }
        }
    ],
```

the new exporter only this

```
    "materials" : [
        {
            "name" : "White",
            "pbrMetallicRoughness" : {}
        },
        {
            "name" : "Black",
            "pbrMetallicRoughness" : {}
        },
        {
            "name" : "Pink",
            "pbrMetallicRoughness" : {}
        }
    ],
```

yes, export materials was checked

**Version**
 - OS: macOS
 - Blender Version 2.79

**Comment by donmccurdy** [comment] 2019-06-27 18:24
Testing in Blender 2.8, the exporter is struggling with two things I think:

- Materials assigned to individual faces. Vertex groups are present but not related to the material assignments.
- Expect best results with the Principled BSDF material, rather than Diffuse BSDF.

After splitting the mesh (`Separate by Material`) and using Principled BSDF, the materials export correctly. That said, I realize that splitting the mesh may negatively affect your animation (which seems broken on export as a separate issue?).

![Screen Shot 2019-06-27 at 11 21 54 AM](https://user-images.githubusercontent.com/1848368/60290648-0a007d80-98ce-11e9-8f68-c17e9ad0c95d.png)

**Comment by donmccurdy** [comment] 2019-06-27 18:24
Which "old exporter" are you referring to?

**Comment by samanthajo2** [comment] 2019-06-28 10:58
Sorry, Old exporter = https://github.com/KhronosGroup/glTF-Blender-Exporter

The animation exports just fine if animation sampling is on. Of course sadly the files get significantly larger which is no so good for web tech

**Comment by donmccurdy** [comment] 2019-06-28 17:16
Thanks! Good to know the animation sampling fixes the animation issue, at least. I've added it to the list on https://github.com/KhronosGroup/glTF-Blender-IO/issues/558. Our main priority for animation right now is to get everything working, and sampling animation is the most robust way to do that. There are ways to optimize the animation later, and of course we'd like to get things working with this option turned off too.

**Comment by kocsis1david** [comment] 2019-07-20 20:56
It seems to me that the problem happens when the material doesn't use nodes.

**Comment by julienduroure** [comment] 2019-08-04 09:51
I can confirm that that remaining issue (material issue) is because of the material on the .blend file :
- use_nodes must be checked
- we have to use principled shader, as requested in user manual.

So it seems that we can close this ticket!

**Comment by samanthajo2** [comment] 2019-08-15 16:43
I am confused. I don't see any option in the exported called "use_nodes". I don't know what it means to use principled shader

Are you saying the export won't support these files? They work fine in both Unreal (.fbx) and Unity (.blend). It would be a shame if they didn't work in glTF.

**Comment by kocsis1david** [comment] 2019-08-15 16:57
In the material settings panel of the object, you can choose to use nodes and there you can also choose the shader to be the principled bsdf.

**Comment by samanthajo2** [comment] 2019-08-16 06:39
So you're saying unlike Unity and Unreal, to use files with glTF I have to learn blender and modify the files? Up until this point all I had to learn was load->export. Now I have to modify the files, and either remember each time to modify them or save new ones. If I tell others "hey, there's some cool models at coolmodels.org" I also have to tell them instructions how to actually get them to work.

Wouldn't it be better of the exporter just worked. In fact this is arguably a regression is it used to work.

**Comment by kocsis1david** [comment] 2019-08-16 06:50
I've also bumped into this issue, but I don't know other way, I guess you need to modify files like these.

**Comment by julienduroure** [comment] 2019-08-16 08:44
@samanthajo2 @kocsis1david In blender, use_node is most of the time enable by default.
You provided only .blend file, so I don't know what file format you imported, and I can't check what happpen at import level.

The aim of an exporter is not to export exactly what was imported, but to export what is inside Blender. If use_node is not checked, and render in blender, you will not see the same render than if use_node is checked. Exporter should take this into account to export was use can see when he renders. ( of course modulo specification of the file format, that can't handle everything done in blender)

**Comment by donmccurdy** [comment] 2019-08-16 19:09
For more detail on what we support, and recommended settings, see https://docs.blender.org/manual/en/2.80/addons/io_scene_gltf2.html.

**Comment by samanthajo2** [comment] 2019-09-04 16:00
I'm still unclear on why you don't consider this a regression. I can go get the old exporter, load the same .blend file into blender and get the correct material colors. Then I use the new exporter and don't get the correct colors.

**Comment by donmccurdy** [comment] 2019-09-04 16:17
Let's keep this open to track that Diffuse BSDF and use_nodes=False are not supported.

This exporter was rewritten — involving a very, very large number of changes — for Blender 2.80, and support for Blender 2.80-standard materials is currently higher priority. But supporting Diffuse BSDF and use_nodes=False again would be nice, if it's not a major change from the current material export.

**Comment by scurest** [comment] 2020-07-27 15:35
The title talks about Diffuse BSDFs, but the Cow.blend file only uses use_nodes=False. I filed #1148 to fix use_nodes=False.

If Diffuse BSDF needs to be exported, I think a separate issue should be filed with an example .blend.

**Closed** 2020-07-27 17:42 UTC
Labels: Material, bug, exporter
