### ISSUE TITLE
Bad roundtrip: wrong up direction

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF-Blender-IO#715] opened 2019-10-07 01:15 UTC
Import [this file](https://github.com/KhronosGroup/glTF-Blender-IO/files/3695160/b00A.zip) and you get this

![ok](https://user-images.githubusercontent.com/11024420/66279201-962f2300-e875-11e9-81be-304166bf3e13.png)

Then export (with default settings) and import again and you get this

![bad](https://user-images.githubusercontent.com/11024420/66279205-a2b37b80-e875-11e9-92db-9861ff1a7c12.png)

**Comment by julienduroure** [comment] 2019-10-07 04:43
Can you please provide the original textures, because I can't read the original glb file with external viewer, missing b00A.png

Opening the generated glb (after roundtrip) seems to have the same orientation than in blender (heads are up) 
![image](https://user-images.githubusercontent.com/1696020/66285481-1fbe0f80-e8cd-11e9-8c0e-af1f038162c9.png)
So not sure what is wrong yet.

Maybe link to the fact that in glb file, joints are children of mesh, this is usually not the case in tested gltf file, and this is not the case in blender workflows. --> To be investigated

**Comment by julienduroure** [comment] 2019-10-07 05:11
Just thinking: This is a glb and saying that an external texture file is missing???
What's wrong with this glb file?

**Comment by scurest** [comment] 2019-10-07 13:30
.glbs can refer to external resources. Not everything has to be packed into it. [Here it is](https://github.com/KhronosGroup/glTF-Blender-IO/files/3697391/b00A.zip) without textures, if that helps.

----

Anyway, I was working on a branch that would get rid of the Yup2Zup object by converting glTF -> Blender coordinates immediately on reading any coordinates. You can see it [here](https://github.com/KhronosGroup/glTF-Blender-IO/compare/master...scurest:coordinate-change). This (totally unintentionally) fixes this issue.


But it doesn't round-trip bone directions and when I was investigating it, I found something kind of weird: consider a set-up like this

![bones](https://user-images.githubusercontent.com/11024420/66315218-f6a47b80-e8da-11e9-8d7d-6473b70791fb.png)

Bones point along their +Y axis in Blender. That's the -Z axis after changing to glTF space. So I expected the upper bone to be translated by, like, [0,0,-1] in glTF. But it's translated by [0,1,0], no matter whether you export with _Transform > +Y-Up_ option or not.

Do you know why that is?

**Comment by julienduroure** [comment] 2019-10-07 14:40
Thanks for the new file. I will check it.

About coordinates conversion on the fly at import: This will need to be tested very carefully, because it will change lots of things. Please note to keep a debug option to import without conversion, as this is done for now with debug value 100.

About your bone issue, at a first check, I don't know. I have to test / check deeper.

**Comment by julienduroure** [comment] 2019-10-07 21:22
About original bug report:
Confirmed that it comes from exporter.
Confirmed that it is linked to the fact that armature is child of the deformed meshed. Don't know why exactly yet, investigation in progress.
For example, following blend file exports fine (where armature is parent of the child mesh): 
[b00A.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3699506/b00A.blend.zip)

**Comment by julienduroure** [comment] 2020-01-24 16:06
Seems this case is also fixed by #857 , closing

**Closed by julienduroure** 2020-01-24 16:06 UTC
Labels: Skinning_&_Rigging, bug, exporter
