### ISSUE TITLE
Error with Shape Keys and Armature when exporting to glTF 2.0

### ISSUE THREAD

**Issue by pigtrumkt** [KhronosGroup/glTF-Blender-IO#2329] opened 2024-08-25 21:49 UTC
I am using Blender 4.2.1.0, and I want to import a glTF file into Unreal Engine 5.4.3, but I'm encountering errors when combining both armature and shape keys.

Case 1:
Step 1: Select the armature and mesh.
Step 2: Export to glTF 2.0 with the "Apply Modifiers" option enabled.
Step 3: Import back into Blender, but the shape keys are missing.

Case 2:
Step 1: Select the armature and mesh.
Step 2: Export to glTF 2.0 without applying the "Apply Modifiers" option.
Step 3: Import into Unreal Engine 5.4, but the mesh and shape keys are not displayed.

Case 3:
Step 1: Select only the mesh.
Step 2: Export to glTF 2.0.
Step 3: Import into Unreal Engine 5.4, and the shape keys are present, but the armature is missing.
I'm not sure if this is a bug in Blender. Could you please help me with this?

Thank you very much!

**Comment by julienduroure** [comment] 2024-08-26 10:57
Case 1:
This is a limitation of Blender. As described in tooltip, you can't export shapekeys if you apply modifiers.

Case 2:
I can't be sure without a .blend test case, but this is maybe a duplicate of #2321 

Case 3:
If you select only the mesh (and enable option "selection only"), this is the correct behavior to not export the armature, as you didn't select it

**Comment by pigtrumkt** [comment] 2024-08-26 11:12
Hello julienduroure,
My case is similar to ticket #2321. Are you fixing it?

**Comment by pigtrumkt** [comment] 2024-08-26 11:14
If it's already fixed, has it been released? Sorry for the inconvenience.

**Comment by julienduroure** [comment] 2024-10-31 12:32
Closed by #2324

**Closed by julienduroure** 2024-10-31 12:32 UTC
Labels: question
