### ISSUE TITLE
Export Armature and Animations Only - Exclude Mesh

### ISSUE THREAD

**Issue by sketchpunk** [KhronosGroup/glTF-Blender-IO#822] opened 2019-12-09 20:23 UTC
I would like to be able to export only the animations. THe idea is that I export the mesh+armature in one file, then export animations+armature in as other files. I do not want them together in one large file for specific reasons.

**Comment by julienduroure** [comment] 2019-12-10 07:59
Did you try to select only armature (and parents from armature to root of the scene), and export using "Selected Objects" ?
Seems to do what you are looking for, except if I misunderstand something.

**Comment by sketchpunk** [comment] 2019-12-10 14:09
I tried that before. The animation gets exported but not the armature. When I open the GLTF file, I see the animation element has channels and samples, the nodes for the bones are there too but, the SKIN element is missing. Without that, I do not know the order of the bones to properly export the data to the shader. The only way I can get the SKIN data to be saved to the file is if I also select at least one Mesh thats attached to the armature.

So year. there is no way to just export the Armature and Animations only.  I have my own parser, so I would like to be able to just render all the bones and animate them, but without skin element, i'm stuck.

**Comment by julienduroure** [comment] 2019-12-10 14:24
I understand. 
The problem is that _skin_ must be attached to a mesh node, so not sure the glTF specification can answer your specific requirement. 
We can't export "empty meshes", because primitives array must have minimum 1 element.
Maybe #732 will help you to export specific data that you need (currently not merged)

**Comment by donmccurdy** [comment] 2019-12-12 12:45
I'm not aware of any requirement in the specification that a node having a `skin` must also have a `mesh`. The closest language I can find is...

> A skin is instanced within a node using a combination of the node's `mesh` and `skin` properties. The mesh for a skin instance is defined in the `mesh` property. The `skin` property contains the index of the skin to instance.

...which is probably more ambiguous than it should be, and we should clarify it either way. But unless there are side effects I haven't thought of, I believe we should allow a skin to be attached to a node without a mesh. That should be useful for exporting skinning animations in standalone files, as just an animated skeleton.

However, morph target / shape key animation would _not_ be valid without a mesh.

**Comment by lexaknyazev** [comment] 2019-12-12 14:49
> I'm not aware of any requirement in the specification that a node having a `skin` must also have a `mesh`.

It's in the schema.

**Comment by sketchpunk** [comment] 2019-12-12 15:26
Here's the thing. The Bone Nodes and the Animation all gets exported now. The only thing thats missing is the skin element. Its a root element, all it does is give you the order of the bones plus the Node index for each bone. There is no possible bad side effect of having it included. In all honestly, the way it works now feels wrong. 

I select armature ONLY to export but the exporter only saves bone nodes and animations but excludes skin which ties the other two bits together. If Skin needs a mesh, then why are Bone Nodes and animations being exported? They're useless without the skin data. Thats a flaw in my opinion.

So I think either fix the export to say, you can not export armature+animations without a mesh or just put the skin data in and let it work as an animation asset export.

**Comment by donmccurdy** [comment] 2019-12-16 18:15
> It's in the schema.

I see. This is perhaps worth revisiting in https://github.com/KhronosGroup/glTF/issues/1665 (or perhaps out of scope, I'm not sure).

**Comment by Snouf-ID** [comment] 2021-12-03 20:12
I need to export armature + animation to gltf. I have fbx files with the model, and fbx files with only the frame and an animation. Cannot export this files only with armature in GLTF.
There is news on how to export only the armature in 2021?

**Comment by donmccurdy** [comment] 2021-12-03 20:22
@Snouf-ID some kind of mesh will have to be attached to the armature to export. That could just be a cube weighted to a single bone, I think, and then you'd connect it to the final mesh in another application.

**Comment by julienduroure** [comment] 2022-02-28 09:55
So,
Having a node with "skin" property without "mesh" property is not allowed (cf Schema)
But it seems we can add a "skins" at root of glTF file, without any "skin" reference to element of "skins" element, seems to be allowed.

Can someone confirm (or not)? @donmccurdy ?

**Comment by lyuma** [comment] 2022-02-28 10:31
@julienduroure I'm afraid you are mistaken. It is perfectly valid in the glTF spec to do this. I already have written a plugin for Godot which uses unused skins as an armature hint while porting files from FBX.

The glTF spec does not state any normative behavior when an unused skin object is encountered, but multiple applications use this as a signal of intent by the user to indicate that an armature is desired rather than a node tree.

Here is an example of an XBot avatar with a few animation tracks embedded:
[xbot_rig_anim.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/8152524/xbot_rig_anim.zip)

You can see here that Three.js, Blender, and Godot already support this de facto behavior. Screenshots at bottom.

Finally, you can see here from the validator (screenshot below) that a single Note is created for the unused skin object, but no Warning or Error is issued for this case, as it is legal to include unused objects.

@donmccurdy If it hasn't already been done, I would suggest that this behavior ought to be written as an Implementor's Note in the glTF 2.0 specification, given the prevalence of apps that take an unused skin as a hint for an armature to be created.

Godot:
![Godot, showing a Skeleton object](https://user-images.githubusercontent.com/39946030/155966099-419b43cd-fd14-490b-bb99-30b9d9023fc2.png)
Blender:
![Blender, showing an Armature object](https://user-images.githubusercontent.com/39946030/155966353-0974dd4e-019e-4f9a-a20f-6f5476f1a69e.png)
Three.js (I imported another copy on the right without the skin to illustrate the difference):
![Three.js showing a Skeleton on the left](https://user-images.githubusercontent.com/39946030/155967307-0cba9a78-547d-4eac-919e-510dedb4b43f.png)
glTF Validator:
![glTF validator showing This object may be unused. /skins/0](https://user-images.githubusercontent.com/39946030/155966803-904e59ea-ca95-46de-9a78-a241a173e879.png)

**Comment by donmccurdy** [comment] 2022-02-28 13:46
What is the proposed change in glTF-Blender-IO here? Something like:

1. Provide option to exclude all meshes from export
2. Export animated node hierarchy
3. Export unused skin(s) identifying nodes as joints

All of that sounds fine to me. The validator's message that the skin "may be unused" can be ignored safely. We may need to be careful that the skin exported in this case is _identical_ to the skin exported when a mesh is attached — otherwise applications attempting to retarget the animation may run into problems. So, using the same joints, in the same order, with the same inverse bind matrices.

> I would suggest that this behavior ought to be written as an Implementor's Note in the glTF 2.0 specification...

Personally I think I see this as one more example of the general use case of 'unused' resources – unused meshes, textures, and materials are also there for applications to use as data resources rather than directly as part of the scene. But if there's some wording you feel would be helpful, I'd recommend opening a PR – the use case of animations in a separate file is popular enough.

**Comment by julienduroure** [comment] 2022-02-28 14:29
Currently:
When an armature is exported, but not the skined mesh (when user select only the armature and export with "limit to selection"), no skins array is exported

To be:
When an armature is exported, but not the skined mesh (when user select only the armature and export with "limit to selection"), an (not used) skins array is exported

**Comment by julienduroure** [comment] 2022-03-03 12:44
A PR is available here : #1582

**Closed** 2022-03-13 10:22 UTC
Labels: enhancement, Animation
