### ISSUE TITLE
Export armature animation with bones - more than two NLA animations does not deflect same amount

### ISSUE THREAD

**Issue by ronh991** [KhronosGroup/glTF-Blender-IO#1471] opened 2021-10-01 21:17 UTC
**Describe the bug**
I have an armature with two NLA animations. A joystick that move fore and aft (anim1) and left and right(anim2). In blender the animation moves the entire distance when both animations are active. In the export to gltf/bin the animations seems to be about 1/2 the displacement.

**To Reproduce**
Create joystick - cylinder.
Add armature
add bones, 4 bones. main, fore_aft, left_right and base.
weight piant fore_aft bone to 
weight paint left_right
make animation 0,1,2 KF, 0 is left 1 center 2 right
make second animation, 0 fore 1 center 2 aft

animation displacement rotation 45 degrees.

make animations and push down stack NLA
make default state bone (not required) 0,1,2, all center. - required for MSFS

**Expected behavior**
in blender it moves 45 degrees, in gltf export if does not only say 30 degrees.

**Screenshots**
https://youtu.be/kkNUBM_1kqE

**.blend file/ .gltf**
If applicable, a zipped folder containing a .blend file for exporter issues and a .gltf file for importer issues. Please take care to include all resources, such as textures in the .zip file.

[TestPlaneMSFS_Interior_LOD99.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/7270188/TestPlaneMSFS_Interior_LOD99.zip)
**Version**
 windows 10 

Blender 2.93.4

**Additional context**
this issues started in branch on khronos version traced back to existing

**Comment by julienduroure** [comment] 2021-10-02 06:32
Hello,
Please test again with a recent build. https://builder.blender.org/download/daily/
I think the issue is linked to way animation are mixed and should be fixed by #1433 + #1468

Before #1433, all bones has some keyframes, so the mix is done between 0 and keyframes (your angle) 
Now, only animated bones has keyframes, so they is no mix between 0 and your angle.

**Comment by ronh991** [comment] 2021-10-02 14:45
Thanks will test - Is this also part of the ver 3.x cadidate?

**Comment by ronh991** [comment] 2021-10-02 15:04
No it did not work with 2.93.
[TestPlane6-1_MSFS_v17_2935_test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/7271693/TestPlane6-1_MSFS_v17_2935_test.zip)
5

**Comment by julienduroure** [comment] 2021-10-02 16:53
This is a recent change, not in any stable version. Please test with 3.0 alpha

**Comment by ronh991** [comment] 2021-10-02 20:06
Ok tested in ver 3.0 alpha 12e8c783535c.  The result is almost what I require. If I enable the two animation fore/aft and left/right then the displacement is 100% the same as blender.  However (and this may be a feature request) for MSFS (Microsoft Flight Simulator 2020) there is a third animation at to top of the stack. This is the rest position and it is the same position for and ALL the KF. The same location KF 0,1,2 all center straight up.  When I enable all three animation then the gltf viewer goes back to half deflection.  So there is still some calculation reducing it to approx 1/2 deflection.

**Comment by julienduroure** [comment] 2021-10-04 11:23
Well, I don't think there is any issue in Blender now in your case.
This is the way animation are used (how there are mixed) by the viewer that is your problem. Currently, seems animation are mixed (using average), and you probably want it to be added

**Comment by ronh991** [comment] 2021-10-04 13:38
Thanks for all your help.  I guess we can close this issue.

**Closed** 2021-10-04 14:01 UTC
Labels: question, exporter, Animation
