### ISSUE TITLE
Export Draco Compression Rate Problem compared to gltf-pipeline

### ISSUE THREAD

**Issue by ghost** [KhronosGroup/glTF-Blender-IO#532] opened 2019-06-07 08:21 UTC
Hello,
There's an important compression rate difference between the Blender gltf output and gltf-pipeline's. Without any texture, not environmental texture and only one material, I have a 21MB (with Blender Draco Exporter) and 1,8MB (with Draco gltf-pipeline) from a 60MB model (default GLTF).

I made sure it was only geometry.

**To Reproduce**
In my tests, I exported two gltf, one draco gltf, one default gltf. I passed the default gltf to the gltf-pipeline, default settings. I did not changed Blender gltf draco settings.

**Expected behavior**
I compared Blender's draco VS gltf-pipeline's draco and the difference was huge. I expected the same result, or near.

**.blend file/ .gltf**
Sorry, I cannot provide the file. I expect this problem to happen for every file.

**Version**
 - OS: Windows 10
 - Blender 2.80 (sub 74) build date: 06/03/2019

Blender GLTF Exporter wtih Draco would be very cool but for now, I am going to use gltf-pipeline. I hope you can fix this bug.

Cheers,

Eric

**Comment by julienduroure** [comment] 2019-06-09 11:34
@UX3D-nopper @McNopper can you please have a look on it?

**Comment by UX3D-nopper** [comment] 2019-06-09 12:16
Yes, we will have a look at it next week.

**Comment by UX3D-schmithuesen** [comment] 2019-06-24 07:53
Just an update from our side: it was easy to reproduce the issue, but we still don't know where it comes from. Some things that we talked about:

* since it's written in JS, gltf-pipeline doesn't use the **same** implementation of Draco that we use (the result should be the same anyway)
* the version of Draco used in Blender is outdated by now
* gltf-pipeline does more than just Draco compression

Sadly, this doesn't really give us an answer yet.

**Comment by Eric02** [comment] 2019-07-28 15:54
Hello everybody!

Is there any update for this issue? I just tested the exporter (w/ Draco) in Blender 2.8 RC3 and got the same results. Are you going to implement gltf-pipeline in Blender or we should not use Draco compression (from Blender)?

Thank you.

**Comment by UX3D-nopper** [comment] 2019-07-28 16:32
We wait, until Blender 2.80 is out, as replacing the C++ library could harm the release.

**Comment by Eric02** [comment] 2019-07-31 13:17
Blender 2.8 is out!  https://www.blender.org/download/

**Comment by UX3D-nopper** [comment] 2019-07-31 13:25
So, let's target 2.81

**Comment by julienduroure** [comment] 2019-10-22 06:37
@UX3D-nopper and @UX3D-schmithuesen Any news? Can you please target it for 2.82?

**Comment by UX3D-nopper** [comment] 2019-10-22 07:15
We are currently asking for a small budget to look into all Draco related issues. If granted, some of our team members will work dedicated on it.

**Comment by UX3D-nopper** [comment] 2019-11-05 15:40
@julienduroure Thanks a lot to Google, we do have a budget granted to fix the bugs.

**Comment by UX3D-schmithuesen** [comment] 2019-11-07 10:28
This fix is here: https://developer.blender.org/D6183
This was already merged so a Blender build from the latest source should export smaller files. Right now, I can't say if the results are identical to the gltf-pipeline, but @Jim-Eckerlein identified and fixed a bug that made a huge difference.

@julienduroure, since the OP is now a @ghost, do you want to verify this? We consider it done.

**Comment by UX3D-eckerlein** [comment] 2019-11-11 08:58
There is a fix here: #767 

The binary buffer's size from the exported glTF should now match the buffer size produced by `gltf-pipeline`.
Interestingly though, `gltf-pipeline` seems to actually reduce the attribute count, instead of just compressing the data, yielding in smaller file sizes.

When exporting the attached `torus.blend` just with positions, both the uncompressed and compressed file hold 147456 position values. Of course, the buffer size still differs due to compression.
When compressing the uncompressed, exported file using: `gltf-pipeline -i torus.gltf -o external.gltf -s -d --draco.compressionLevel 6`, the file just holds 36864 positions.
I currently don't know if that is intended behaviour from `gltf-pipeline`.

[torus.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3830406/torus.zip)

**Closed** 2019-11-12 21:35 UTC
Labels: draco, exporter
