### ISSUE TITLE
Extension MSFT_texture_dds is not available on this addon version

### ISSUE THREAD

**Issue by Fortn00b15** [KhronosGroup/glTF-Blender-IO#1294] opened 2020-12-14 13:44 UTC
I went through the installation process of this add-on exactly as described but keeping getting the following error "Extension MSFT_texture_dds is not available on this addon version" anytime I try to import a plane model.

**Expected behavior**
Import the LOD model with no issues. 

**Version**
 - OS: Windows 10
 - Blender Version 2.91

**Comment by scurest** [comment] 2020-12-14 13:53
I have a branch that imports MSFT_texture_dds. It's easy to do. https://github.com/KhronosGroup/glTF-Blender-IO/compare/master...scurest:dds

**Comment by emackey** [comment] 2020-12-20 18:17
Are DDS models floating around somewhere that users can reach them, maybe in MS FlightSim or someplace?  If so, maybe we should break with conventions and allow just import (not export!) to work with DDS models?

Blender can import DDS images without any conversion, and the glTF exporter will automatically re-encode them into a standard form on export.  Maybe allowing DDS glTF import is a good thing?  We should just be clear it's a non-standard use of glTF, so no exporting in that form.

**Comment by donmccurdy** [comment] 2021-01-02 20:57
I haven't seen any examples of the MS Flight Simulator models yet, but I would guess that's the source here. Do we know if that's the only non-standard thing about these models?

**Comment by ptasev** [comment] 2021-01-09 01:33
I just want to add another voice in favor of supporting import of the dds extension.  Also, what's the reason that you wouldn't want to support export?

**Comment by emackey** [comment] 2021-01-09 02:07
> what's the reason that you wouldn't want to support export?

Because the exporter would produce non-standard files that wouldn't work in other applications.

**Comment by donmccurdy** [comment] 2021-01-09 02:09
DDS is not an official part of the glTF format (it's part of an unofficial extension created for internal use in Microsoft tools), and it can't be rendered on many devices (mobile devices especially) that would otherwise support glTF files. There are newer and more widely-compatible compressed texture formats available, like Basis, which I'd be more excited to support.

In any case, we can't implement the extension without example models to test. I'm concerned that there may be other things in the MSFT Flight Sim models that would prevent us from loading them here, not just the DDS textures...

**Comment by donmccurdy** [comment] 2021-02-13 03:55
I'm not sure we can do anything on this issue. If someone can provide an example of the MS Flight Sim models they would like to import, we can at least inspect those and figure out whether DDS textures are the only non-standard thing about them. Until then, closing.

**Closed by donmccurdy** 2021-02-13 03:55 UTC

**Comment by MeFisto94** [comment] 2021-05-23 22:41
I'd just like to give my two cents here: 
I'm using gltf as an exchange format to convert from/to an old DX9 based game, where I reversed the asset formats.
Since the games textures are all DDS, I wanted to use the `MSFT_texture_dds`.
The goal there is to just make it visible in blender, whereas editing the texture (painting, etc) would be good enough to be done in another tool.
It's also not used to display stuff on the web, but rather as a tool exchange format for me.

That being said, there is the perspective from https://github.com/KhronosGroup/glTF-Blender-IO/issues/382#issuecomment-678714440:
> The DDS extension dates to the earliest days of glTF 2.0. Microsoft never intended for it to be standard, it was just an internal-use-only stop-gap measure (per Gary Hsu) until texture compression became available.
> This exporter has thus far stuck with KHR_ extensions. We could add EXT or some really popular vendor extension at some point if needed, but we don't want the glTF ecosystem to get polluted with non-standard DDS files (and yes I understand they're popular, but that doesn't make them rigorous enough for use in the glTF ecosystem).

So there's the kinda "political" debate about their inclusion. A common argument also was that gltf is designed with the web in mind, and dds is not really portable outside of Direct X (at least isn't designed to be).
For tooling, however, not supporting DDS isn't desirable, so maybe we can treat importing and exporting differently? Or something like: Only export to DDS if the file has been imported as dds/is dds.

I don't understand the technical challenge of this though, because there is the DDS Extension in the spec and as long as the importer/exporter adheres to this spec, it does every right. If MS Flight Sim does also add other attributes under that extension that are not part of it, it's MS Flight Sim doing the wrong things.
Technically speaking, those other changes should be dedicated extensions, though.

Maybe that is also a solution, considering #1377 and only allow/distribute dds as an addon to handle the extensions, much like one would add in-house/custom extensions as well, like they don't need to be part of the "Core" Loader.

Thanks in Advance for your time/comments

**Comment by ludo5x5** [comment] 2021-07-10 01:48
Please re-open that issue, while export is not needed, import support for GLTF/DDS would be great.

Here is a sample GLTF with the import issue to reproduce the problem and develop a solution to the error:

  Extension MSFT_texture_dds is not available on this addon version
[To-Reproduce-Extension_MSFT_texture_dds_is_not_available_on_this_addon_version.gltf.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/6794481/To-Reproduce-Extension_MSFT_texture_dds_is_not_available_on_this_addon_version.gltf.zip)

**Comment by brandon-lockaby** [comment] 2022-12-15 21:38
+1 for not adding arbitrary companies' extensions to the standard

**Comment by swiinger** [comment] 2023-07-10 13:06
Hello, here's a link of a MSFS2020 plane's gltf model if it can help
[https://drive.google.com/file/d/1pDsybynhbFuv49wNjr-BYVFbcRABkQmX/view?usp=sharing](url)
Thanks

**Comment by UltraEngine** [comment] 2023-10-20 21:48
> > what's the reason that you wouldn't want to support export?
> 
> Because the exporter would produce non-standard files that wouldn't work in other applications.

That's not true, we export glTF files with DDS or Basis textures. The extensions are set up so the models still reference the original PNG/JPEG files and can still be loaded with any standard glTF loader.

**Comment by donmccurdy** [comment] 2023-10-20 22:28
- /cc https://github.com/KhronosGroup/glTF-Blender-IO/issues/1234#issuecomment-1773467067

**Comment by ptasev** [comment] 2023-10-20 22:48
I still think at least import of DDS files should be supported. It would save tons of processing time for me when generating glTF files since right now I have to manually decode them on the CPU as a png which is very time consuming. Blender on the other hand can load them directly to GPU.

**Comment by hobsie** [comment] 2024-11-09 13:10
Would be useful if the importer didn't just outright fail to load the rest of a GLTF file because it can't load a few textures

**Comment by scurest** [comment] 2024-11-09 14:16
@hobsie Interesting point. That should already work if MSFT_texture_dds is not marked required. If it is marked required, I also think the importer should import it anyway (and produce a warning).

**Comment by julienduroure** [comment] 2024-11-09 14:50
> That should already work if MSFT_texture_dds is not marked required.

I agree with that.
If not mark as required, it must have a fallback texture.

See https://github.com/KhronosGroup/glTF/blob/main/extensions/README.md#extension-mechanics

> a texture image format extension must be listed as required unless fallback textures in core formats (JPG, PNG) are also supplied. 



> If it is marked required, I also think the importer should import it anyway (and produce a warning) 

The spec says:

>  an asset SHOULD NOT be loaded if the client does not support the specified extension

So ... we should not, even if this is not forbidden.
I will discuss it with Khronos glTF Working Group
