### ISSUE TITLE
Export: Grandchild object of bone is not exported correctly

### ISSUE THREAD

**Issue by bnelson1324** [KhronosGroup/glTF-Blender-IO#1867] opened 2023-02-12 05:01 UTC
**Describe the bug**
I have made object A a child of a bone, and object B a child of object A. When exporting, object B disappears.

**To Reproduce**
1. Add 2 meshes (A and B) and an armature to a scene
2. Make mesh A a child of the armature's bone
3. Make mesh B a child of mesh A
4. Export scene as glTF
5. Import the resulting glTF file to Blender. See that mesh B was not imported

**Expected behavior**
Mesh B gets exported/imported along with all the other objects/bones.

**.blend file/ .gltf**
[issue.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/10715323/issue.zip)
I have created a scene following the steps above. Mesh A is a cube and mesh B is a cone. When importing the glTF file, the cone disappears.

**Version**
 - OS: Windows 10
 - Blender Version 3.4.1

**Comment by julienduroure** [comment] 2023-02-12 08:41
Hello,
I can confirm on 3.4.1, but it is already fixed in main branch (that is 3.5 alpha).

Anyway, seems there is still an issue about object parented to bone. Probably a duplicate of #1811 .
You can workaround by enable "Use Current Frame" at export.

Can you please confirm that the issue is solved in 3.5 alpha?

**Comment by bnelson1324** [comment] 2023-02-12 09:52
Hello, I tried exporting and importing my file again in the 3.5.0 alpha build, but the grandchild object is still disappearing when imported.

**Comment by julienduroure** [comment] 2023-02-12 10:12
> Hello, I tried exporting and importing my file again in the 3.5.0 alpha build, but the grandchild object is still disappearing when imported.

I can't reproduce.
The cone is here after export/import on recent build of 3.5 apha.
Did you change some export or import settings?

With the #1811 bug, after reimporting:
![image](https://user-images.githubusercontent.com/1696020/218304953-c4f8431e-494f-479d-bb8e-e8e73e057497.png)

Using "Use current frame" at export, then re-import:

![image](https://user-images.githubusercontent.com/1696020/218305029-6905e504-f547-497f-ae6e-08f4afb713b2.png)

**Comment by bnelson1324** [comment] 2023-02-12 10:29
The only setting I changed is "Use current frame".

The workaround fixes this issue for me in 3.4.1 and 3.5. Exporting/importing with "Use current frame" on in 3.5:
![issue-with-use-current-frame](https://user-images.githubusercontent.com/33214860/218305483-c355290f-1ed0-43a0-a9b7-2d7a143738d3.png)

But when I turn off "Use current frame" in 3.5 and export/import:
![issue-without-use-current-frame](https://user-images.githubusercontent.com/33214860/218305491-e73ef8e3-d325-4a60-9ec3-e0c4edc79d22.png)
For me the cone completely disappears. But it seems for you, the cone is still imported, but in the wrong position.

**Comment by bnelson1324** [comment] 2023-02-13 08:02
Nevermind, I tried reproducing my steps on the February 13 build, and the cone was imported just like in your screenshot. I was using the February 10 build yesterday. Thank you for the fix.

**Comment by julienduroure** [comment] 2023-02-13 08:04
Hello,
Thanks for your feedback.
I will close this ticket, because it seems to be solve, except the part that is a duplicate of already know #1811

**Closed by julienduroure** 2023-02-13 08:04 UTC
Labels: question
