### ISSUE TITLE
Material properties exported as integers instead of floats/numbers

### ISSUE THREAD

**Issue by TimZoet** [KhronosGroup/glTF-Blender-IO#843] opened 2019-12-28 18:15 UTC
**Describe the bug**
When importing a gltf file created with Blender using a well-known [C++ library](https://github.com/syoyo/tinygltf) several material properties were not handled correctly. For example, a metallic factor of 0 was not read at all. This seems to be a result of the exporter writing 0 (and 1) without a decimal point. Without a decimal point, the values are then interpreted as integers, which appears to be a violation of the gltf standard (see for example [spec](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#pbrmetallicroughnessmetallicfactor)).

**To Reproduce**
Simply export the default cube with the principled BSDF and a metallic factor of 0.

**Expected behavior**
number types should be exported using a decimal point.

**Additional context**
This problem might occur in more places than just the materials.

**Comment by donmccurdy** [comment] 2019-12-28 19:21
Here's an example file, created as you suggest:

[IntTest.gltf.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4007347/IntTest.gltf.zip)

![Screen Shot 2019-12-28 at 11 16 26 AM](https://user-images.githubusercontent.com/1848368/71548476-95cd9200-2963-11ea-861a-4c72a82877fc.png)

My understanding of the JSON schema is that the _value_ must be of the correct type, but the decimal is neither required for floats nor prohibited for integers. See: https://json-schema.org/understanding-json-schema/reference/numeric.html. This model passes the official glTF validator, as well: http://github.khronos.org/glTF-Validator/. The two 'info'-level issues it reports are just because I didn't remove unused UVs and nodes in the scene, not related here.

If tinygltf cannot load a model that passes the validation suite and loads correctly in other viewers (like gltf-viewer.donmccurdy.com/) then I would recommend reporting an issue on that repository.

/cc @lexaknyazev

**Comment by lexaknyazev** [comment] 2020-01-02 12:37
Updated the pending PR: https://github.com/KhronosGroup/glTF/pull/1574.

**Comment by donmccurdy** [comment] 2020-01-02 18:59
@lexaknyazev thanks! So it sounds like we should report this as a bug on tinygltf, if real values without a fractional part "should be universally supported"?

**Comment by emackey** [comment] 2020-01-03 16:04
I have a project that uses Tinygltf, and I'm having trouble reproducing this issue.  It seems to handle integers in these fields OK.  I don't know if it's the same version etc.

@TimZoet Many JSON writers will skip the fractional part of it's zero, so your glTF reader does need to tolerate that possibility.  This is not a bug in the Blender exporter, so I'll close this issue, but discussion of spec clarifications will continue in KhronosGroup/glTF#1574.

**Closed by emackey** 2020-01-03 16:04 UTC
