### ISSUE TITLE
Inconsistent errors on GLTF export from Blender after modifying action

### ISSUE THREAD

**Issue by aoedipus** [KhronosGroup/glTF-Blender-IO#274] opened 2019-02-04 17:32 UTC
I have a model with 7 animations that exports ok, with or without actions being pushed down into NLA tracks, or saved as data blocks. I introduce a new animation following a workflow identical to the other seven (all rigged and exported in Mixamo, then imported to Blender 2.79b as FBX). The exporter will then typically start throwing errors, even though no settings have changed. A voodoo process ensues, trying things like purging data, removing then relinking actions, appending from a .blend file instead of importing the FBX directly, reinstalling the exporter, clearing keyframes, quitting and restarting, saving as a new file name, etc.

Sometimes one of these things works - or something else happens that makes it appear as though one of these things works. There's no rhyme or reason that I can discern. Establishing a reliable workflow for modifying an animation or introducing a new action has become fraught with fear.

This issue is seemingly related to [39](https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/39) and [166](https://github.com/KhronosGroup/glTF-Blender-Exporter/pull/166). So far no workaround I've tried is very predictable.

Occasionally bones import from Mixamo with a -1 orientation on a given quaternion, which I'll correct in Blender. I've also noticed a high degree of weirdness when re-exporting things that play back fine in Blender, then break apart (unexpected rotations) when loaded in a three.js context. Applying all the loc/rot/scale makes no difference. Again, there's not a pattern for why this happens that I can figure out. Unsure if it's somehow related.

The steps that seem to semi-reliably get things exporting properly again include: purging data > clearing all animation data in the scene view, relinking actions by running through each of them in the action editor, saving as a new .blend file, quitting blender, reopening the file, and exporting. When that fails, as a last resort I will clear keyframes (but this often requires a fair amount of cleanup, or redoing an animation from scratch - ugh). Even this last step only works sporadically.

If I had any hair left to pull out I would. [This file is an example](http://nideffer.net/book/media/mod/game/pnpc/alvin/Alvin.blend) of one that was broken a bit ago, but started working again after taking the step of clearing keyframes on the root bone of the newly added action.

I'm currently using the most recent build of the gltf 2.0 Import-Export package.

Any feedback/tips much appreciated, and thanks for all the great work.

**Comment by julienduroure** [comment] 2019-05-14 04:46
This is maybe link to issue #461 about NLA that can have some issue in some cases

**Comment by julienduroure** [comment] 2020-01-13 12:17
Hello @aoedipus Can you please test again with a recent build of blender, for exemple with Blender 2.82 beta, that you can download here : https://builder.blender.org/download/

**Comment by julienduroure** [comment] 2020-01-26 09:08
Export seems to be OK, and I can't reproduce any issue. Without answer from this issue reporting, closing.
Don't hesitate to comment or create a new ticket if you still have issue with recent blender version

**Closed by julienduroure** 2020-01-26 09:08 UTC
Labels: Animation, ReTest with master, bug, exporter
