### ISSUE TITLE
Model is deformed after unchecking "Transform: +Y Up" in animation

### ISSUE THREAD

**Issue by terri0n** [KhronosGroup/glTF-Blender-IO#1597] opened 2022-03-25 11:14 UTC
I have a model and several animations in different files. When exporting the animation to gLTF, the "Transform: +Y Up" option made my model go towards up:
![With Y UP option](https://user-images.githubusercontent.com/63014185/160110188-4d8eb8d3-506e-4274-b0c6-321becbbb57a.png)

So I decided to uncheck it and the result is that the model gets deformed:
![Without Y UP option](https://user-images.githubusercontent.com/63014185/160110194-74d1c43e-75c7-40f8-8720-b8519715bfdd.jpg)

[Animation file](http://formulamanager.com/tennis/modelos/John/J_Forced_Backhand.glb)

**Comment by julienduroure** [comment] 2022-03-25 11:31
Hello,
- What version of Blender are you using? Please test with 3.2 alpha
- If you experienced some exporter issue, I need the .blend file to be able to reproduce

Unchecking the +Y at export make some not valid glTF files (that needs to be Yup). We probably need to remove it (at least from UI)

**Comment by terri0n** [comment] 2022-03-25 11:58
> What version of Blender are you using? Please test with 3.2 alpha
3.01. I will try that

> If you experienced some exporter issue, I need the .blend file to be able to reproduce
I just import it and export to gLTF. But I will save it in .blend with the 3.2 version

> Unchecking the +Y at export make some not valid glTF files (that needs to be Yup). We probably need to remove it (at least from UI)
With it checked, the animation is always oriented towards up, no matter how I rotate it before the exportation. How could I display it in the right direction?

**Comment by terri0n** [comment] 2022-03-25 12:39
Done. No differenbce with 3.2 alpha

[blend file](http://formulamanager.com/stuff/Forced_Backhand.blend)

**Comment by julienduroure** [comment] 2022-03-25 12:49
I am not sure to understand, I can't reproduce.
You file doesn't look like screenshots. There is no mesh, only empties.
After export/import, the character is still up.

Blend file:
![image](https://user-images.githubusercontent.com/1696020/160123544-2018eef3-b0cd-40c8-b3af-2f61d557643d.png)

After export/import:

![image](https://user-images.githubusercontent.com/1696020/160123679-8537caf2-f2e0-4bdc-a4b0-13389558cc19.png)

**Comment by terri0n** [comment] 2022-03-25 13:15
I use the animation in Three.js over a model in another file. I'm new to the 3D world and maybe I don't understand well some concepts :)

Probably if I merge the animation with the model in Blender it will show everything ok (I tried it with other animations). But, when I export it to use in Three.js, something changes and the result is different, as you can see in the captures. So I asume that the problem is in the exportation, but I may be wrong

**Comment by terri0n** [comment] 2022-03-26 22:22
I found the solution, although I don't understand it:

If I don't export the geometry (UVs and Normals), I can unmark +Y Up transform and the model doesn't get deformed :D

Thank you for your time

**Comment by julienduroure** [comment] 2022-04-12 14:46
I am still not able to reproduce, as we don't have any error with file you upload.
Not sure there is a bug here on Blender side.
If you have more information, don't hesitate to share it here.

**Comment by siliconvoodoo** [comment] 2022-04-14 06:27
I noticed that on my area lights, export with or without the option results in the same JSON output.
but only for the area lights that have undergone no rotation at all during edition.
Which means rotation is not a field that exists in the output because it's supposed to be all zeroes probably and therefore gets skipped by a sort of expressly minimalistic logic. But then, Y is up is usually applied by quaternion 0.7, 0, 0, 0.7 so if you don't export any rotation at all, the exporter has no chance to fixup the Y is up using that 0.7 quaternion.

(area lights are just nodes, they have no mesh, and they're not supported by the khr_lights extension but i have a plugin to copy the properties into custom properties so don't mind that, just think of it as a node, it applies the same for any node)

I suggest the possibility of export problem comes from the unjustified special case that skips orientation in case it has never been touched. to be verified.

**Comment by terri0n** [comment] 2022-04-15 10:40
Sorry, I don't understand the concept of "area lights"

What I underestand about your words is that the file lacks some information that some editors/viewers, like Blender, fill with default data. And others, like Three.js don't, or do it differently

Then I wonder... is there a way to normalize a model so that it has all the information that it needs?

I'm just trying to rotate the model 90 degrees since a lot of time now haha. But every solution I try produces a different problem: the scale is changed, the model gets deformed, it gets displaced... I'm a begginer in the 3D world and this kind of things discourages me :/

**Comment by siliconvoodoo** [comment] 2022-04-19 02:38
Don't worry, this message is addressed to blender programmers. (more precisely maintainers of gltf2_blender_gather_nodes.py).
line 483 may be suspicious:
`if rot[0] != 1.0 or rot[1] != 0.0 or rot[2] != 0.0 or rot[3] != 0.0:`
Also the combination with block from 103 to 116 making use of `__get_correction_node` just for extensions? why not unified handling of YUP?
Another suspicious line:
under object type "ARMATURE"
`            # fix rotation
            if export_settings[gltf2_blender_export_keys.YUP]:
                rot = child_node.rotation
                if rot is None:
                    rot = [0, 0, 0, 1]
`

**Comment by siliconvoodoo** [comment] 2022-04-19 02:49
@Cyp and @UX3D-becher probably are the main capable to investigate.

**Comment by julienduroure** [comment] 2022-04-19 05:10
@siliconvoodoo Please do not use ticket of someone else, as the problems may not be related. Please open a new one.

You should also test with 3.2 alpha, as you refered to part of code that not exist anymore on 3.2

**Comment by siliconvoodoo** [comment] 2022-04-20 06:30
@julienduroure I don't have a ticket and I don't intend to because I don't care. I am not side injecting my issue into this ticket, since I don't consider it to be my issue, but a vector of approach to understand the problem underlying OP's issue; and maybe you didn't notice, but what I did was try to help you kick start the debugging of OP's issue.

**Comment by siliconvoodoo** [comment] 2022-04-21 06:40
Ok I tried 3.2 and the behavior has radically changed. There are no more _Orientation children nodes, and the problem about nodes with 0 rotation doesn't appear anymore. My above analysis is indeed obsolete and needs to be redone.

**Comment by julienduroure** [comment] 2023-02-01 10:15
This ticket is quite old, and I am not able to reproduce the issue with the provided sample files.
Without any news within a month, I will close this ticket.

**Comment by julienduroure** [comment] 2023-03-27 14:01
Closing this ticket. Still not able to reproduce, and no news from user.

**Closed by julienduroure** 2023-03-27 14:01 UTC
Labels: question
