### ISSUE TITLE
Color changed where there is skeleton-animation

### ISSUE THREAD

**Issue by beibei1998** [KhronosGroup/glTF-Blender-IO#819] opened 2019-12-06 10:31 UTC
I have updated my glTF exporter to 1.1.20
And my blender is 2.81

When I exported glb, I found that the color of the part with skeleton-animation changed.
I updated exporter to make  skeleton-animation run successfully, but now the color is wrong compared to the one without skeleton-animation.
How can I get both correct color and animation?

**Comment by julienduroure** [comment] 2019-12-06 12:28
Hello,

Please follow guidelines and provide needed information to reproduce the issue. There is a template when you create a bug, please follow it.
Without a test case .blend, we will not be able to work on it.

For reminder, the template you have to follow : 

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**.blend file/ .gltf**
If applicable, a zipped folder containing a .blend file for exporter issues and a .gltf file for importer issues. Please take care to include all resources, such as textures in the .zip file.

**Version**
 - OS: [e.g. macOS, linux]
 - Blender Version [e.g. 2.79, 2.80 (2019-03-18)]

**Additional context**
Add any other context about the problem here.

**Comment by julienduroure** [comment] 2020-01-06 08:28
Well, I will close this ticket, because we don't have any answer since 1 month.
If you have some info to send us, don't hesitate to comment

**Closed by julienduroure** 2020-01-06 08:28 UTC
Labels: exporter, question
