### ISSUE TITLE
Geometry broken when appending certain object

### ISSUE THREAD

**Issue by Joe-Kerr** [KhronosGroup/glTF-Blender-IO#1625] opened 2022-04-14 06:40 UTC
**Describe the bug**
Whenever I append “trigger.blend” it breaks all the 2x3 walls, i.e. from “works.glb” to “broken.glb” (in “debug.blend”). It seems they are reset to a 2x2 cube. Issue happens in Win10 3d viewer and upon re-importing the glb into Blender.

**To Reproduce**
0 Download https://github.com/Joe-Kerr/TEMP_blender-gltf-issue
1. Open debug.blend
2. Export glb named "works.glb"
3. Mainmenu File->Append, choose trigger.blend, choose element in Objects
4. Export glb named broken.glb
5. Observe change form works.glb to broken.glb

**Expected behavior**
Geometry stays the same as rendered in Blender.

**.blend file/ .gltf**
https://github.com/Joe-Kerr/TEMP_blender-gltf-issue

**Version**
 - OS: Win10
 - Blender Version 3.1

**Comment by julienduroure** [comment] 2022-04-14 07:21
Hello,
Can you please check with blender 3.2 alpha ?
It seems to be solved, but I am not sure to get all your steps to reproduce
You can get a recent blender 3.2 alpha build here : https://builder.blender.org/download/daily/

**Comment by Joe-Kerr** [comment] 2022-04-19 07:48
Sorry @julienduroure for the unclear instructions. Updated my opening post.

**Anyway, your workaround was successful! :)**

However, I am a bit worried when using an alpha version. Is it possible to port the fixed exporter from alpha3.2 to stable 3.1? Can I just copy some files?

**Comment by julienduroure** [comment] 2022-04-20 06:25
Hello,
There is no easy way to officially backport fix from 3.2 to 3.1, because a big refactor happen between these 2 versions.
But, as you said, you can try on your own to copy/past all content of io_scene_gltf2 on your system.
Closing this ticket, because original bug is fixed

**Closed by julienduroure** 2022-04-20 06:25 UTC
Labels: question
