### ISSUE TITLE
ACCESSOR_NON_UNIT error in validator

### ISSUE THREAD

**Issue by AlbertoElias** [KhronosGroup/glTF-Blender-IO#372] opened 2018-06-10 16:38 UTC
I'm exporting a blender scene using the latest add on in master and then opening it in https://gltf-viewer.donmccurdy.com/ and I get the error 

`Cannot read property 'joints' of undefined`

The model has an armature and some animations. I'm attaching the gltf and the blender file. Thanks!

[broken_model.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2088037/broken_model.zip)

**Comment by julienduroure** [comment] 2019-09-17 04:51
Skin issue seems to be fixed, but now have gltf error : 
> ACCESSOR_NON_UNIT

**Comment by emackey** [comment] 2019-09-17 14:03
> Skin issue seems to be fixed, but now have gltf error :
> 
> > ACCESSOR_NON_UNIT

I know that one.  The model contains degenerate faces, and the exporter doesn't weed them out prior to export, resulting in zero-length normal vectors, which are invalid in glTF.

Quick fix is go into Edit Mode, menu, "Mesh" -> "Clean up" -> "Degenerate Dissolve".

**Comment by julienduroure** [comment] 2020-08-12 19:08
Well, this is a duplicate of #1138, let's continue the discussion on the other ticket

**Closed by julienduroure** 2020-08-12 19:08 UTC
Labels: bug, exporter
