### ISSUE TITLE
How to export height map after i implement parallax-mapping effect in blender

### ISSUE THREAD

**Issue by dandingol03** [KhronosGroup/glTF-Blender-IO#1674] opened 2022-06-24 07:13 UTC

**Comment by julienduroure** [comment] 2022-06-24 07:22
Hello,
Height Map is not something that is defined in glTF specification, so this is not possible to export "as-is".
Can you please share a simple blend file with your setup?

Currently, only normal map is exported. We planned (no timeline for now) to implement conversion from Bump map to Normal map (see #199)

**Comment by julienduroure** [comment] 2024-11-09 07:34
Closing this ticket as a duplicate of #199 , as the enhancement request to manage (by conversion) bump map to normal map is the same.

**Closed by julienduroure** 2024-11-09 07:34 UTC
Labels: question
