### ISSUE TITLE
blender 4.2 cannot export shapekey with amature

### ISSUE THREAD

**Issue by linrin07** [KhronosGroup/glTF-Blender-IO#2321] opened 2024-08-17 11:39 UTC
**Describe the bug**
 Cannot export shapekey with Amature

**To Reproduce**
Add a Cube
Set some shape keys
Add a Amature
Attach the Cube to Amature
Export to gltf
import the gltf file, the cube does not have any shape keys

**Expected behavior**
shapekey can be exported in 4.1.1 

**Screenshots**
the cube with shape key and amature
![image](https://github.com/user-attachments/assets/4427e900-686d-4af2-b7e8-b5922cb42d44)
modifier
![image](https://github.com/user-attachments/assets/978e943f-cc26-4445-82cf-d6d53e3d50a2)
gltf export settings
![image](https://github.com/user-attachments/assets/b0f5b97b-8e38-43cb-ab7b-b940d97c529f)
import glft file
![image](https://github.com/user-attachments/assets/05e4c16c-adc8-46ef-8b15-fa5dd299c2e1)

**Version**
 - OS: Win10 19045.4651
 - Blender Version 4.2

**Comment by julienduroure** [comment] 2024-08-17 15:15
Hello,
No bug here, and no change in behavior since 4.1
As described in tooltip, applying modifiers prevent exporting shapekeys, because of limitation in Blender api bpy.
Closing this ticket

**Comment by linrin07** [comment] 2024-08-18 04:16
> Hello, No bug here, and no change in behavior since 4.1 As described in tooltip, applying modifiers prevent exporting shapekeys, because of limitation in Blender api bpy. Closing this ticket

The only modifier is amature. There's no other modifier. In 4.1(and 3.6.8, 2.93), shapekeys can be exported with amature.

**Comment by julienduroure** [comment] 2024-08-18 12:04
Sorry, my bad.
I can reproduce now

**Closed** 2024-10-31 12:31 UTC
Labels: bug
