### ISSUE TITLE
Support for non-surface primitive modes (POINTS, LINES)

### ISSUE THREAD

**Issue by Siccity** [KhronosGroup/glTF-Blender-IO#1283] opened 2020-12-03 10:52 UTC
The GLTF spec supports the following primitive modes:
```
0 POINTS
1 LINES
2 LINE_LOOP
3 LINE_STRIP
4 TRIANGLES
5 TRIANGLE_STRIP
6 TRIANGLE_FAN
```

Right now it seems only primitive mode TRIANGLES is supported in the exporter.
For technical purposes it would be very useful to me if the exporter also supported POINTS and LINES.
I imagine checking primitive mode during export would behave something similar to this:
```python
if (mesh.HasFaces) mode = "TRIANGLES"
else if (mesh.HasEdges) mode = "LINES"
else mode = "POINTS"
```

**Comment by donmccurdy** [comment] 2020-12-04 07:06
There's work in progress here: https://github.com/KhronosGroup/glTF-Blender-IO/pull/717

**Comment by donmccurdy** [comment] 2020-12-04 07:07
Marking as duplicate of https://github.com/KhronosGroup/glTF-Blender-IO/issues/376.

**Closed by donmccurdy** 2020-12-04 07:07 UTC
