### ISSUE TITLE
Wrong object exported (classroom.blend)

### ISSUE THREAD

**Issue by harokyang** [KhronosGroup/glTF-Blender-IO#638] opened 2019-08-29 04:16 UTC
Using Blender 2.8
classroom.blend (the example file come with Blender)

Exported as gltf 2.0
Check with any gltf viewer app, no chairs in scene, but lots of door handles

Check the gltf file manually
All the object chair and its instances become object Box.024(the door handle)

Something wrong with the exporter

**Comment by julienduroure** [comment] 2019-08-29 04:50
This is a duplicate of #619 : 3 scenes are exported, but the active scene is the last exported.

But:: Something is wrong when animation is exported. Created #639 for this issue.

**Closed by julienduroure** 2019-08-29 04:50 UTC
Labels: duplicate

**Comment by harokyang** [comment] 2019-08-29 05:08
I checked all 3 scenes, none of them contain object chair but door handles

If I select the chair and enable export selected object option, I got 3 empty scenes

**Comment by julienduroure** [comment] 2019-08-29 05:20
The scene is using lots of particles and dupli-instances. This is a know limitation, will be manage in #500

**Comment by julienduroure** [comment] 2021-07-04 19:55
Seems to be fixed in #1378
