### ISSUE TITLE
rotated by +90° or -90° on the X axis

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF-Blender-IO#856] opened 2020-01-04 20:57 UTC
Exporting .blend file from #373 (by @swift502)
Seems to be correctly oriented on https://sandbox.babylonjs.com/
but badly on https://gltf-viewer.donmccurdy.com/

@donmccurdy Do you know if this is a known issue
@swift502 Can you please confirm that this is OK in babylonjs ?

**Comment by swift502** [comment] 2020-01-05 11:55
Yes it's fine in Babylon.

After inspecting the imported model, if I check the +Y up option in the export options, the scene gltf scene seems to be rotated on the X axis by -180° (PI/2). 
![image](https://user-images.githubusercontent.com/24359130/71779828-5b46a380-2fba-11ea-9e11-a68859b473ea.png)
Shouldn't it be 90 (PI/4)?

If I don't check the +Y up option, rotation is (0, 0, 0), which is probably correct right?

**Comment by swift502** [comment] 2020-01-05 12:57
I made some progress.
First I tried rotating the character manually, but it would rotate back again with the start of a new animation.

[Video](https://youtu.be/geKRwFJTiNk)

But then I fixed the issue by rotating my the root bone of my skeleton in edit mode, so that it's Y axis is pointing up.

![image](https://user-images.githubusercontent.com/24359130/71780324-710b9700-2fc1-11ea-8d8d-0664bf276fef.png)

So maybe Babylon ignores animation of the root bone? Or it's overriding the root bone rotation?

**Comment by donmccurdy** [comment] 2020-01-08 18:32
Taking the `.glb` file attached to the original comment in https://github.com/KhronosGroup/glTF-Blender-IO/issues/373, I see the same model orientation when playing the Idle animation in both viewers... the issue is very obvious in @swift502's video of course. How should I reproduce that?

**Comment by julienduroure** [comment] 2020-01-09 15:50
@donmccurdy I can reproduce using the .blend file of #373, and exporting it

**Comment by swift502** [comment] 2020-01-09 16:21
I can also reproduce using both 2.81 and 2.82 Alpha.

**Comment by donmccurdy** [comment] 2020-01-31 21:19
Alright, I'm confused. 😕

I can reproduce the problem in my viewer.  The model plays correctly in BabylonJS and the [glTF sample viewer](https://github.khronos.org/glTF-Sample-Viewer/), so I have to assume the problem is related to threejs.

What's weirder is that after running the model through [gltfpack](https://github.com/zeux/meshoptimizer#gltfpack) I no longer see the bug — the model is upright in all viewers.

`.glb` files attached for reference.

[Archive.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4141446/Archive.zip)

**Comment by donmccurdy** [comment] 2020-02-01 02:15
Filed as https://github.com/mrdoob/three.js/issues/18526.

**Comment by donmccurdy** [comment] 2020-02-04 16:18
@swift502 this isn't a real fix of course, but as pointed out in mrdoob/three.js#18526, the following modification in threejs does seem to fix the animations:

```js
const root = model.getObjectByName('root');
root.rotation.set(0,0,0);
```

**Comment by donmccurdy** [comment] 2020-02-05 04:12
We've confirmed this is a bug in three.js (link above). I'll close this issue out.

**Closed by donmccurdy** 2020-02-05 04:12 UTC
Labels: exporter, question

**Comment by donmccurdy** [comment] 2020-02-06 23:20
Will be fixed in upcoming threejs release r114, by https://github.com/mrdoob/three.js/pull/18543.
