### ISSUE TITLE
Incorrect armature scale and hierarchy

### ISSUE THREAD

**Issue by supagu** [KhronosGroup/glTF-Blender-IO#346] opened 2018-09-20 10:38 UTC
I have this armature in blender. I've scaled it down as it was too big and reset the transforms.

When I export as a DAE file this is the result:
![dae](https://user-images.githubusercontent.com/11153232/45812868-35878380-bd10-11e8-9f5f-f11d44fe99c6.jpg)
which is correct. Notice the red line on the left indicates a non-scaled box for size, and the box to the right is the same box just attached to the skeleton.
Also notice on the far right, the hierarchy from the DAE file matches blender.

![glb](https://user-images.githubusercontent.com/11153232/45812876-3b7d6480-bd10-11e8-8ffc-7cda8092bb5f.jpg)
Now this is the exported GLB. Notice the red line on the left indicates the non-scaled box which is correct. The box to the right is the same box attached to the skeleton - see it is way bigger. This is the size I would expect from the character before I scaled and applied the transform.
Also notice the far right, the hierarchy from the GLB is really weird broken up into multiple skeletons.

Here is my blender file with exported DAE and GLB files for debugging
[Stip.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/2400866/Stip.zip)

**Comment by donmccurdy** [comment] 2019-03-07 16:53
Transferring to new project repo, issue is reproducible.

**Comment by julienduroure** [comment] 2019-10-03 19:52
Seems to be solved with blender 2.81 alpha + future godot 3.2

**Closed by julienduroure** 2019-10-03 19:52 UTC
Labels: Skinning_&_Rigging, bug, exporter

**Comment by haosizheng** [comment] 2022-03-15 07:23
same issue here. The fbx is ok but glb error.
![image](https://user-images.githubusercontent.com/52849063/158326890-52ba4382-5e13-4c7c-abea-56a896ae41a3.png)

**Comment by julienduroure** [comment] 2022-03-15 07:31
@haosizheng You are commenting a ticket more than 2 years old, that is already solved
Please open a new ticket, and follow guidelines to provide needed information (blender version used, example .blend file to reproduce your issue, etc...)
Thanks
