### ISSUE TITLE
Getting Error on Importing A gltf file That I imported using blender 2.8

### ISSUE THREAD

**Issue by nabarun1011** [KhronosGroup/glTF-Blender-IO#535] opened 2019-06-08 11:41 UTC
**Describe the bug**
Everytime I am exporting my animated mesh to gltf, it is giving me an error. And not showing bones correctly and all animation actions are also not getting exported at first. For some mesh it exports all actions without any problem, but for some it doesn't.

**To Reproduce**
1. Export The Blend file I uploaded as gltf.
2. Make settings for an animated mesh. My settings are in screenshot below
3. Now import the exported .glb file

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/24879352/59146768-cd98da80-8a0f-11e9-8948-be99ba13629a.png)
![image](https://user-images.githubusercontent.com/24879352/59146772-d8536f80-8a0f-11e9-8ac8-58d4f0aad341.png)

![image](https://user-images.githubusercontent.com/24879352/59146750-a93cfe00-8a0f-11e9-9865-3c4e782775dc.png)

**.blend file/ .gltf**
[Worm.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3268458/Worm.zip)

**Version**
 - OS: Windows 10 Home Version 1809
 - Blender Version : 2.80 (sub 74) , commit date: 2019-06-06 23:23, hash: `rBaa003c73245f`

**Additional context**

Error :

Traceback (most recent call last):
  File "D:\Softwares\blender-2.80.0-git.aa003c73245f-windows64\2.80\scripts\addons\io_scene_gltf2\__init__.py", line 528, in execute
    return self.import_gltf2(context)
  File "D:\Softwares\blender-2.80.0-git.aa003c73245f-windows64\2.80\scripts\addons\io_scene_gltf2\__init__.py", line 549, in import_gltf2
    BlenderGlTF.create(self.gltf_importer)
  File "D:\Softwares\blender-2.80.0-git.aa003c73245f-windows64\2.80\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_gltf.py", line 41, in create
    BlenderScene.create(gltf, scene_idx)
  File "D:\Softwares\blender-2.80.0-git.aa003c73245f-windows64\2.80\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_scene.py", line 102, in create
    BlenderAnimation.anim(gltf, anim_idx, node_idx)
  File "D:\Softwares\blender-2.80.0-git.aa003c73245f-windows64\2.80\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_animation.py", line 34, in anim
    BlenderAnimation.anim(gltf, anim_idx, child)
  File "D:\Softwares\blender-2.80.0-git.aa003c73245f-windows64\2.80\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_animation.py", line 34, in anim
    BlenderAnimation.anim(gltf, anim_idx, child)
  File "D:\Softwares\blender-2.80.0-git.aa003c73245f-windows64\2.80\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_animation.py", line 28, in anim
    BlenderBoneAnim.anim(gltf, anim_idx, node_idx)
  File "D:\Softwares\blender-2.80.0-git.aa003c73245f-windows64\2.80\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_animation_bone.py", line 289, in anim
    BlenderBoneAnim.parse_rotation_channel(gltf, node, obj, bone, channel, animation)
  File "D:\Softwares\blender-2.80.0-git.aa003c73245f-windows64\2.80\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_animation_bone.py", line 166, in parse_rotation_channel
    animation.samplers[channel.sampler].interpolation
  File "D:\Softwares\blender-2.80.0-git.aa003c73245f-windows64\2.80\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_animation_bone.py", line 225, in fill_fcurves
    fcurve = action.fcurves.new(data_path=blender_path, index=i)
RuntimeError: Error: F-Curve 'pose.bones["Spine"].rotation_quaternion[0]' already exists in action 'Default_Pose_WormArmature.001'

location: <unknown location>:-1

**Comment by julienduroure** [comment] 2019-06-13 21:21
Hello,

This is a duplicate of #474 
On your bone "Spine", you have keyframes on quaternion AND on Axis angle. This is not recommanded to have keyframes on different rotation type. If you want to export, delete keyframes from Axis-angle.

In #474, we will enhance exporter to avoid this non valid gltf file generation
Thanks for reporting it!

**Closed** 2019-11-13 21:37 UTC
Labels: Animation, duplicate, exporter
