### ISSUE TITLE
Shape keys do not export in some cases (autosmooth?)

### ISSUE THREAD

**Issue by jitspoe** [KhronosGroup/glTF-Blender-IO#1267] opened 2020-11-21 02:52 UTC
**Describe the bug**
Trying to export a mesh with just a shape key.  Upon reimport, the shape keys are gone.

**To Reproduce**
1. Create a mesh.
2. Add a base and additional shape key.
3. Export GLTF

**Expected behavior**
The exported GLTF file should contain the shape keys.

**Screenshots**
Before export:
![image](https://user-images.githubusercontent.com/7751182/99865769-1435b280-2b7a-11eb-8c58-ee1894f214c0.png)
After import:
![image](https://user-images.githubusercontent.com/7751182/99865778-23b4fb80-2b7a-11eb-91ae-072f2f597b59.png)

**.blend file/ .gltf**
[fx_electricity1_shape_key_fail.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/5576905/fx_electricity1_shape_key_fail.zip)

Note: There's a door that exports the shape keys properly, but the electricity effect does not.  Only difference I think is that the door had an animation (door was appended from another blender file where the shape keys worked, just to test).

**Version**
 - OS: Windows 8.1
 - Blender Version: 2.90.1

**Comment by jitspoe** [comment] 2020-11-21 02:57
After further investigation, it looks like it was actually caused by autosmooth being on.

**Comment by julienduroure** [comment] 2020-11-21 07:37
I can't reproduce with recent blender version (2.91 beta)
Seems glb file you provided was generated with addon version 1.3.48 (and I confirm that it don't contains the SK).

Can you please confirm that the problem is gone with a recent version?

**Comment by jitspoe** [comment] 2020-11-22 02:51
Didn't appear to reproduce in 2.91 beta.  It does reproduce in the 2.83 LTS version, though.  Might be worth fixing there?

**Comment by julienduroure** [comment] 2020-11-23 10:30
Didn't check in details, but we performed lots of code refactoring since 2.83, so don't think this can be easily backported

**Comment by julienduroure** [comment] 2022-02-10 16:28
Quite old ticket already fixed ... let's close it

**Closed by julienduroure** 2022-02-10 16:28 UTC
Labels: question
