### ISSUE TITLE
GLTF Clamp base color (rBAe890169) breaks Mix node output

### ISSUE THREAD

**Issue by emkajeej** [KhronosGroup/glTF-Blender-IO#1807] opened 2022-12-12 14:00 UTC
**Describe the bug**
Since Blender 3.4, exporting a material that uses the Mix / Color Factor (previously MixRGB) node, the result is set to rgb(1,1,1) rather than the actual values.

The behaviour was changed [here](https://developer.blender.org/rBAe890169e0a62)

**To Reproduce**
1. Open a new Blend file
2. Create a material
3. Use a Mix node and set it to Color, Multiply, Factor of 1, and a random color on B.
4. Export as GLTF
5. Open in a GLTF viewer, e.g. [Khronos](https://github.khronos.org/glTF-Sample-Viewer-Release/)

**Expected behavior**
Color in the exported GLTF should be the same as in the Color Factor node

**Screenshots**

**.blend file/ .gltf**
[cubes.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/10208655/cubes.zip)
Red striped cube is Blender 3.4, Blue striped cube is Blender 3.3.
Open in the .glb [Khronos](https://github.khronos.org/glTF-Sample-Viewer-Release/) and notice how the Red cube is now White (due to rgb values being set to 1,1,1).

**Version**
 - OS: macOS 12.6.1
 - Blender Version 3.4.0

**Comment by julienduroure** [comment] 2022-12-12 14:33
Hello,
Thanks for reporting, but this bug is already fixed in master ( see https://developer.blender.org/rBA3fbcd35feb2a2c06ce1200bee648a9f39583d37e), and is not linked to the commit you mentioned. 

Root cause is change MixRGB node to Mix in core Blender.

The fix should be backported to 3.4.1 (not released yet)

**Closed by julienduroure** 2022-12-12 14:33 UTC
