### ISSUE TITLE
importing camera path doesn't work on 3.1.2 as far as i noticed.

### ISSUE THREAD

**Issue by SnowyFoxtrot** [KhronosGroup/glTF-Blender-IO#1666] opened 2022-06-12 19:17 UTC
When I import a glb/gltf camera path from Minecraft's replay mod it does not work.

1. Have the camera path.
2. Go To Blender.
3. Click on file.
4. Scroll down to import.
5. Click on glTF 2.0
6. See error.

For The camera path to be imported correctly and working.

Screenshots
![Screenshot_5](https://user-images.githubusercontent.com/107367486/173249345-36d143e2-00c8-4a75-b37a-b46b95560103.png)

.blend file/ .gltf
[Trying To make water physics.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/8886591/Trying.To.make.water.physics.zip)

Version
3.1.2

 - OS: Windows 
 - Blender Version 3.1.2

Additional context
i was trying to make a minecraft water physics animation but it didn't work when importing camera path.

**Comment by scurest** [comment] 2022-06-12 19:33
Looks like #1603. Should be fixed in Blender 3.2.

**Comment by julienduroure** [comment] 2022-06-13 08:13
Yes, confirmed that this should be solved in 3.2
Closing this ticket. Don't hesitate to comment if we missed something

**Closed by julienduroure** 2022-06-13 08:13 UTC
