### ISSUE TITLE
Skinned mesh in incorrect position

### ISSUE THREAD

**Issue by Yzou-NaO** [KhronosGroup/glTF-Blender-IO#614] opened 2019-08-09 07:04 UTC
**Describe the bug**
The skinned meshes display in the incorrect positions. 

**To Reproduce**
1. Load into blender
2. File -> Export ->glTF2.0
3. Check to skinning
4. Export

**Expected behavior**
![WeWork Helper20190809025420](https://user-images.githubusercontent.com/39986511/62760033-98634400-bab5-11e9-88e3-f3da1e5e9d3c.png)

**Screenshots**
![WeWork Helper20190809025350](https://user-images.githubusercontent.com/39986511/62760042-9c8f6180-bab5-11e9-8609-d8d3d7dcb127.png)

**.blend file/ .gltf**
[rabbit.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3485111/rabbit.blend.zip)

**Version**
 - OS: macOS
 - Blender Version 2.8.0

**Additional context**
The model is imported from .fbx. The position is correct with FBX2glTF (Facebook). 
I'm not sure whether it is a bug.

**Comment by julienduroure** [comment] 2019-08-09 16:34
Confirmed.
Seems to be linked to ears object location that are not initial before skinning.
Applying location ( Ctrl+A) on both ears seems to solve the issue

**Comment by Yzou-NaO** [comment] 2019-08-12 02:12
Thanks, but it doesn't work on this 
[test.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3490864/test.blend.zip), 
is this another problem?

**Comment by julienduroure** [comment] 2019-08-29 05:25
This will be fix after merge of branch https://github.com/KhronosGroup/glTF-Blender-IO/tree/fix_IBM

**Comment by julienduroure** [comment] 2019-09-13 20:05
Fixed now !

**Closed by julienduroure** 2019-09-13 20:05 UTC
Labels: Skinning_&_Rigging, bug, exporter
