### ISSUE TITLE
Alpha of Principle BSDF is ignored

### ISSUE THREAD

**Issue by biteworks** [KhronosGroup/glTF-Blender-IO#1133] opened 2020-07-21 09:52 UTC
**Describe the bug**
When trying to export an object with transparency I noticed that only the alpha value from the base color is taken into account.
The separate alpha value further down the shader is ignored during export. 

**To Reproduce**
1. Add a Principle BSDF shader to a object 
2. Change the alpha value in the bottom of the Principle BSDF to a value around 0.1
3. Change the Blend Mode of the material to "Alpha Blend"
4. The transparency should be visible in EEVEE viewport
5. Now export the geometry with default settings of the glTF 2.0 exporter
6. Open glTF inside of a viewer and the transparency should not be visible

**Expected behavior**
I wouldn't expect it to matter where I set the alpha value. The alpha value in the lower part of the shader (input[18]) should also be exportable

**Screenshots**
![Alpha-Export-Problem](https://user-images.githubusercontent.com/22855132/88039630-20681f80-cb48-11ea-9f08-ec715b91a728.jpg)

**.blend file/ .gltf**
[Alpha-Export-Bug.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/4952654/Alpha-Export-Bug.zip)

**Version**
 - OS: Windows 10
 - Blender Version 2.83 LTS

**Comment by scurest** [comment] 2020-07-21 10:25
Dupe of #784. The fix should be in the [2.90 alpha](https://builder.blender.org/download/).

>  I wouldn't expect it to matter where I set the alpha value. The alpha value in the lower part of the shader (input[18]) should also be exportable

Actually the alpha from the Base Color socket is now ignored, since it doesn't do anything in Blender.

**Comment by biteworks** [comment] 2020-07-21 11:04
IWith the latest exporter everything works now. Thanks!

**Closed** 2020-07-21 11:38 UTC
