### ISSUE TITLE
Export as glb corrupts the model and the workspace

### ISSUE THREAD

**Issue by HugoPeters1024** [KhronosGroup/glTF-Blender-IO#2171] opened 2024-03-22 22:12 UTC
### Describe the bug

Model and workspace are corrupted when exporting as glb.

### To Reproduce

1. Download `San Miquel 2.0` from https://casual-effects.com/data/
2. Export the zip file
3. Import the low poly obj in blender
4. Join all the nodes (Object -> Join)
5. Export as glb
6. Both the exported model as well as the workspace becomes corrupted.

### Expected behavior

The export is successful and does not affect the workspace.

### Screenshots
After joining the nodes and before exporting:

![before](https://github.com/KhronosGroup/glTF-Blender-IO/assets/22196124/e74fd13d-da48-483c-8de6-5ef70fba158e)

Directly after running an export as glb (the file is not re-imported or anything, just the export is run):

![after](https://github.com/KhronosGroup/glTF-Blender-IO/assets/22196124/50b4dbf6-f02a-48ed-8933-b459db4cfb09)

### .blend file/ .gltf (mandatory)

This download contains the `.obj` file with which to reproduce.

https://casual-effects.com/g3d/data10/research/model/San_Miguel/San_Miguel.zip

**Version**
 - OS: Ubuntu 22.04
 - Blender Version:

```
Blender 4.0.2
	build date: 2023-12-05
	build time: 08:48:50
	build commit date: 2023-12-05
	build commit time: 07:41
	build hash: 9be62e85b727
	build platform: Linux
	build type: release
	build c flags:  -Wall -Werror=implicit-function-declaration -Wstrict-prototypes -Werror=return-type -Werror=vla -Wmissing-prototypes -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wlogical-op -Wundef -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Wformat-signedness -Wrestrict -Wno-stringop-overread -Wno-stringop-overflow -Wnonnull -Wabsolute-value -Wuninitialized -Wredundant-decls -Wshadow -Wimplicit-fallthrough=5 -Wno-error=unused-but-set-variable  -std=gnu11 -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -ffp-contract=off -msse2  
	build c++ flags:  -Wuninitialized -Wredundant-decls -Wall -Wno-invalid-offsetof -Wno-sign-compare -Wlogical-op -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Werror=return-type -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wundef -Wcomma-subscript -Wformat-signedness -Wrestrict -Wno-suggest-override -Wuninitialized -Wno-stringop-overread -Wno-stringop-overflow -Wimplicit-fallthrough=5 -Wundef -Wmissing-declarations  -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -ffp-contract=off -msse2  
	build link flags:  -Wl,--version-script='/home/blender/git/blender-v400/blender.git/source/creator/symbols_unix.map'
	build system: CMake
```

**Comment by julienduroure** [comment] 2024-03-23 06:54
Hello,
I could not reproduce in 4.1 RC, but it seems that some mesh are not valid, so glTF can not export them correctly.

Can you please test with 4.1 RC (from here: https://builder.blender.org/download/daily/) ?
Run it from the console, and can you please past the result here.

Example of what you will probably find:

```
06:50:25 | WARNING: Mesh Water is not valid, and may be exported wrongly
06:50:25 | INFO: Extracting primitive: Water
Error: Array length mismatch (got 160602, expected more)
```

In that case, the issue is not on glTF exporter, but in obj importer. So we need to open a ticket on Blender tracker here: https://projects.blender.org/blender/blender

**Comment by HugoPeters1024** [comment] 2024-03-23 11:49
Thanks for looking into it! I ran the latest version from the command line and I can indeed reproduce the error that you saw too. If I do not join all the meshes beforehand, I can export to glb successfully although there are numerous warnings about invalid meshes, for example:

```
12:46:48 | WARNING: Mesh Portraits.001 is not valid, and may be exported wrongly
12:46:48 | INFO: Extracting primitive: Portraits.001
Error: Array length mismatch (expected 5304, got 5016)
```

I can accept that this model might not be entirely healthy and thus causes some issues. Do you still think it's worthwhile to upstream this information to the Blender developers?

**Comment by julienduroure** [comment] 2024-03-23 12:25
> Do you still think it's worthwhile to upstream this information to the Blender developers?

Sure, this is important to report it, as it seems that something went wrong during obj import (or obj is not valid, and Blender should manage it)

Let me know if you reported it. If not, I will do it myself


Seems we can close this ticket, as there is no glTF exporter issue here

**Closed by julienduroure** 2024-03-23 12:25 UTC
Labels: question

**Comment by HugoPeters1024** [comment] 2024-03-23 12:36
I created an account (needed to create an issue) but it says it can take up to 3 hours to verify my email. If you could report it for me that would be much appreciated :)

**Comment by julienduroure** [comment] 2024-03-23 13:02
Reported here : https://projects.blender.org/blender/blender/issues/119823
