### ISSUE TITLE
extension khr_ draco_ mesh_compression is not avaailable on this addon version

### ISSUE THREAD

**Issue by maxliu-rgb** [KhronosGroup/glTF-Blender-IO#1173] opened 2020-08-07 08:07 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**.blend file/ .gltf**
If applicable, a zipped folder containing a .blend file for exporter issues and a .gltf file for importer issues. Please take care to include all resources, such as textures in the .zip file.

**Version**
 - OS: [e.g. macOS, linux]
 - Blender Version [e.g. 2.82, 2.83, or build date]

**Additional context**

**Comment by julienduroure** [comment] 2020-08-08 13:48
Hello,
You didn't update the template with required information. Please fill the data, we can't help you without these info (importer or exporter? version of blender? version of the addon? error message? How to reproduce?)

**Comment by scurest** [comment] 2020-08-08 16:10
Almost surely a dupe of #252. The title is the error that appears when trying to import a Draco file

![error](https://user-images.githubusercontent.com/11024420/89714925-a0272400-d967-11ea-9e7f-470750881d63.png)

**Closed** 2020-08-10 03:40 UTC
Labels: draco, question
