### ISSUE TITLE
Assertion failure when exporting Class Room demo as glTF

### ISSUE THREAD

**Issue by Silverlan** [KhronosGroup/glTF-Blender-IO#1290] opened 2020-12-07 13:59 UTC
**Description**
The addon produces the following error in Blender 2.91.0 when trying to export the Blender Class room demo as glb:
```
Python: Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.91\scripts\addons\io_scene_gltf2\__init__.py", line 561, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.91\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 46, in save
    json, buffer = __export(export_settings)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.91\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 66, in __export
    json = __fix_json(exporter.glTF.to_dict())
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.91\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 1190, in to_dict
    self.animations)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.91\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 56, in from_union
    assert False
AssertionError

location: <unknown location>:-1
```

**To Reproduce**
1. Download Blender 2.91.0
2. Download the "Class room" demo by Christophe Seux (https://download.blender.org/demo/test/classroom.zip)
3. Export the scene as glb with the default settings

**Expected behavior**
Expected the scene to be exported. Instead, no glb-file is created and the addon crashes.

**Screenshots**
Here are my export settings:
https://pragma-engine.com/share/blender_2020-12-07_14-55-10.png

**.blend file/ .gltf**
Class room demo: https://download.blender.org/demo/test/classroom.zip

**Version**
 - OS: Windows 10 x64
 - Blender Version 2.91.0
- glTF-Blender-IO version: I've tried both the one that ships with Blender 2.91.0, as well as addon version 1.5.8

**Comment by julienduroure** [comment] 2020-12-07 14:08
Hello,
Thanks for reporting. This is a duplicate of #639 
We currently don't manage well when a same object is 1. animated 2. linked in multiple scenes.

**Closed by julienduroure** 2020-12-07 14:08 UTC
Labels: Animation, duplicate, exporter
