### ISSUE TITLE
Export: Alpha values are ignored when sourcefile has no transparency

### ISSUE THREAD

**Issue by emkajeej** [KhronosGroup/glTF-Blender-IO#2245] opened 2024-05-21 13:00 UTC
**Describe the bug**
When connecting the color socket of an image that does not have an alpha channel to the alpha socket of the Principled BSDF, Blender correctly interprets black pixels als 0 alpha.
When exported to a GLB, the tranparent pixels turn black.

This does not happen in Blender 4.0.

**To Reproduce**
1. Add a plane
2. Add a new material
3. Import a black and white image and connect the Color to the Alpha
4. Export as GLB/GLTF
5. Open in any GLB viewer, like https://gltf.report/

**Expected behavior**
The black and white values of the image are interpreted as alpha values, allowing for more granular control of the material's transparency.

**Screenshots**
<img width="1472" alt="material-setup" src="https://github.com/KhronosGroup/glTF-Blender-IO/assets/34506354/b1597ebc-6c7f-4f4f-a4cf-dcad70b890d3">

<img width="1001" alt="export-4 1 1" src="https://github.com/KhronosGroup/glTF-Blender-IO/assets/34506354/a3fa7d3b-ab88-4723-997c-6c2a424ec4d5">

Here is the same file exported from 4.0:
<img width="765" alt="export-4 0" src="https://github.com/KhronosGroup/glTF-Blender-IO/assets/34506354/967377d0-4ac9-43ec-acb6-a9ee37204902">

**.blend file/ .gltf (mandatory)**
[alphamap.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/15390136/alphamap.blend.zip)

**Version**
 - OS: macOS 14.5
 - Blender Version 4.1.1. 

**Additional context**
Issue does not occur in v < 4.1.

**Comment by julienduroure** [comment] 2024-05-21 18:01
Hello,
Yes, this is a duplicate of #2176 

In 4.0, the alpha channel was created only from Red channel of the texture.
In 4.1, no alpha is generated.
Agree that the behavior changed. Was not right, and still is not right, not in the same way.

This will be solved by #2176

**Comment by julienduroure** [comment] 2024-05-30 17:02
#2242 is now merged, closing

**Closed by julienduroure** 2024-05-30 17:02 UTC
Labels: duplicate
