### ISSUE TITLE
Export Compression Sub-Menu Missing

### ISSUE THREAD

**Issue by EliCDavis** [KhronosGroup/glTF-Blender-IO#2412] opened 2024-11-21 17:19 UTC
**Describe the bug**
With the latest release of blender (4.3) the compression submenu for exporting GLB is missing

**To Reproduce**
1. Go to export gltf 2.0
2. See missing

**Expected behavior**

Compression submenu to be there

**Screenshots**
![image](https://github.com/user-attachments/assets/59ae87dd-51b5-484b-96da-1c9a60f0f2ce)

**.blend file/ .gltf (mandatory)**

N/A

**Version**
 - OS: Windows 11
 - Blender Version 4.3

**Additional context**
N/A

**Comment by julienduroure** [comment] 2024-11-21 17:23
Hello,
This is a know issue on Blender side, that is already solved (and is candidate to be part of a 4.3.1 release)
See https://projects.blender.org/blender/blender/issues/130545

Closing this ticket, avoiding following multiple duplicate ticket for the same root cause.

**Closed by julienduroure** 2024-11-21 17:23 UTC
