### ISSUE TITLE
Create an armature with only empties

### ISSUE THREAD

**Issue by fire** [KhronosGroup/glTF-Blender-IO#1580] opened 2022-02-26 18:44 UTC
**Is your feature request related to a problem? Please describe.**

We discovered one neat trick that can allow us to export gltf animations with only empties. This is a feature of the industry standard animation interchange format we would like.

**Describe the solution you'd like**

If we put all the nodes below the `Armature` node into a new skin, we can export animations from Blender with only empties and it'll import into Blender as a armature.

**Describe alternatives you've considered**

1. The industry standard animation interchange format
2. BVH
3. .blend
4. https://github.com/artellblender/empties_to_bones

**Additional context**

Reference implementation https://github.com/fire/avatar-wellness/blob/main/addons/bvh/import_bvh.gd#L54

**Comment by fire** [comment] 2022-02-26 19:15
Here's the example glb produced.

[AvatarSample_A.vrm_melt_anim_only-b1360511181690057d76f1d0ad9317cb.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/8147338/AvatarSample_A.vrm_melt_anim_only-b1360511181690057d76f1d0ad9317cb.zip)

![image](https://user-images.githubusercontent.com/32321/155856188-98208861-9dd1-44f1-9a7e-f6fab1e1f2b8.png)

## References

* https://github.com/hurumeki/electron-pronama-chan/blob/master/assets/pronama/motion/melt.vmd
* https://github.com/madjin/vrm-samples/blob/master/vroid/AvatarSample_A.vrm

**Comment by julienduroure** [comment] 2022-02-28 06:19
Hello,
Not sure to fully understand what you said, because you mix import / export considerations.

But, please test with https://builder.blender.org/download/experimental/gltf_vtree/

Select the armature, and export using "Include > Limit to Selected Object", it will export each bone as Empty, and export animations as well.
Seems this is your requirement?

**Comment by fire** [comment] 2022-02-28 06:39
Let me check.

**Comment by fire** [comment] 2022-02-28 06:41
While I wait for the 10 minute download..

1. Exporting empties from Blender exists.

Delete the meshes from scene and export. Leave the armature as is.
  
2. This exported glb will probably fail to import as an armature and instead of skeletal animation it becomes empty animation

**Comment by julienduroure** [comment] 2022-02-28 07:07
Ok, seems I get it.
2 possibilities here:

- Force skin data to be created and exported, even if no meshes are exported. I first have to check if the glb is still a valid file regarding glTF 2.0 specification

- Force to import a glb file with only empties as an armature.

For import, I don't want to make it available by default, as this is a custom interpretation of content of the file. But it should be able to perform it on a user extension addon.

**Comment by fire** [comment] 2022-02-28 08:35
> Force skin data to be created and exported, even if no meshes are exported. I first have to check if the glb is still a valid file regarding glTF 2.0 specification

I believe our interpretation of putting armature joints into a global skin is valid. Can you check?

**Comment by julienduroure** [comment] 2022-02-28 09:14
This is a duplicate of #822

**Closed** 2022-02-28 09:56 UTC
Labels: question
