### ISSUE TITLE
Armatures included in .glb file even when "only selected objects" checked

### ISSUE THREAD

**Issue by jcarlosrc** [KhronosGroup/glTF-Blender-IO#1489] opened 2021-11-10 00:09 UTC
**Describe the bug**
Armatures are included in the  exported .glb file even if user clicked the "only selected objects" option. Even armatures with no relation at all with the object to export.

**To Reproduce**
1. Create a new mesh and some armatures.
2. Try to export as gltf 2.0 .glb only the mesh.
3. Check the resulting file, it has included the armatures.

**Expected behavior**
Only selected objects should be exported.

**Screenshots**
<img width="960" alt="bug-report-rings-01" src="https://user-images.githubusercontent.com/8985409/141025082-949d7128-e344-43c0-b15a-efcb812c5b5a.png">

<img width="521" alt="bug-report-rings-02" src="https://user-images.githubusercontent.com/8985409/141025089-1c5c55a8-ae99-4a33-a0e6-1ace969f5b86.png">

**.blend file/ .gltf**
Here the .blend and exported .glb file
[bug-report-armatures.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/7508787/bug-report-armatures.zip)

**Version**
 - OS: Windows 10
 - Blender Version 2.93.5

**Additional context**
Blender 2.82a did not have this problem.

**Comment by julienduroure** [comment] 2021-11-10 06:22
Duplicate of #1298 
This is already solved in recent version (master / future v3.0)

**Closed by julienduroure** 2021-11-10 06:22 UTC
Labels: duplicate
