### ISSUE TITLE
Exported object with multiple materials has only one material assigned

### ISSUE THREAD

**Issue by revyTH** [KhronosGroup/glTF-Blender-IO#170] opened 2018-12-15 16:35 UTC
Hi, I have an object exported from Unity in glTF format which has 2 material, each material with different textures. When imported into Blender one material is assigned to the whole object, while the other material is unused.
The same object loaded in three.js is loaded with the two materials assigned correctly.

[Level.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2682858/Level.zip)

**Comment by julienduroure** [comment] 2018-12-15 16:54
I can't reproduce.
I have 24 faces assigned to HD_Wall_01_Norm_mod, and 48 faces assigned to HD_Wall_02_Norm_mod.
Can you please shared to .blend file ? 
What version of blender do you use ?

**Comment by julienduroure** [comment] 2018-12-15 17:57
(Seems that some TEXTCOORD are not well assigned in HD_Wall_01_Norm_mod). Will check it

**Comment by revyTH** [comment] 2018-12-15 18:14
Hi @julienduroure, I've attached the .blend file.

[Level.blend.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2682954/Level.blend.zip)

This is the result I got in Blender after importing the model:

![screenshot 2018-12-15 at 19 12 12](https://user-images.githubusercontent.com/26633801/50046077-98818000-009d-11e9-8456-8a46360f942b.png)

![screenshot 2018-12-15 at 19 12 26](https://user-images.githubusercontent.com/26633801/50046080-a33c1500-009d-11e9-9431-a06d80d76966.png)

**Comment by julienduroure** [comment] 2018-12-15 18:47
On your file, both materials are assigned. So I am not sure to anderstand your problem.
Do you have a screenshot from Unity?

**Comment by revyTH** [comment] 2018-12-15 19:03
This is the result loading .glb + textures on [https://gltf-viewer.donmccurdy.com](url), and that's how the model looks in Unity.

![screenshot 2018-12-15 at 20 01 46](https://user-images.githubusercontent.com/26633801/50046479-61629d00-00a4-11e9-8a2e-4d1f4dd7a0e6.png)

**Comment by julienduroure** [comment] 2018-12-15 22:06
Should be fixed now!

**Closed** 2018-12-15 22:06 UTC
Labels: bug, importer, question
