### ISSUE TITLE
Model animation imports incorrectly

### ISSUE THREAD

**Issue by mikejsavage** [KhronosGroup/glTF-Blender-IO#509] opened 2019-05-30 21:42 UTC
Only one part of the model animates, the same model animates correctly on https://gltf-viewer.donmccurdy.com/

**Screenshots**
![image](https://user-images.githubusercontent.com/579299/58666501-c1d45680-8333-11e9-9235-4c27043cfc4b.png)

**.blend file/ .gltf**
[bigvic.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3238846/bigvic.zip)
Also contains the FBX which I converted to glTF

**Version**
 - OS: Linux/Windows
 - Blender Version 2.80.190529.fee600f47980-1

edit: same behaviour with 30th May Blender and git head of the gltf plugin

**Comment by julienduroure** [comment] 2019-05-31 08:14
Probably duplicate of #331

**Closed** 2020-01-23 21:07 UTC
Labels: duplicate, enhancement, importer
