### ISSUE TITLE
Keyframe Interpolation issue of exported file? 

### ISSUE THREAD

**Issue by gonnavis** [KhronosGroup/glTF-Blender-IO#1436] opened 2021-07-19 11:28 UTC
**Describe the bug**
Hello, I found that if uncheck "Always Sample Animation" ( thus just export keyframes and interpolation function ), the animation will has problem.
![image](https://user-images.githubusercontent.com/10785634/126149889-52d67626-dd9a-422f-b87a-006efbfa5c12.png)

**To Reproduce**
1. Download this blender file.
[Keyframe Interpolation issue.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/6840270/Keyframe.Interpolation.issue.zip)
2. Open a.blend and play the animation. You can see the blue box go through the top of the red box smoothly.
2. Export gltf/glb with "Always Sample Animation" unchecked.
3. Open it with Win10 3D Viewer or online gltf viewers
    https://github.khronos.org/glTF-Sample-Viewer-Release/
    https://gltf-viewer.donmccurdy.com/
    https://modelviewer.dev/editor/
    https://sandbox.babylonjs.com/
    https://playcanvas.com/viewer    
4. You can see the blue box paused on top of the red box for a short period.

**Expected behavior**
Whether check or uncheck "Always Sample Animation", all played smoothly in Win10 3D Viewer and online gltf viewers.

**Screenshots**
![image](https://user-images.githubusercontent.com/10785634/126153368-b2ab74c6-d4c4-4d85-ab98-0a4c97f690df.png)

**.blend file/ .gltf**
[Keyframe Interpolation issue.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/6840270/Keyframe.Interpolation.issue.zip)

**Version**
 - OS: [ Windows10 ]
 - Blender Version [ 2.93.1 ]

**Additional context**
If export gltf/glb with "Always Sample Animation" checked ( thus baked to per frame animation datas ), will looking smoothly with Win10 3D Viewer and all the online viewers, as the origin a.blend file looked in Blender.

**Comment by julienduroure** [comment] 2021-08-11 15:59
Confirmed.
One more test : Reimporting in Blender -->Seems to be smooth...
![image](https://user-images.githubusercontent.com/1696020/129063042-ad2d467d-d6b9-4474-abd6-373b6436a13c.png)

**Comment by julienduroure** [comment] 2022-08-11 14:13
Closing, this is now solved

**Closed by julienduroure** 2022-08-11 14:13 UTC
Labels: bug, exporter, Animation
