### ISSUE TITLE
Animation export is broken

### ISSUE THREAD

**Issue by ZanQdo** [KhronosGroup/glTF-Blender-IO#583] opened 2019-07-09 02:08 UTC
**Describe the bug**
Simple animation is not exported correctly from Blender

**To Reproduce**
Export an animated cube and import back.
The action is not imported at all.

When opening the file on https://sandbox.babylonjs.com/ the action will be present but the animation count will be 0, and the end frame will be a negative value. The action will not play.

![image](https://user-images.githubusercontent.com/999476/60926685-91ea6e00-a264-11e9-9834-2d809e182491.png)

![image](https://user-images.githubusercontent.com/999476/60926672-826b2500-a264-11e9-8291-ef85542c3c2d.png)

These files where created with a recent Blender 2.8 build

.blend file
[AnimExport.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3374984/AnimExport.zip)

.gltf file
[anim.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3370872/anim.zip)

**Version**
 - Blender Version 2.80 (2019-07-08)

**Comment by MiikaH** [comment] 2019-07-09 22:32
The attached .gltf file seems to contain two duplicated versions of the node. Both share identical name and mesh, but only other one is animated. Only the non-animated version is included in the scene.

**Comment by ZanQdo** [comment] 2019-07-09 23:04
Confirmed, after manually removing duplicate nodes the files load correctly

**Comment by pjoe** [comment] 2019-07-10 08:37
Seems to be caused by #561. The node cache breaks because the animation gather now calls with different params (None for blender_scene) and then creates a new node instead of using the existing one :S

**Comment by ZanQdo** [comment] 2019-07-11 16:58
I hope this can be fixed soon before the Blender RC since animation export is completely broken even on the simplest of cases

**Comment by emackey** [comment] 2019-07-11 17:33
The RC is due out today.  I don't think this fix is going in RC1, but I would expect some more bugs & fixes to come in before the next Release Candidate comes along.

**Comment by jedStevens** [comment] 2019-07-11 20:01
I would also like to chime in about the broken animation.

Here is a gif showing what the animation looks like after it has been imported to the Godot engine. When I import it back into blender there is no animation at all, but I mostly care about getting my animations **out** of blender.

![Peek 2019-07-11 15-55](https://user-images.githubusercontent.com/6509081/61081195-a9f0f780-a3f4-11e9-9551-0c69e1202ead.gif)

This just seems wrong. I'm noticing that the bouncing up and down in the torso should instead be a rotation as I didn't animate an idle cycle this terrible.

Any ideas?

**Comment by julienduroure** [comment] 2019-07-11 20:26
@jedStevens Please report a complete bug report, as requested :
- provide a .blend file
- what export options are you using ?

Please first test with "always sample animations" option at export.

**Comment by julienduroure** [comment] 2019-07-11 21:02
This is now fixed here.
Here is info about merge into blender : https://lists.blender.org/pipermail/bf-committers/2019-July/050047.html
(we are in master freeze, so I hope it will be merged before release)

**Closed by julienduroure** 2019-07-11 21:02 UTC

**Comment by ZanQdo** [comment] 2019-07-11 21:09
@julienduroure Thank you

**Comment by ZanQdo** [comment] 2019-07-12 18:56
@julienduroure it appears we got the goahead https://lists.blender.org/pipermail/bf-committers/2019-July/050050.html
