### ISSUE TITLE
GLTF Export Sometimes Modifies Animation (not export bug)

### ISSUE THREAD

**Issue by Nubsy** [KhronosGroup/glTF-Blender-IO#1386] opened 2021-04-29 19:48 UTC
**Describe the bug**
When exporting my animated mesh, my character's right leg is rotated in both the exported file and in the editor after exporting. (Note: Changes are immediate in the editor, no re-import required.) The changes are apparent across all of the Actions in the file.

**To Reproduce**
1. Open File (Generic Character.zip is linked below)
2. Click on File -> Export -> gltf
3. Use default export settings
4. Wait for export to complete
5. Observe right leg's rotation after export completes

**Expected behavior**
Exporting an animated mesh should not make changes to the scene

**Screenshots**
https://i.stack.imgur.com/rLKpW.gif

**Version**
 - OS: Windows 10
 - Blender Version 2.92.0

**Additional context**
I'm new to animation and am using Rigify. I posted the following question to the Blender Stack Exchange and was told to report this as a bug by a commenter.
https://blender.stackexchange.com/questions/221035/exporting-to-gltf-causes-leg-to-twist-how-can-this-be-prevented
It is entirely possible that I'm doing things in the wrong way, but I still wouldn't expect an export to change the contents of my file, no matter how egregious my mistake is. 
[Generic Character.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/6401200/Generic.Character.zip)

**Comment by julienduroure** [comment] 2021-05-02 08:02
Here is what happen:

- Open your file
- In Dopesheet, change the opened action (idle.loop) to landing
- In Dopesheet, go back to idle.loop
- You can see that your animation (check right leg) is changed

This happen because some of your actions as less keyframed channels than other, so the less keyframed actions keep the last value used for unkeyframed channels. This is how blender works, so not sure we can considered as an export bug.

**Comment by DavidDufour** [comment] 2021-12-18 23:56
I believe I am seeing a similar issue where the gltf exporter in Blender is moving the rig once the export is complete. Additionally when I load the glb file into a view many of the animations appear different from how they appear in Blender.
I've tried playing with different settings, pushing down vs stashing, clearing out all the animations and re-adding them and I just can't figure out what I did to mess up exporting.

Original pose in Blender for reference. Entire rig keyframed:
![0 animation pose](https://user-images.githubusercontent.com/4563772/146658547-e3916e3a-3e1a-477b-a329-51033584ad3d.png)
Zeroing out the rig before exporting:
![1 zeroed out rig](https://user-images.githubusercontent.com/4563772/146658548-4464559a-791b-419c-96af-39930ee4e1ca.png)
Export settings:
![2 export settings](https://user-images.githubusercontent.com/4563772/146658549-27b4c5ea-03eb-48ea-8d1f-3530b1887b1e.png)
Model changing pose automatically when the export finishes:
![3 post export](https://user-images.githubusercontent.com/4563772/146658550-362d6ecb-9177-4f71-9229-7c67dd4083a1.png)
Default pose in https://gltf-viewer.donmccurdy.com/
![4 gltf viewer](https://user-images.githubusercontent.com/4563772/146658551-bc486b0c-dada-4cfe-9b59-ebf2464810e7.png)
Broken animation in https://gltf-viewer.donmccurdy.com/
![5 gltf viewer animation](https://user-images.githubusercontent.com/4563772/146658552-231a0d62-a301-4c2d-90a2-814e6eccad4b.png)
Broken animation in https://sandbox.babylonjs.com/
![6 babylon gltf viewer animation](https://user-images.githubusercontent.com/4563772/146658553-3dbe953c-6f68-457e-ad2b-faf340c20b2b.png)

**Comment by julienduroure** [comment] 2021-12-19 06:23
As explained in my comment, this is not a bug, but a misunderstand how Blender works.
Please provide your blend file if you want me to check what happen in your case

**Comment by DavidDufour** [comment] 2021-12-19 14:36
I've uploaded the files here, thank you so much for looking, I'm having trouble understanding animations for games in Blender.

https://discourse.threejs.org/t/gltf-not-animated-properly/14765/14

**Comment by DavidDufour** [comment] 2021-12-19 17:36
Okay so I tried reproducing what I was seeing with just two bones.

I was able to reproduce pose staying after unlinking actions (this is expected behavior in Blender).
I was able to reproduce going from a zeroed out rig to a random action after exporting to gltf (annoying but not important).
**I was NOT able to reproduce selecting a single animation in the gltf viewer and having it be different from what I was seeing in Blender (this is the issue I care about).**

Load glb into viewer https://gltf-viewer.donmccurdy.com/
[untitled.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/7741242/untitled.zip)
If you select any single animation in the viewer, it will bend a bone by 45 degrees as expected.
If you playAll and see that left block adds it's animations and the right block takes the average of it's animations. This is expected behaviour because the left block only has key frames for the moving bones while the right block has key frames for every bone even if it doesn't move.
While interesting, this doesn't matter to me because I am never playing more than one animation at a time.

**I can't figure out for my original files above in blend.zip, why any single animation looks different from Blender to the gltf viewer. It appears that information from one animation is being stored in another.**

**Comment by DavidDufour** [comment] 2021-12-20 02:49
I looked at the samples in the "Fall" animation in the gltf file and compared it to a gltf file with only one stashed animation and they have different input and output values.
[gltf.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/7742274/gltf.zip)

**Comment by julienduroure** [comment] 2021-12-20 06:30
Hello,
Yes, I can confirm that this is exactly the same behaviour than the original report.
There is no bug in export here.
When you switch from multiple action in Blender where all bones are not keyed, non keyed channels in your destination action will keep values they have at time of switching action.
This is how Blender work, no exporting bug here.

One thing that can be done here is to reset TRS of bones just after switching to new action.

**Comment by DavidDufour** [comment] 2021-12-21 04:17
Thank you for the help @julienduroure! I added a function to the addon to reset the pose after each animation is gathered from the action. All of my animations look good now without any information bleeding over from the previous action.

glTF-Blender-IO\addons\io_scene_gltf2\blender\exp\gltf2_blender_gather_animations.py
`
def __reset_pose(blender_object, export_settings):
    if not export_settings['export_reset_pose']:
        return 

    # Remove the action from the object so the stored action's data isn't removed
    if blender_object.animation_data and blender_object.animation_data.action:
        blender_object.animation_data.action = None

    # Reset pose
    if blender_object.pose and blender_object.pose.bones:
        for bone in blender_object.pose.bones:
            bone.matrix_basis = Matrix()
`

**Comment by DavidDufour** [comment] 2021-12-22 16:48
Something else that helped me was to set a key frame for every bone in every layer (I wasn't looking at every layer before) and then deleting the keyframes I didn't need. Not sure why it helped though.
![image](https://user-images.githubusercontent.com/4563772/147126843-5dacb6f2-1e47-4e51-b03b-c5a5d9e3fc0b.png)

**Comment by julienduroure** [comment] 2022-01-10 10:45
Discussion about how to manage will place in #1047

**Comment by julienduroure** [comment] 2022-10-06 04:32
We can now close this ticket. Non keyed bones are not reset to rest pose when switching actions

**Closed by julienduroure** 2022-10-06 04:32 UTC
Labels: enhancement, exporter
