### ISSUE TITLE
export issues from blender 2.8 beta

### ISSUE THREAD

**Issue by spiraloid** [KhronosGroup/glTF-Blender-IO#114] opened 2018-11-30 00:01 UTC
I did a quick run through of the beta to try and verify everything is working properly.  But a few things seems to be broken getting a GLTF scene exported and imported properly into various viewers.  I figured some test data might help so:   I've zipped an archive of the blender scene, textures and the gltf and glb exports files if it's usefull for testing.

the .scene contains an animated skinned mesh, a point, spot and directional light and a camera.

[runthrough_test.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/2631337/runthrough_test.zip)

if everything exported correctly the it should look like the image on the left.

![image](https://user-images.githubusercontent.com/36362743/49259764-9954b980-f3ef-11e8-98ce-3f16a0f6e88c.png)

unfortunately, not 1-to-1 yet, but very close.

![image](https://user-images.githubusercontent.com/36362743/49259952-3adc0b00-f3f0-11e8-93c5-5c7f7e85936b.png)

Issues.
-the camera does not come across 
-the direction light (red) doesn't seem to have the correct rotation.
-looks like the apply modifier export option didn't apply the subdivision on the sphere, 
-the HDR environment map did not export.

Some of these could be a viewer issues:  so I started a thread here as well:  https://github.com/donmccurdy/three-gltf-viewer/issues/120#issuecomment-442989532

**Comment by donmccurdy** [comment] 2018-11-30 00:07
> the camera did not seem to export properly 

I think this is an exporter issue, I've confirmed my viewer is orienting the official camera samples correctly. if lights and cameras are handled the same way, then the light direction may be an exporter issue as well.

> the HDR environment map did not export.

These aren't supported — only spot, point, and directional lights.

> looks like the apply modifier export option didn't apply

Yeah this is an open bug, see https://github.com/KhronosGroup/glTF-Blender-IO/issues/112.

**Comment by UX3D-schmithuesen** [comment] 2018-11-30 15:41
#114 has been merged so camera and light should be fine now. Since the other points are separated issues or not supported, I will close this.

**Closed by UX3D-schmithuesen** 2018-11-30 15:41 UTC
Labels: bug, exporter

**Comment by spiraloid** [comment] 2018-11-30 17:49
Excellent!

**Comment by julienduroure** [comment] 2018-12-01 05:06
Is now merge with Blender repo, will be available next build
