### ISSUE TITLE
Armature - BVH - GLTF - ThreeJS

### ISSUE THREAD

**Issue by StudioOchi** [KhronosGroup/glTF-Blender-IO#839] opened 2019-12-18 01:39 UTC
**Describe the bug**
The bug appears when targetting the skeleton in ThreeJS and the mesh seems to behave sweird, like pulled up or the bones move in different directions as well, I have tried different settings while exporting and nothing seems to work out perfectly.
While I managed to solve the Mixamo scale issue, by Importing FBX in Blender, then exporting to BVH and finally import BVH in scale .01
I haven't been able to fix the animations in threejs
**To Reproduce**
I got this tester link that developers team gave me to try out the models and armatures for production.
1. Go to 'http://bvhgltf.mobivatar.com/'
2. Click on 'add files'
3. Once you put both files it goes to the viewer.
4. Scale and set on/off the RetargetClip to see different results.

**Expected behavior**
The animations always behave differently, some work a bit better though. They should follow the skeleton properly as they show in Mixamo and in Blender.

**Screenshots**
![GitHub_BVHGLTF (1)](https://user-images.githubusercontent.com/58912789/71047863-e106ca00-2145-11ea-935c-2bf8dda5cd2f.png)
![GitHub_BVHGLTF (5)](https://user-images.githubusercontent.com/58912789/71047864-e106ca00-2145-11ea-9397-8fb3e201c329.png)
![GitHub_BVHGLTF (2)](https://user-images.githubusercontent.com/58912789/71047865-e106ca00-2145-11ea-9b92-5271236bb75a.png)
![GitHub_BVHGLTF (3)](https://user-images.githubusercontent.com/58912789/71047866-e106ca00-2145-11ea-8582-1076cb950c5f.png)
![GitHub_BVHGLTF (4)](https://user-images.githubusercontent.com/58912789/71047867-e19f6080-2145-11ea-8f55-24116eed9f5c.png)

**.blend file/ .gltf**
[GithubBVHGLTF_Issue001.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3976218/GithubBVHGLTF_Issue001.zip)
If applicable, a zipped folder containing a .blend file for exporter issues and a .gltf file for importer issues. Please take care to include all resources, such as textures in the .zip file.

**Version**
 - OS: Windows & Mac
 - Blender 2.81

**Additional context**
1. Animations were imported from mixamo, applied to new objects and exported separately from the skeleton, however, sometimes the GLTF file brings the animation with it wich makes it seem fine but it ignores the skeleton completely. So when adding another animation it keeps reproducing the same one.
2. They have told me as well that the object calls for more bones than the skeleton brings sometimes. 
3. Also some versions call for bones called mixamo... while bones are called mixamo:... ( **:** ) not included in the mesh information.
4. The Viewer link was provided for testing, I got permission to share so that you can check out the code in case there's something there that can be improved.

**Comment by julienduroure** [comment] 2019-12-18 05:24
Hello,
This is a duplicate of #783
You can find a workaround on #783 comments ([here](https://github.com/KhronosGroup/glTF-Blender-IO/issues/783#issuecomment-558494123)) before the bug/enhancement is fixed

**Comment by donmccurdy** [comment] 2019-12-18 18:55
(Closing, as #783 will remain open until this is fixed)

**Closed by donmccurdy** 2019-12-18 18:55 UTC
Labels: Animation, Skinning_&_Rigging, duplicate, exporter
