### ISSUE TITLE
Textures not exported by python script

### ISSUE THREAD

**Issue by Yamakaky** [KhronosGroup/glTF-Blender-IO#1479] opened 2021-10-19 10:40 UTC
**Describe the bug**
I use the following script to export to GLTF:
```python
import bpy
import sys
from pathlib import Path

argv = sys.argv
argv = argv[argv.index("--") + 1 :]  # get all args after "--"

filename = Path(argv[0])

bpy.ops.wm.open_mainfile(filepath=str(filename))
bpy.ops.export_scene.gltf(
    filepath=str(filename.with_suffix(".gltf")),
    export_format="GLTF_EMBEDDED",
    export_yup=True,
)
```
With the default blender cube with any texture applied, I get the following, and the export file doesn't contain the texture:
```
Blender 2.93.5 (hash a791bdabd0b2 built 2021-10-13 00:53:14)
Read prefs: /home//.config/blender/2.93/config/userpref.blend
Read blend: models/untitled.blend
'/usr/bin/2.93/python/lib/python3.9/site-packages/libextern_draco.so' does not exist, draco mesh compression not available
10:31:49 | INFO: Starting glTF 2.0 export
10:31:49 | INFO: Extracting primitive: Cube
10:31:49 | INFO: Primitives created: 1
10:31:49 | WARNING: Image '<bpy_struct, Image("ds5.png") at 0x7f7e23485408>' has no color channels and cannot be exported.
10:31:49 | INFO: Finished glTF 2.0 export in 0.004320383071899414 s
```
It works fine if I export using the GUI. Am I missing something?

**To Reproduce**
1. Create new blender file, add a cube, add a texture to the cube.
2. Run `blender --background --python export.py -- <model>.blend`
3. Open the gltf file and list the textures

**Expected behavior**
The gui and python script should both generate the same result.

**Version**
 - OS: archlinux
 - Blender Version: 2.93.5

**Comment by Yamakaky** [comment] 2021-11-12 16:04
Sorry for the late response. Here it is with another texture: https://tmp.chocolytech.info/blender-bug.zip

**Comment by julienduroure** [comment] 2021-11-20 15:05
Sorry, but I can't reproduce with your file neither:

![image](https://user-images.githubusercontent.com/1696020/142731252-75642811-7cd9-4cf8-a93d-a46248c36922.png)

**Comment by julienduroure** [comment] 2021-12-13 14:08
Not sure what I did last time, but I can reproduce now.
Seems to be an Blender API issue, that doesn't retrieve texture (and even some node) correctly when used in background.
I will open some issue in Blender tracker.

**Comment by cesarizu** [comment] 2022-01-28 20:39
@julienduroure did you end up opening this issue on the blender issue tracker? Could you share a link to that?

**Comment by julienduroure** [comment] 2022-02-06 10:39
Here is the ticket:
https://developer.blender.org/T95550

**Comment by adoug** [comment] 2023-01-05 23:45
Has anyone found a solution for this, I am trying to export gltf but running this in docker and it does not export textures?

**Comment by julienduroure** [comment] 2023-05-24 14:22
Hello,
I am no more able to reproduce with recent version of Blender.
Closing this ticket.
(Note: On your test case, your blend file saved image path in absolute paths, so I had to remap it before testing)

Feel free to open a new ticket if you are still facing issues

**Closed by julienduroure** 2023-05-24 14:22 UTC
Labels: exporter, Material, Blender
