### ISSUE TITLE
Cameras and lights get exported as 2 nodes, using just a node should be enough.

### ISSUE THREAD

**Issue by aguaviva** [KhronosGroup/glTF-Blender-IO#604] opened 2019-08-01 14:45 UTC
**Describe the bug**
Cameras and lights get exported as 2 nodes

**To Reproduce**
1) create a camera or a light
2) export it as glTF
3) note the two nodes 

>     "nodes" : [
>         {
>             "camera" : 0,
>             "name" : "Camera_Orientation",
>             "rotation" : [
>                 -0.7071067690849304,
>                 0,
>                 0,
>                 0.7071067690849304
>             ]
>         },
>         {
>             "children" : [
>                 0
>             ],
>             "name" : "Camera",
>             "rotation" : [
>                 0.5503501892089844,
>                 0.28839731216430664,
>                 -0.22456789016723633,
>                 0.7506736516952515
>             ],
>             "translation" : [
>                 20.66196060180664,
>                 9.831344604492188,
>                 21.116901397705078
>             ]
>         }, 

In addition each node has a different transformation.  

**Expected behavior**
Having just node would be enough, that way if you want to modify a light programmatically you only have to do it in one node, otherwise you need to take into account the parent nodes, a thing that adds complexity to the code. 

**Version**
 - OS: Win10
 - any recent Blender Version, or 2.80

**Comment by julienduroure** [comment] 2019-08-01 16:42
This was historically intentional, but I don't remember exactly why. Maybe @McNopper can help remember

**Comment by UX3D-nopper** [comment] 2019-08-01 17:38
Blender does have a different default orientation for cameras and lights. Because of this, a helper node was introduced, which does change to glTF dafault orientation.
On a first thought, one could claim, that this orientation could be stored in the "original" node. Yes, but as soon as this node is animated and/or does have children with meshes, the whole thing gets complicated.

**Comment by UX3D-nopper** [comment] 2019-08-01 17:40
So, this is not a bug. Furthermore, a node hierarchy has to be calcuated for other elements anyway.

**Comment by UX3D-nopper** [comment] 2019-08-01 17:42
FRom my point of view, close this issue.

**Comment by aguaviva** [comment] 2019-08-01 17:53
Could the exporter flatten out those two nodes into one? Without this in order to move a light in the engine I need to have different paths for different exporters (that for Blender GLTFs I'd need to look for the helper node and undo that transformation). The more the exporter can simplify the rendering side the better.

**Comment by UX3D-nopper** [comment] 2019-08-01 17:56
Well, the exporter provides valid glTF. This can happen in Blender but also in other glTF files.
Suggest you adapt your engine. Maybe some work today, but much more work in the future if you work around this problem.

**Closed** 2019-08-01 19:29 UTC
Labels: Mesh_&_Object, exporter

**Comment by julienduroure** [comment] 2019-08-01 19:30
Closing this, as there is no easy way to have only 1 node with right data.
This solution is glTF compatible, I will focus on bugs first

**Comment by aguaviva** [comment] 2019-08-01 19:53
Will the importer handle a GLTF file that doesn't use those Blender specific helper nodes?

**Comment by donmccurdy** [comment] 2020-08-06 21:21
@aguaviva sorry for the slow reply. It will, yes.
