### ISSUE TITLE
Incorrect result on import/export a glb file in Blender without editing

### ISSUE THREAD

**Issue by revyTH** [KhronosGroup/glTF-Blender-IO#432] opened 2019-04-15 15:01 UTC
**Describe the bug**
I have a glb file exported from Unity using [https://github.com/KhronosGroup/UnityGLTF](https://github.com/KhronosGroup/UnityGLTF).
This is how the file look:

![image](https://user-images.githubusercontent.com/26633801/56142436-f6b46600-5f9e-11e9-84bc-5cfffb8144ad.png)

Then I import the file in Blender, this is how it looks (correct):

![scene_blender](https://user-images.githubusercontent.com/26633801/56142559-311e0300-5f9f-11e9-994b-735054ca50db.png)

Without any editing, I export the entire scene from Blender in glb format.
This is the result (incorrect):

![image](https://user-images.githubusercontent.com/26633801/56142675-60347480-5f9f-11e9-8ce2-be7ca3847332.png)

**To Reproduce**
1. Import a gltf/glb file in Blender
2. Without editing, export the same file in glb format
3. The result does not look correct after import/export from Blender

**Expected behavior**
The exported file should look identical to the imported one.

**.blend file/ .gltf**
[Scene.zip](https://github.com/KhronosGroup/glTF-Blender-IO/files/3080738/Scene.zip)

**Version**
 - OS: Windows 10, Mac Os High Sierra
 - Blender Version [2.79b]

**Comment by julienduroure** [comment] 2019-04-16 00:24
This is linked to UVMapping. There are 2 of them in glb file.
Seems that TEXCOORD_1 is used by the blender exporter, but TEXCOORD_1 is never used in materials. So seems to be an exporter issue.

**Comment by emackey** [comment] 2019-04-16 19:55
@revyTH Is that 3rd image from Don's viewer?  I think there's still a known issue in ThreeJS where it doesn't support multiple UV maps except on the Occlusion channel.

Try deleting one of the two UV maps from your blend file prior to export, see if that works.

**Comment by emackey** [comment] 2019-04-17 15:04
Unfortunately I think this is a ThreeJS bug.  This exporter is a little aggressive about always exporting all UV maps assigned to a mesh, even if the material doesn't call for all of them.  Some of the maps could possibly be optimized out in some cases, but, it's not a corrupt export or anything.

**Comment by DmitriyMenshayev** [comment] 2020-08-15 18:44
When I add second set of UVs for normals, UV is present int gltf, but texCoord property in material points to the wrong one (TEXCOORD_0 instead of TEXCOORD_1). When I reimport gltf file in blender, it shows wrong UVs (first set of UVs). 
![image](https://user-images.githubusercontent.com/42211512/90319412-e6244f00-df48-11ea-9013-9a30f3639b0e.png)

**Comment by DmitriyMenshayev** [comment] 2020-08-15 18:47
Similar issue #1037

**Comment by donmccurdy** [comment] 2020-12-06 21:50
I'm not able to reproduce this issue from the `.glb` attached above – it opens correctly in my viewer and in Blender, and after re-exporting it still looks correct in both. As @emackey mentions there is a known limitation with multiple UVs on the same mesh in three.js.

@DmitriyMenshayev if you're still having the issue you mention in https://github.com/KhronosGroup/glTF-Blender-IO/issues/432#issuecomment-674434442 with the latest Blender, where Blender export -> Blender import doesn't work, could you include a `.blend` to reproduce that?

**Comment by donmccurdy** [comment] 2021-01-02 20:46
Closing without a way to reproduce the issue, please let us know if this is still a problem and we can test the `.blend` file involved.

**Closed by donmccurdy** 2021-01-02 20:46 UTC
Labels: Material, exporter
