### ISSUE TITLE
Animations Management on the new versions of Blender 3.3 / 3.4 / 3.5

### ISSUE THREAD

**Issue by lyonheart001** [KhronosGroup/glTF-Blender-IO#1823] opened 2023-01-06 17:17 UTC
**Describe the bug**
Did you know that animations are now handled differently with glTF-2 file handling in Blender?  When you import a model in glTF-2 format into Blender 3.3+ versions, your frame rates are now 'frames per second' instead of Key Frames or KF's.

**To Reproduce**
1. Import a model of a fully animated, mapped aircraft.
2. Note an animation that is normally 50, 100, or 200 KF's.
3. Note in the Animation Track slider that an animation that was 100 KF's in MSFS is now 2,400 KF's in Blender.  A 200 KF track is now 4,400 KF's approximately.  Worse yet, is that Blender will no longer 'scale down' the animation track when you change (correct/adjust/fix the track count) but 'slices' the animation track.  So if you select END button/slot and change the setting (length) of the animation track from 2400 KF's to 100 KF's as it should be, Blender 'slices' the track at that point, damaging it.  You must use the Scale setting way down the list on the Animation window management settings.  There you must calculate the approximate point with only 2 digits under the decimal for the massive re-scale of the animation.

**Expected behavior**
1.  Previous Import of a glTF-2 file in MSFS format;
   A. Import Model
   B. Change scale with END key if any re-setting of Key Frames is needed.  Scale automatically adjusts, with all its key frame points, to proper new length.
   C. Import a new glTF-2 file in MSFS format to Blender 3.3+ and your animations are now massively high in counts and cannot scale down unless you use the 'scale' input window and figure out your calculations which could possibly not be able to be properly calculated as there is a low setting 'exactness' to this input window for the length setting of your animation track.

**Screenshots**

**.blend file/ .gltf**
If applicable, a zipped folder containing a .blend file for exporter issues and a .gltf file for importer issues. Please take care to include all resources, such as textures in the .zip file.

**Version**
 - OS: Windows 10
 - Blender Version 3.3 / 3.4 / 3.5

**Additional context**
I contacted the Blender team stating this as a bug, and they said that glTF-2 files should always be brought in as 'Frames per Second', but in all earlier versions, they were brought in as 'Key Frames'.  I believe their new system is bad and not functioning as it should.  We have never had issues with animations before.

I also theorize that this could be the issue with long export times with Blender 3.3, 3.4, and 3.5.  I noticed that with one airplane I imported to 3.3, when I went to export it in glTF-2 MSFS format, it took 10 to 15 minutes and the exports failed every time 'if' the exports had their animations exported with them.  The plane wouldnt show up.  So I believe that the import of glTF-2 files in MSFS format into Blender 3.3+ are corrupted in the animation section and this could explain massive export times.  It could be the new buggy Blender animation management with glTF files is clogging the flow of the export builder.  

Again..  this is only a theory.  I know nothing about building SDK's and barely enough about coding.  I make planes, but use this SDK all day long, all week long, day in and day out.  This is my humble report from the front battle line of whats happening on the new Khronos importer/exporter and the new versions of Blender 3.3+.

Bill
LHC

**Comment by lyonheart001** [comment] 2023-01-06 17:23
A quick note to add to this, above.  When we imported files in glTF-2 format in the past, the Key Frame tracks were proper.  A 100 KF animation track imported as such.  100 in the simulator, 100 when imported to Blender 3.2 and lower.  With Blender 3.3+, your animations are totally changed now.

I talked with Arno about this, who has a very nice exporter that exports the glTF-2 files from MDL format.  He did a 'look over' on the way Blender is handling it and stated he thinks they are not handling the glTF's properly.  I forget his exact words, but he said 'from how you should handle a import of this file type, they are not following the route exactly or properly'.  

The way animations in glTF's are managed has changed quite a bit from what I have seen.

Bill
LHC

**Comment by julienduroure** [comment] 2023-01-06 17:26
Hello,
I think you are referring to this ticket https://developer.blender.org/T102900
You are talking to same people, and already said, glTF specification, animations are in seconds, and we didn't change the way we import it from the beginning of the development.

Please provide a glTF file we can import on both 3.2 and 3.3 and check how it import.

**Comment by lyonheart001** [comment] 2023-01-06 17:27
Hello Julien, 

Can you give me an email to send the link to.  The file is confidential.

Bill
LHC

My email is william at lionheartcreations dott com

**Comment by julienduroure** [comment] 2023-01-11 17:03
For the log, I received 4 mails with 3 zip files.
I am not sure to understand the all explanation, that are quite confuse without the global context.
Uploading simple test case (here some files are 1.2Go !) with easy to reproduce cases will help understand your issue.

Anyway, in the zip files, there is only 1 glTF files (others are .blend file, probably for #1822)

Tested on file Piper Pacer.gltf :

Here are content of accessors -> samplers -> input, for any animations in the file:

![image](https://user-images.githubusercontent.com/1696020/211866472-a354b475-b785-4a1a-9c94-369da78c9e42.png)

Full list here : 
[animations.txt](https://github.com/KhronosGroup/glTF-Blender-IO/files/10394371/animations.txt)

As you can see, most of the animation last 100 --> 100s
In glTF specification, you can see that the unit for animation is second 
https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#animations

> a set of floating-point scalar values representing linear time in seconds

Because the default fps in Blender is 24 
![image](https://user-images.githubusercontent.com/1696020/211867874-298a8e03-62da-4c93-92d3-ba53539c7eda.png)

The most used end of animation (100s) will be 24 * 100 = 2400 frames.
This is what we get in Blender :

![image](https://user-images.githubusercontent.com/1696020/211868449-813ac597-5fb9-43b1-9ad3-03fedd4a0b34.png)

You can use Ctrl+T to see seconds instead of frames in Blender, and you can see 1:40 --> 1min40 = 100s

![image](https://user-images.githubusercontent.com/1696020/211868899-fede8d44-672f-4e0f-874e-bc460c46b995.png)

I got the exact same result in current master and in version 3.2

![image](https://user-images.githubusercontent.com/1696020/211869685-27b70406-cc61-4c5b-8c63-43c673e0207c.png)


Note you can have a different result if you have a different frame rate value in Blender before you import the glTF file.

I can't see any issue here.
Without any new information or new file within a week, I will close this ticket

**Comment by tonypez** [comment] 2023-01-25 21:23
Hello There,

I am having the same issue.
I am using Blender 3.3 and The glTF2 exporter with the 1.1.7 msfs2020 addon.

I have a very complex aircraft interior and exterior file that I am trying to export to the game via the exporter:

**Export times**

Exporting with blender 3.1.2 and msfs2020 exporter 1.1.6
Complex Interior export = 2 min
Complex Exterior export = 1 min

with Blender 3.3 and exporter 1.1.7
Complex Interior export = 55 min
Complex Exterior export = 6 min

Something got screwed with the glTF exporter since blender 3.2 version

I cannot share the scene with you currently since it is confidential.
I am going to try to replicate a dummy of this file, but I am going to need a bit of time, please do not close the thread.

**Comment by julienduroure** [comment] 2023-01-26 07:13
Hello,
This ticket is about importer, not exporter. Your comment is not relevant to this ticket

**Comment by lyonheart001** [comment] 2023-01-26 17:51
> Hello There,
> 
> I am having the same issue. I am using Blender 3.3 and The glTF2 exporter with the 1.1.7 msfs2020 addon.
> 
> I have a very complex aircraft interior and exterior file that I am trying to export to the game via the exporter:
> 
> **Export times**
> 
> Exporting with blender 3.1.2 and msfs2020 exporter 1.1.6 Complex Interior export = 2 min Complex Exterior export = 1 min
> 
> with Blender 3.3 and exporter 1.1.7 Complex Interior export = 55 min Complex Exterior export = 6 min
> 
> Something got screwed with the glTF exporter since blender 3.2 version
> 
> I cannot share the scene with you currently since it is confidential. I am going to try to replicate a dummy of this file, but I am going to need a bit of time, please do not close the thread.


I think it 'might' be related, Julien.  It might be that the exporter and animations are what is causing the long export times.  Its only a theory, but that is why I have been trying to figure out what could be causing the long export times, and it seems like it 'might' be animations related.  Not certain.
I have since gone back to Blender 3.2 using the Ron Haertel custom exporter as its quick and fast, works fine in MSFS.  Sad as its many builds behind in Blender, and 3.6 is coming out soon (Alpha).

**Comment by julienduroure** [comment] 2023-02-25 10:28
More than a month without any new information or confirmation that the problem comes from frame-rate used in Blender before importing the glb file.
Closing this ticket.
If you think you have news that let you think there is really something wrong, please open a new ticket

**Closed by julienduroure** 2023-02-25 10:28 UTC
Labels: question
