### ISSUE TITLE
Cannot export if skeleton is linked

### ISSUE THREAD

**Issue by Favkis** [KhronosGroup/glTF-Blender-IO#921] opened 2020-02-13 07:53 UTC
I have linked skeleton from another .blend file

link skeleton
attach mesh to skeleton
export
done, it crashes

should export like normal model with skeleton

error:
https://media.discordapp.net/attachments/506192854066921478/677416435504513024/unknown.png

windows 10
blender 2.81

**Comment by julienduroure** [comment] 2020-02-13 08:31
Hello,
This is a known issue, duplicate of #500 
I will close this ticket, #500 will remain open until all collection issues are solved (collection instance and linked collection)

**Closed by julienduroure** 2020-02-13 08:31 UTC

**Comment by julienduroure** [comment] 2020-03-07 08:02
@Favkis This is solved by PR #950.
Target is to merge it soon (and will be available in blender 2.83)
